ethereum/py-evm

- .gitmodules
Travis is failing due to not knowing how to auth to github, e.g. [build log](https://travis-ci.org/pipermerriam/py-evm/builds/219093258) for PR #1.
The build machine would need a public key with github to use `git@` URL.
> gitmodules: Use HTTPS instead of git for submodule cloning

- .travis.yml
- evm/utils/fixture_tests.py
- tests/json-fixtures/test_blockchain.py
- tox.ini
Useful to be able to ignore (rather than skip) certain tests.  Also blockchain tests have slow tests which need to be marked.
Added `ignore_fn` as an optional parameter to `find_fixtures` and setup initial structure for marking blockchain tests as slow.
> Small refactor to test gathering

- .travis.yml
- evm/ecc/backends/coincurve.py
- evm/utils/numeric.py
- setup.py
- tests/coincurve-ecc/test_coincurve_ecc_backend.py
- tox.ini
This PR is in response to #25 
@pipermerriam Right now I have `coincurve` as an extra requirement like you suggested.  I'm also testing `coincurve` by comparing it with the pure python implementation.
> Create and test coincurve ecc backend

- tests/json-fixtures/test_transactions.py
This PR is in response to #32 
It enables and fixes the remaining json-fixture transaction tests
http://www.cutestpaw.com/wp-content/uploads/2012/01/baby-tiger.jpg
> Enable and fix remaining transaction tests

- evm/db/__init__.py
- evm/db/backends/base.py
- evm/db/backends/memory.py
- evm/ecc/__init__.py
- tests/core/evm/test_evm.py
- tests/json-fixtures/test_blockchain.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_transactions.py
- tests/json-fixtures/test_vm.py
This PR is in response to #33 
Now py-evm uses a local `MemoryDb` as opposed to the one from `py-trie`
> Create local db backend

- .travis.yml
- requirements-dev.txt
- tox.ini
May be able to speed up travis test runs using xdist parallelization.
Added `ADDOPTS="-n 3"` to split tests across 3 processes.  Lets see if it's faster.
> try to speed up travis runs

- evm/chain.py
- tests/core/block-utils/test_blocks.py
- tests/core/gas_meter/test_gas_meter.py
Since unit tests are, by definition, untested, it's always a good idea to make them as short/straightforward as possible, without [conditional logic](http://xunitpatterns.com/Conditional%20Test%20Logic.html) or [hard-coded variables that need to match those from a fixture](http://xunitpatterns.com/Obscure%20Test.html#Mystery%20Guest)
This PR refactors those tests so that they no longer include any of the above.
> Some improvements to test_blocks and test_gas_meter

- evm/chain.py
- evm/rlp/headers.py
- evm/vm/flavors/frontier/headers.py
- evm/vm/flavors/homestead/headers.py
It was easy to accidentally create a new BlockHeader with a difficulty that did not match the
header's timestamp, which would lead to a ValidationError when trying to mine the block.
Changed BlockHeader.from_parent to make the timestamp arg required instead of defaulting to the
current time.
> BlockHeader.from_parent: timestamp arg is now required

- evm/vm/code_stream.py
- tests/core/code-stream/test_code_stream.py
Codestream processing was insecure
Updated codestream processing algorithm
> Update is_valid_opcode security

- evm/chain.py
- evm/logic/call.py
- evm/logic/context.py
- evm/logic/storage.py
- evm/logic/system.py
- evm/utils/fixture_tests.py
- evm/vm/base.py
- evm/vm/computation.py
- evm/vm/flavors/frontier/__init__.py
- evm/vm/flavors/frontier/blocks.py
- evm/vm/flavors/frontier/validation.py
- evm/vm/flavors/homestead/__init__.py
- evm/vm/flavors/homestead/headers.py
- tests/core/chain-object/test_chain.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/test_blockchain.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_vm.py
Issue #67
The state db is no longer stored as an instance variable anywehre; instead it is always accessed
via the VM.state_db() contextmanager, which takes care of updating the header's state_root on
exit.
One important thing to note is the fact that now the header's state_root is updated multiple times
during, say, the processing of a transaction (because there are multiple methods called to perform
that, and several of them make use of the state_db contextmanager), whereas before it'd only be
updated once, at the very end of the tx processing. Because of that, if we now have an uncaught
exception while adding a transaction to a block, we may end up with the wrong state_root, but
an uncaught exception there probably means we have a bug that prevents us from processing the
block anyway, …
> VM: state_db is accessible only via a contextmanager now

- evm/utils/address.py
- evm/utils/secp256k1.py
- evm/validation.py
- tests/core/validation/test_validation.py
The same code for validating public keys was used in two different places.
That code was extracted into a new function in evm.validation.validate_raw_public_key
> Create public key validation function

- evm/chain.py
- evm/consensus/pow.py
- evm/precompile.py
- evm/state.py
- evm/utils/blocks.py
- evm/validation.py
- evm/vm/code_stream.py
- evm/vm/computation.py
- evm/vm/flavors/frontier/blocks.py
- evm/vm/flavors/frontier/headers.py
- evm/vm/flavors/frontier/transactions.py
- evm/vm/flavors/homestead/headers.py
- evm/vm/flavors/homestead/transactions.py
- evm/vm/gas_meter.py
- evm/vm/message.py
- setup.py
When a validation error occurred, it would often have a cryptic message such as:
> "Value 28 is not less than or equal to 0"
It was really difficult to divine where this message originated from and what it was validating.
All of the `validate_x` functions now accept an optional `title` parameter.  When provided, the corresponding message would then look something like this
```python
validate_lte(..., title="Block Number")
```
> "Block Number 28 is not less than or equal to 0"
> better validation error messages

- evm/chain.py
- evm/utils/rlp.py
- evm/validation.py
- evm/vm/base.py
- evm/vm/flavors/frontier/headers.py
- evm/vm/flavors/homestead/headers.py
- tests/core/fixtures.py
- tests/core/vm/test_vm.py
* The `Chain.ensure_blocks_are_equal` seemed to only exist because it needed to be overridden in some tests.
* Needed a `Chain.mine_block()` function for non-import based blockchain advancement.  This is needed in #92 
* The `configure_homestead_header` function delegated to the `configure_frontier_header` function, but only to perform the validation of the `header_params`.
* Modified the test fixture that needed this override and moved this to a utility function.
* Added a `Chain.mine_block()` API
* Moved the `header_params` validation to a stand-alone function and decoupled the two frontier and homestead functions.
> Piper/add chain.mine block api

- evm/chain.py
- evm/utils/chain.py
- evm/vm/flavors/__init__.py
- evm/vm/flavors/frontier/blocks.py
- evm/vm/flavors/tester/__init__.py
- tests/core/tester/test_generate_vm_configuration.py
Blocker for: https://github.com/pipermerriam/ethereum-tester/pull/14
Py-EVM needs a *tester* chain that can be used with testing.  Primary features needed are:
* bypass POW validation
* easy configuration for starting blocks for the various hard forks
* easy initialization of the chain with custom state
Added a new `Chain` subclass under `evm.vm.flavors.tester` with these properties.
> Implement MainnetTesterChain

- evm/p2p/ecies.py
The private key generation was not appropriately being padded to 32 bytes
Added padding.
> fix private key padding for private key generation

- .travis.yml
- evm/precompile.py
- evm/utils/transactions.py
- setup.py
Upstream update to `ethereum-keys` API
Bumped version
> Upgrade to ethereum-keys v0.1.0-alpha.7

- evm/p2p/auth.py
- evm/p2p/test_peer.py
These peers are configured with matching auth secrets and have their
readers/writers connected directly so we can test roundtrips for
protocol-specific interactions.
> New test fixture that gives us two directly connected p2p peers

- evm/p2p/auth.py
- evm/p2p/constants.py
- evm/p2p/exceptions.py
- evm/p2p/peer.py
Similar to auth.handshake(), but this one performs the P2P handshake and
only returns a peer when there are matching sub-protocols.
Also use a timeout on Peer.read() and an asyncio.Event so that Peer.stop() only
returns when the Peer.start() coroutine exits.
> Implement peer.handshake()

- evm/exceptions.py
- evm/logic/flow.py
- evm/logic/system.py
- evm/vm/base.py
- evm/vm/forks/frontier/__init__.py
- tests/conftest.py
* The `vm.apply_computation` implementation was standard enough that it wasn't being overridden by any of the VM subclasses.
* The opcodes which cause the VM to halt were hard-coded.
* Created a new `Halt` exception that opcodes can raise if they wish to cause VM execution to halt.
* Move the implementation of `apply_computation` into the `BaseVM` class since it doesn't look like it will need to be overwritten.
> Remove hard coded HALT opcodes in favor of exception pattern

- evm/p2p/discovery.py
- evm/vm/code_stream.py
- requirements-dev.txt
- tox.ini
And fixes a couple issues caught by 3.5.0 that were not caught by the previous version (3.3.0)
Without this we can, all of a sudden, start seeing [failures](https://travis-ci.org/pipermerriam/py-evm/jobs/291541039) when there's a new version of flake8
> Pin flake8 version to 3.5.0

- evm/db/chain.py
- tests/database/test_chaindb.py
All blocks were getting an extra GENESIS_DIFFICULTY added to their score
since BaseChainDB.get_score() considered that to be the score of the
genesis' parent, which is obviously wrong.
> Fix a bug in the calculation of a block's score

- evm/chains/chain.py
- evm/db/chain.py
- tests/core/chain-object/test_chain.py
The Chain class used to do that, but now it's done as part of BaseChainDB.persist_header_to_db().
I needed this on another branch I'm working on (which changes the LightChain so that it can handle possibly diverging data from multiple peers), but this seemed like a worthwhile refactoring in itself so I'm submitting it separately
> Update canonical chain info whenever we store a header in the DB

- tests/database/test_chaindb.py
One of the chaindb tests was using `os.urandom` to provide testing randomness.  While this is a fine strategy, using hypothesis is arguably better for this type of test.
Switched to use hypothesis to generate the randomness.
> use hypothesis for random test

- evm/p2p/auth.py
- evm/p2p/discovery.py
- evm/p2p/kademlia.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/test_auth.py
- evm/p2p/test_kademlia.py
- evm/p2p/test_peer.py
The generator-based coroutines have some limitations (e.g. not possible to yield values from them) and pitfalls that are not present on native coroutines. Since we don't intend to support python 3.4, there's no reason for us to use the generator-based approach
> Change from generator-based to native coroutines

- .travis.yml
The parallelism for CI was set to 3 cores.  During the Byzantium testing this was causing some of the workers to fail.  CI machines only actually have 2 cores.
Changed to only use 2 workers
> Reduce CI parallelism from 3 to 2 cores

- evm/logic/context.py
The logging message for the `CALLDATACOPY` gas usage didn't use consistent terminology
Changed it to use `CALLDATACOPY` in the reason.
> cleanup reason for CALLDATACOPY

- evm/rlp/headers.py
The `BlockHeader` object `repr` method was not implemented making the terminal representation not contain any useful information.
Added a `__repr__` method that shows block number and hash for headers.
> Add a repr method for BlockHeader object

- evm/vm/computation.py
The assignment of `Computation.output` did not do any type validation.
Added validation that the assigned value is `bytes`.
> Add validation to computation.output

- evm/vm/forks/frontier/__init__.py
The term `gas_cost` was being used where elsewhere these are referred to as `gas_fee`
Renamed the variable to use `gas_fee`
> Rename gas_cost to gas_fee

- evm/logic/call.py
- evm/logic/system.py
- evm/vm/computation.py
The way in which child computations were done left room for error.  It was possible to execute a child computation but fail to append it to the children of the parent computation.
Added a new API onto the `Computation` object called `apply_child_computation` which has all of the necessary logic correctly grouped together for executing child messages.
> Add apply_child_computation to Computation object

- evm/utils/padding.py
Padding utils needed some easier to use APIs for common cases.
Curried the main functions and then made some pre-curried helpers for common cases of left and right padding with zeros and to 32 bytes.
> Improvements to padding utils

- evm/vm/base.py
During initialization of the `BaseVM` objects there was a check for whether the `chaindb` was `None`.  This was a carry-over from a previous version where the db was part of the class definition.
Removed the check.
> Refactory BaseVM initialization handling of chaindb

- evm/db/state.py
- evm/vm/forks/frontier/__init__.py
Should speed up the Byzantium tests
> State.touch_account(): don't call _set_account() for existing accounts

- .bumpversion.cfg
- README.md
- evm/__init__.py
- evm/__version__.py
- setup.py
* Some meta information was wrong after the recent migration to the ethereum foundation github
* No docs for how to cut a release.
* Upstream dependency library names have changed
* Removed the `__version__.py` in favor of embedding all information in `setup.py`
* fixed dependency names `ethereum-` to be `eth-`
* Added bumpversion based release process
* Fixed markdown rendering for pypi
> Misc cleanup

- .travis.yml
- tests/json-fixtures/test_state.py
There are some JSON fixture tests which take a *long* time to run.  This slows down the turnaround time in ci
Skipped them during normal CI runs.  They will run in a cron job daily on travis.
> skip slowest tests during ci, run them in cron

- Makefile
- docs/conf.py
- docs/low_level.rst
The autodocs weren't building, which meant that the low-level API page was empty, and the deep links to class docs were broken.
Build locally the same way RTD builds. Hook autodoc into the vanilla `sphinx-build` process via docs/conf.py.
I tested this branch against the live RTD site. It works.
> docs: build more consistent with readthedocs

- docs/quickstart.rst
- evm/p2p/exceptions.py
- evm/p2p/les.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/protocol.py
- evm/p2p/test_peer.py
This allows us to avoid unnecessarily fetching the same headers from
all peers we're connected to.
Now we also retry a few times if we get a timeout when fetching headers
from a peer.
> Move header-syncing code from LESPeer to LightChain

- evm/chains/chain.py
- evm/vm/base.py
- evm/vm/forks/frontier/blocks.py
- requirements-dev.txt
Type info about the keyword args to `mine_block` was not apparent in the low-level api docs.
Adding the docstrings with parameter type info, to autopopulate the low-level api docs on RTD.
> docstrings: a bit more mine_block info

- tox.ini
fixes #186 
By default, tox does not pass through environment variables.  This was causing the `TRAVIS_EVENT_TYPE` environment variable to not be present when the test suite checked if it should run the slow tests.
Added it to the whitelist in `tox.ini`
> make slow tests run in travis

- docs/building_chains.rst
- docs/conf.py
- docs/quickstart.rst
- evm/lightchain_shell.py
- evm/p2p/lightchain.py
- evm/p2p/test_peer.py
- evm/rpc/server.py
- requirements-docs.txt
Also extend the quickstart and building_chains docs, and add the asyncio
sphinx extension so that coroutines get special treatment in docs.
> lightchain_shell: run LightChain in the background of interactive shell

- evm/p2p/exceptions.py
- evm/p2p/les.py
- evm/p2p/peer.py
- evm/p2p/protocol.py
Protocol.process_handshake() must now raise that exception to signal a
handshake failure, which will then cause the peer to be disconnected.
> Introduce a new exception to signal handshake failures

- docs/quickstart.rst
- evm/lightchain_shell.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/test_lightchain.py
- evm/rpc/server.py
- Log to a file in lightchain_shell
- Rename Peer.stop_and_wait_until_finished() to stop()
- lightchain.py, lightchain_shell.py and rpc/server.py now connect to ropsten by default
- peer.py no longer takes a db/mainnet arg as it no longer handles sync
> p2p and rpc: a few misc fixes

- evm/db/chain.py
- evm/db/state.py
- evm/utils/state_access_restriction.py
- evm/vm/base.py
- tests/core/access-restrictions-utils/test_checks_and_conversion.py
- tests/core/chain-object/test_chain.py
- tests/core/fixtures.py
- tests/core/vm/test_state_access_restrictions.py
- tests/database/test_state.py
This PR adds an alternative way of storing state as described in #191.
It depends on two not yet implemented trie methods:
- `Trie.delete_branch(key)` that should delete all keys that start with `key` (to delete the whole storage of an account)
- `Trie.branch_exists(key)` that checks if there is a key that starts with `key` (to check if an account exists)
State is always stored RLP encoded as that's the way it used to be in the two layer design. However, I don't really see a good motivation for that anymore as all entries are either integers (nonces, balances, storage entries) or binary (code), whereas in the old design we had a slightly more complex object (account).
> Account redesign

- LICENSE
No LICENSE file. See #231 
Added a MIT license under the name specified in setup.py
> included license file

- evm/db/chain.py
- evm/db/state.py
- evm/p2p/lightchain.py
- setup.py
Change to use `HexaryTrie` instead of deprecated `Trie` from the py-trie library.
Changed to use `HexaryTrie`.
> upstream changes to py-trie

- evm/rlp/transactions.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/frontier/transactions.py
- evm/vm/forks/homestead/transactions.py
Rename `intrensic` to `intrinsic`
Change `constants` module import to local module import
> Minor naming and import fix

- evm/vm/base.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/frontier/vm_state.py
- evm/vm/forks/homestead/__init__.py
- evm/vm/forks/homestead/vm_state.py
- evm/vm_state.py
I deeply apologize for that in the previous refactoring, the `validate_transaction` should be moved from `VM` to `VMState`. The current codebase misses calling `validate_homestead_transaction`.
Implement `VMState.validate_transaction` by moving the logics from `VM.validate_transaction` to `VMState.validate_transaction`.
> Bugfix: should move `validate_transaction` from `VM` to `VMState`

- evm/chains/chain.py
- evm/db/chain.py
- evm/exceptions.py
- evm/utils/db.py
- evm/vm/base.py
- tests/core/chain-object/conftest.py
- tests/core/chain-object/test_chain.py
- tests/core/vm/test_vm.py
Need to be able to look up transactions by hash
Split transaction lookups in two for now (in three to four later)
1. **Done:** Transactions in the canonical chain
2. **Done:** Pending transactions issued locally
3. **Punt:** pending transactions received by peers for txpool
4. **Punt:** transactions in blocks that fall off the canonical chain (This is really just a special case of 2 or 3 above. I think most of the work to do is figuring out whether a transaction is from pool 2 or 3 when it falls off the canonical chain.)
Chain API changes:
- `chain.get_canonical_transaction(txn_hash)` -- find a transaction in the canonical chain
- `chain.get_pending_transaction(txn_hash)` -- find a pending transaction (only works for locally issued transactions, for now)
- …
> Look up transaction by hash

- evm/utils/env.py
- tests/core/env-utils/test_env_bool.py
- tests/core/env-utils/test_env_float.py
- tests/core/env-utils/test_env_int.py
- tests/core/env-utils/test_env_list.py
- tests/core/env-utils/test_env_string.py
- tests/core/env-utils/test_get.py
`evm.utils.env` needed to be backported to `master`.
Copied the `evm.utils.env` module and `tests/core/env-tests` directory to `master` from `sharding` branch.
> Backport evm.utils.env and related tests from sharding branch

- setup.py
- tests/sharding/test_vmc_handler.py
* In the latest `eth-tester`, there is some usage of the latest syntax in py-evm master branch, which is not yet merged(rebased) to py-evm sharding branch. This cause CI errors in sharding branch.
* Moreover, since `TransactionFailed` is added in `eth-tester` recently and is not caught by `web3.py`, which causes tests to fail.
* Specify the version of `eth-tester` to `0.1.0b12`
* Modify the test code to catch `eth_tester.exceptions.TransactionFailed`, instead of `web3.exceptions.BadFunctionCallOutput`
> Fix CI errors

- evm/chains/chain.py
- evm/db/__init__.py
- evm/estimators/__init__.py
- evm/estimators/gas.py
- evm/rlp/transactions.py
- evm/utils/spoof.py
- evm/vm/base.py
- tests/core/chain-object/test_chain.py
- tests/core/helpers.py
- tests/core/vm/conftest.py
- tests/core/vm/test_vm.py
#264 - Want to easily estimate gas usage of a transaction.
Now fully fixes #264 
- Add two gas estimators to `Chain`.
- The simplest one just runs the transaction to see how much gas was used, and multiplies the estimate by 2. The estimator cannot return an amount higher than the gas set in the transaction. It might under-guess the gas if there is a long chain of calls (because it doesn't account for the 63/64 gas passed to subcall)
- The more complicated one does binary search, (roughly) as defined in #264
- Add `gas_used_by(computation)` API to Transaction (for now, just intrinsic cost + gas used)
- Generate the state of a temporary block on top of the current header. This allows us to estimate gas taking into account the pending state, but still have a full block's worth of gas …
> Two new gas estimators

- evm/db/chain.py
- evm/db/state.py
- evm/logic/call.py
- evm/p2p/test_state.py
- evm/utils/state_access_restriction.py
- evm/vm/forks/sharding/opcodes.py
- pytest.ini
- tests/auxiliary/user-account/test_contract.py
- tests/core/fixtures.py
- tests/core/vm/test_sharding_vm.py
- tests/database/test_account_state_db.py
> Avoid usage of account_exists

- evm/chains/chain.py
- evm/computation.py
- evm/rlp/blocks.py
- evm/utils/datatypes.py
- evm/vm/base.py
- evm/vm_state.py
`Configure` classmethod was repeated across different classes. 
Wrote `evm.utils.datatypes.Configurable` base class for classes to inherit from. 
Classes changed. . .
`evm.rlp.blocks.BaseBlock`
`evm.vm.base.VM`
`evm.chains.chain.Chain`
`evm.computation.Computation`
`evm.vm_state.VMState`
closes #245
> Convert configure to base class

- evm/vm/forks/sharding/opcodes.py
Gas cost of the new SIGHASH opcode was set to 0.
Gas cost was set to GAS_BASE (2). This seems reasonable to me as similar environmental constants have the same cost (TIMESTAMP, CALLER,  GASPRICE, ...)
> Set gas cost of SIGHASH

- evm/p2p/constants.py
- evm/p2p/eth.py
- evm/p2p/exceptions.py
- evm/p2p/les.py
- evm/p2p/lightchain.py
- evm/p2p/p2p_proto.py
- evm/p2p/peer.py
- evm/p2p/protocol.py
- evm/p2p/state.py
- evm/p2p/test_auth.py
- evm/p2p/test_lightchain.py
- evm/p2p/test_peer.py
P2P message processing was scattered across methods from multiple classes (Protocol,
Peer, LightChain).
Also, the sub-protocol matching was designed to allow a connection to a single remote
node to use various different protocols, but that's not useful now and may never be.
Started consolidating msg processing on Peer methods. Now Protocol/Command methods
only deal with encoding/decoding of messages
Changed sub-protocol matching to pick just one sub-protocol
Better to review both commits separately, I believe
> p2p: Redesign sub-protocol matching and msg processing

- evm/chains/chain.py
In the `trinity` branch, I'm finding that I need to be able to do mult-step configuration for the chain classes.  The way that the `configure` method is written, it requires the `vm_configuration` be passed in each time (even if it's already been configured)
* Modified `Chain.configure` to have `vm_configuration` be optional.
This should be fine since the `Chain.__init__` does perform a validation check that `self.vms_by_range` is configured.
> Make vm_configuration optional to allow multi-step configuration

- evm/db/__init__.py
extracted from https://github.com/ethereum/py-evm/pull/310
The API for the `get_db_backend` was recently change in proper accordance with YAGNI.  However, I gonna need it.
Reverted the change to allow passing in an import path.
> Revert get_db_backend to take an import path

- evm/computation.py
- evm/logic/call.py
- evm/logic/context.py
- evm/logic/storage.py
- evm/logic/system.py
- evm/rlp/transactions.py
- evm/vm/forks/sharding/computation.py
- evm/vm/forks/sharding/vm_state.py
- evm/vm/message.py
- tests/auxiliary/user-account/test_contract.py
- tests/core/helpers.py
- tests/core/vm/test_shard_vm.py
Replaces #276 (I suck at rebasing and thought rewriting this would be faster -- probably mistakenly, but well...).
1) transaction access list is converted to prefix list at initialization (that's the format used in the rest of the code)
2) state accessibility is checked during transaction execution (both during pre- and post-processing and for all opcodes), using `computation.state_db` when available.
3) access lists are passed down from transaction to message and from message to child message (see also #262)
4) `test_sharding_vm` and user account contract tests have been updated to provide transactions with correct access lists
When fixing 3) I noticed the use of `prepare_child_message` was not consistent: `BaseComputation` has methods `prepare_child_message` and …
> Fix transaction execution

- evm/logic/call.py
Since
1. `FlatTrieBackend`
2. `Binary Trie`
is adopted in Sharding, `touch_account` doesn't seem to be needed because account's `code_hash`, `balance` and `nonce` now belongs to different trie entries. Also, initializing these attributes to `b''` has no effect in a `Binary Trie`.
However since we no longer create a new account like we used to, we should not charge `create_gas_fee` but instead (1)separately charge for setting `code_hash`, `nonce` and `balance` if not been set before. Or (2)we still charge it but multiply it by x(say 3 since there will be 3 trie entries for one account, but I'm not sure that's all the reason it's charged `25000` gas for creating a new account).
At first thought there doesn't seem to be an easy and clean way to charge separately so I personally would prefer …
> Adjust create account fee in Sharding

- evm/p2p/eth.py
- evm/p2p/exceptions.py
- evm/p2p/lightchain.py
- evm/p2p/p2p_proto.py
- evm/p2p/peer.py
- evm/p2p/protocol.py
- evm/p2p/test_lightchain.py
- evm/p2p/test_lightchain_integration.py
- evm/p2p/test_peer.py
Now BasePeer only handles P2P msgs (via the handle_p2p_msg()) method, and
places sub-proto messages onto a queue to be consumed by our services (e.g.
LightChain)
Also get rid of the Command.handle() method; last step in order to have
Protocol/Command responsible only for encoding/decoding of data.
> p2p: Redesign sub-protocol msg processing

- evm/db/chain.py
- evm/vm/forks/frontier/vm_state.py
- evm/vm_state.py
part 1 of #331: make configurable `trie_class` in `master` branch.
1.  Made `trie_class` to be configurable in `BaseChainDB.__init__`.
2. To generate `trie_data`, added `trie_class` in `VMState` and set `trie_class = HexaryTrie` in `FrontierVMState`.
> Configurable trie_class

- evm/exceptions.py
- evm/logic/call.py
- evm/logic/system.py
- evm/vm/forks/sharding/blocks.py
- evm/vm/forks/sharding/computation.py
- evm/vm/forks/sharding/opcodes.py
- evm/vm/forks/sharding/vm_state.py
- evm/vm/message.py
- tests/auxiliary/user-account/test_contract.py
- tests/core/fixtures.py
- tests/core/helpers.py
- tests/core/vm/contract_fixture.py
- tests/core/vm/test_PAYGAS_tx_fee.py
- tests/core/vm/test_shard_vm.py
Implementation of #234 
* Carry additional informations such as `transaction_gas_limit`, `paygas_gasprice ` and `paygas_total_fee` in `ShardingMessage` object
* `transaction_gas_limit` is the same as `transaction.gas`
* `paygas_gasprice ` is set by `PAYGAS` opcode and only under two conditions:
1. in a top level call(i.e., `computation.msg.depth == 0`)
2. the value has not been set before during this transaction
* If the two conditions are not met, current action is to do nothing.
* `paygas_total_fee` is equal to `transaction_gas_limit * paygas_gasprice`
* Once triggered, deduct `paygas_total_fee` from transaction initiator(`transaction.to`)'s balance
* Refund fee is calculated base on `paygas_gasprice` instead of `transaction.gas_price`
* Opcode value is currently set as ~~`0x5c`~~ …
> Add PAYGAS opcode

- evm/lightchain_shell.py
- evm/p2p/integration_test_helpers.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/protocol.py
- evm/p2p/state.py
- evm/p2p/test_auth.py
- evm/p2p/test_lightchain.py
- evm/p2p/test_lightchain_integration.py
- evm/p2p/test_peer.py
Instead of taking a single callback to be called when a new peer is
added, PeerPool now can have multiple subscribers that will be notified
when new peers are added.
Also LightChain is no longer responsible for creating/running a PeerPool
itself
This way we can share a single PeerPool among multiple p2p services.
> p2p: PeerPool now has subscribers that get notified of new peers

- evm/db/chain.py
- evm/rlp/collations.py
- evm/rlp/headers.py
- evm/vm/forks/sharding/collations.py
- tests/database/test_chaindb.py
This pull request adds a Collation and CollationHeader classes. I used the Block and BlockHeader classes in the current master as a model, so they are very slim. Only functionality added is the ability to get witnesses from `BaseChainDB` (using `py-trie`s `get_witness_for_key_prefix`) which is needed for `Collation.from_header`. I wrote a test for this, which unfortunately fails. I believe the reason for this is that `get_witness_for_key_prefix` has been written for `BinaryTrie` instead of `HexaryTrie` (which is still in use), but would appreciate feedback by @NIC619 on that matter. If this is confirmed I'd mark it as `xfail`ing (as switching to `BinaryTrie` should be done in another PR).
@hwwhww Is there anything missing?
> Add Collation and CollationHeader classes

- tests/database/test_chaindb.py
CI fails because the `get_nonce_key` doesn't exist anymore.
Simply removed `get_nonce_key` from `tests/database/test_chaindb.py`.
> Remove `get_nonce_key` in tests

- evm/chains/chain.py
- evm/db/chain.py
- evm/rlp/headers.py
Another patch for switching transaction and receipt tries (#331) , and also prepare for switching State trie (#289).
The empty `HexaryTrie` root is `BLANK_ROOT_HASH` and empty `BinaryTrie` root is `EMPTY_SHA3`, so it requires setting the default root by `chaindb.trie_class`.
> Configurable trie_class in master branch - part2

- setup.py
- tests/trinity/chain-management/test_is_chain_initialized.py
- tests/trinity/chains-utils/test_chain_config_object.py
- tests/trinity/conftest.py
- tox.ini
- trinity/README.md
- trinity/__version__.py
- trinity/chains/__init__.py
- trinity/chains/ropsten.py
- trinity/constants.py
- trinity/main.py
- trinity/utils/chains.py
- trinity/utils/db.py
- trinity/utils/logging.py
- trinity/utils/xdg.py
There are a small number of things that need to be in place in order to run a chain.
- chain directory structure created
- chaindb initialized wtih genesis data
- nodekey
Added detection for whether these things are initialized and code to do intelligent initialization.  Note that this is just a start, as it won't handle cases where it's a custom chain with custom genesis data, etc.
This PR currently special cases a number of things that will need to be polished out (such as only supporting the ropsten chain and light sync mode.
> Add automatic chain initialization of chain directories to trinity.

- tests/trinity/cli/test_trinity_repl.py
- trinity/cli.py
- trinity/main.py
Implements #302. Ports the initial work done in #298 
Added support for Python REPL to trinity CLI. Running `trinity console` starts either an IPython, if it is installed, or a Python REPL. The shell comes loaded with chain variable that can be used while it's syncing. Running `trinity --log-level info console --vanilla-shell` sets the log level as `INFO` and run the default Python shell even if IPythin is installed on the system.
Chain syncing continues in the background while the shell is running in the foreground. Starting the REPL starts the chain syncing in a thread instead of a process. This is unlike trinity CLI which starts syncing in a separate process.
The reason for using multithreaded syncing instead of multiprocess is when we use a Python REPL we need to share the same …
> Initial support for trinity REPL

- evm/__init__.py
- evm/chains/__init__.py
- evm/chains/mainnet/__init__.py
- evm/chains/mainnet/constants.py
- evm/chains/ropsten/__init__.py
- evm/chains/ropsten/constants.py
- evm/vm/forks/homestead/__init__.py
These block numbers come from
https://github.com/ethereum/cpp-ethereum/blob/develop/libethashseal/genesis/ropsten.cpp.
Update comments and standardize constant names across both Ropsten and
Mainnet chains.
Closes https://github.com/ethereum/py-evm/issues/301.
Ropsten chain was using Mainnet chain fork block numbers.
By pulling in the correct Ropsten chain block numbers from cpp-ethereum.
> Fix hard fork block numbers for Ropsten chain

- docs/building_chains.rst
- docs/quickstart.rst
- evm/db/chain.py
- evm/lightchain_shell.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/state.py
- evm/p2p/test_lightchain.py
- evm/p2p/test_lightchain_integration.py
- evm/p2p/test_peer.py
- evm/rpc/server.py
- evm/utils/fixture_tests.py
- evm/utils/state.py
- evm/vm/base.py
- tests/core/fixtures.py
- tests/core/vm/test_vm.py
- tests/core/vm/test_vm_state.py
- tests/database/test_chaindb.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_transactions.py
- tests/json-fixtures/test_virtual_machine.py
When I see an object named `BaseXXX` I generally think of it as something that requires inheritance, or at least that you build on top of.  The way that our `BaseChainDB` object is used does not fit this model and the `Base` prefix adds some level of confusion (in-my-humble-ish-opinion)
Established a `BaseChainDB` class which has stub methods for all of the *public* API.
Renamed the original `BaseChainDB -> ChainDB` and re-organized the class methods to be grouped by functionality.
> Note that this is in preparation for the work in trinity to relegate the ChainDB execution to it's own process.
> Rename BaseChainDB to ChainDB and establish base API

- evm/db/state.py
- evm/rlp/headers.py
- evm/utils/db.py
- evm/vm/forks/sharding/__init__.py
- evm/vm/forks/sharding/headers.py
- evm/vm/forks/sharding/vm_state.py
- tests/auxiliary/user-account/test_contract.py
- tests/core/chain-object/conftest.py
- tests/core/chain-object/test_chain.py
- tests/core/fixtures.py
- tests/core/vm/conftest.py
- tests/core/vm/test_PAYGAS_tx_fee.py
- tests/core/vm/test_shard_vm.py
- tests/core/vm/test_state_access_restrictions.py
- tests/core/vm/test_vm.py
- tests/core/vm/test_vm_state.py
- tests/database/test_chaindb.py
Fix #289
Fix #331 
1. For the sharding VM tests, set `chaindb.trie_class` to `BinaryTrie`.
2. Set empty trie roots to `EMPTY_SHA3`.
3. Made `ShardingAccountStateDB` based on `BinaryTrie`.
4. Updated default roots of `CollationHeader`.
5. Refactored `tests.core.fixture`.
> Switch all tries to BinaryTrie

- evm/computation.py
- evm/logic/context.py
- evm/transaction_context.py
- evm/vm/forks/frontier/computation.py
- evm/vm/forks/frontier/transaction_context.py
- evm/vm/forks/frontier/vm_state.py
- evm/vm/forks/spurious_dragon/utils.py
- evm/vm/message.py
- evm/vm_state.py
- tests/core/message-object/test_message_object.py
- tests/core/vm/test_base_computation.py
- tests/core/vm/test_frontier_computation.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_virtual_machine.py
Creating a PR to track this work in progress. From #262.
> Add transaction_context object to Computation

- setup.py
When installing requires for `py-evm`, the version of `eth_utils` installed is not the latest one. This results in the import error in `eth_account` in CI, since it requires the newer `eth_utils`
Modify the version of `eth_account` in `setup.py `
> Use the latest eth-utils

- evm/chains/chain.py
- evm/db/chain.py
- evm/utils/db.py
- evm/utils/state.py
- evm/validation.py
- evm/vm/base.py
- evm/vm_state.py
- tests/core/chain-object/conftest.py
- tests/core/chain-object/test_chain.py
- tests/core/fixtures.py
- tests/core/vm/conftest.py
- tests/core/vm/test_vm.py
- tests/core/vm/test_vm_state.py
As mentioned at https://github.com/ethereum/py-evm/issues/312#issuecomment-365233568, this is the part 1 (for master branch).
1. Backported from sharding branch:
* fixture refactoring
2. Removed `create_block` in master branch. Will update a `BinaryTrie` version in `sharding` branch.
3. Refactored and fixed trie switching
4.  `evm.utils.db.get_empty_root_hash function` -> `chaindb.empty_root_hash`
> Some clean up for sharding

- evm/chains/chain.py
evm/evm.py contained typos in the docstrings
typos were corrected
> DOC: fix typos in evm docstrings

- evm/lightchain_shell.py
- evm/p2p/cancel_token.py
- evm/p2p/discovery.py
- evm/p2p/exceptions.py
- evm/p2p/lightchain.py
- evm/p2p/peer.py
- evm/p2p/state.py
- evm/p2p/test_cancel_token.py
- trinity/cli.py
- trinity/main.py
CancelTokens should be passed to any async operation, and whenever
they are trigger()ed they cause those operations to be cancelled. It was
inspired by http://goo.gl/MUFMKU and right now is used mainly to ensure
we cancel pending operations when terminating services
> Implement CancelToken and use it everywhere

- evm/computation.py
- evm/logic/call.py
Statement `if not child_computation.should_burn_gas:` is not intuitive enough and confusing sometimes.
Add a new property `should_return_gas` which is the opposite of `should_burn_gas` and use `should_return_gas` to replace `if not child_computation.should_burn_gas:` statement.
> Add `should_return_gas` to replace `not should_burn_gas` statement for clarity

- evm/chains/chain.py
We need a definition of the `Chain` API.
Established an `evm.chain.chain.BaseChain` class with a stubbed out version of the current `Chain` API.
> Establish a BaseChain class

- trinity/cli_parser.py
- trinity/main.py
The `trinity.main` module was feeling crowded.
Moved the `argparse` parser definition to `trinity.cli_parser`
> Trinity: move argparse parser to own module

- p2p/cancel_token.py
- p2p/discovery.py
- p2p/ecies.py
- p2p/kademlia.py
- p2p/les.py
- p2p/lightchain.py
- p2p/p2p_proto.py
- p2p/peer.py
- p2p/protocol.py
- p2p/state.py
- tests/p2p/test_cancel_token.py
- tox.ini
- trinity/cli.py
- trinity/rpc/main.py
- trinity/utils/logging.py
By default it only checks the code of a func/method if it is typed, so
I changed the command line we use in TOX to ask it to check untyped defs
as well.
Also added an extra switch to disallow incomplete type annotations (i.e.
require func/methods to annotate all args and return value).
Those new checks caught a few bugs, that I've fixed as well
> Make mypy check bodies of untyped functions as well

- pytest.ini
Tests were green for xfail tests that were unexpectedly passing.
Added `xfail_strict=true` to `pytest.ini`.
> Add xfail=strict to pytest.ini

- docs/building_chains.rst
- evm/chains/base.py
- evm/opcode.py
- evm/utils/datatypes.py
- evm/vm/forks/byzantium/__init__.py
- evm/vm/forks/byzantium/opcodes.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/frontier/opcodes.py
- evm/vm/forks/homestead/__init__.py
- evm/vm/forks/homestead/opcodes.py
- evm/vm/forks/sharding/__init__.py
- evm/vm/forks/sharding/opcodes.py
- evm/vm/forks/spurious_dragon/__init__.py
- evm/vm/forks/spurious_dragon/opcodes.py
- evm/vm/forks/tangerine_whistle/__init__.py
- evm/vm/forks/tangerine_whistle/opcodes.py
- tests/core/chain-object/test_chain_retrieval_of_vm_class.py
- tests/core/datatype-utils/test_configurable_class.py
- tests/core/fixtures.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_virtual_machine.py
- tests/p2p/test_lightchain_integration.py
- trinity/chains/ropsten.py
Currently, if you wanted to use the `MainnetChain` with a different set of opcodes, you would be required to duplicate a *lot* of code to properly reconfigure all the way down to the correct deeply burried objects to swap out the opcodes.
This pull requests gets us a step closer to being able to do that easily, by allowing configuration of sub-properties.
```python
class Inner(Configurable):
attr_a = 'value-a'
class Outer(Configurable):
attr_b = Inner
NewClass = Outer.configure(**{'attr_b.attr_a': 'new-value-a'})
assert NewClaass.attr_b.attr_a == 'new-value-a'
```
This allows us to *reach* into sub-properties that are also of the `Configurable` type and do sub-configuration.
> Allow deep property configuration in Configurable classes

- .gitignore
- evm/utils/address.py
- evm/utils/bn128.py
- evm/utils/chain.py
- evm/utils/datatypes.py
- evm/utils/db.py
- evm/utils/env.py
- evm/utils/headers.py
- evm/utils/numeric.py
- evm/utils/padding.py
- evm/utils/spoof.py
- evm/utils/state_access_restriction.py
- evm/utils/transactions.py
- p2p/discovery.py
- tox.ini
`evm/utils` lacks type hints (see #132)
This PR adds most of the needed type hints for `evm/utils`. I left out some parts that I I want to follow up later. Also some type hints that were set to `Any` can probably be tighten up if one gives it more thought. I believe this will be an iterative process until we have 100 % coverage.
> Add type hints for most of evm/utils

- evm/constants.py
- evm/utils/blobs.py
- tests/core/test_blob_utils.py
As I couldn't find anything more important to do, I went ahead and wrote some small utils for blobs which should hopefully be useful when the new spec is finalized.
> Blob utility functions

- p2p/peer.py
That is another error that can be raised by reader.readexactly(), and it
wasn't being handled before
> p2p: Handle BrokenPipeErrors when reading from remote peer

- evm/chains/base.py
- evm/computation.py
- evm/db/backends/base.py
- evm/db/chain.py
- evm/db/state.py
- evm/logic/call.py
- evm/opcode.py
- evm/rlp/blocks.py
- evm/rlp/collations.py
- evm/rlp/transactions.py
- evm/vm/base.py
- evm/vm_state.py
- p2p/peer.py
- tests/core/vm/test_base_computation.py
- tests/p2p/test_auth.py
Abstract methods did not use the `abc.abstractmethod` decorator (see #466)
Added decorator
> Implement abc.abstractmethod pattern

- p2p/chain.py
Before, the requested block numbers always included the last one from
the previous batch.
> p2p: Fix ChainSync to request non-overlapping header batches

- p2p/auth.py
- p2p/peer.py
- requirements-dev.txt
- setup.py
See https://github.com/ethereum/eth-hash/issues/10 for more info
This is what was causing fast-sync to slow to a crawl after running for only a few minutes. With this change we should be able to actually complete a full-node sync
This is intended as a temporary solution while we work on a fix for eth-hash
> p2p: Revert from eth-hash to pysha3 to fix performance issues

- evm/vm/forks/frontier/vm_state.py
- evm/vm/forks/spurious_dragon/vm_state.py
- evm/vm_state.py
**Note:** Purpose of this pull-request is to get the ball rolling on issue #368 and come up with an initial refactoring so as to formalize the API.
`execute_transaction` functionality for different forks could benefit from some code re-use.
I created a `BaseTransactionExecutor` to be implemented by Frontier and SpuriousDragon forks (for now). The implementations, overriding the `run_pre_computation`, `run_computation`, and `run_post_computation` methods, are used as mixins in the corresponding VM state classes.
My API of `BaseTransactionExecutor` does not comply with what was suggested in #368. This is largely due to strong coupling between the three computation phases, thereby not allowing me to split them in a clean fashion. This is the API in this pull-request:
- …
> Generic transaction executor

- p2p/eth.py
- p2p/les.py
- p2p/peer.py
- p2p/rlp.py
Needed because BaseTransaction now uses metaclass=ABCMeta and thus
cannot be instantiated.
> p2p: Use a separate Transaction class in Commands

- Makefile
- evm/computation.py
- evm/logic/call.py
- evm/logic/context.py
- evm/logic/logging.py
- evm/logic/memory.py
- evm/logic/sha3.py
- evm/logic/system.py
- tests/core/vm/test_base_computation.py
Currently, the Computation object houses lots of information and sub-APIs for things like maniputlating the stack, consuming gas, etc. This creates a lot of public API surface area since we are effectively support two public APIs for anything needed from a sub-property of the Computation object.
Computation.memory is the API for getting at the Memory
Computation.memory.read is the API for reading from memory.
Computation.memory -> Computation._memory
Computation.memory.read() -> Computation.memory_read()
Computation.memory.write() -> Computation.memory_write()
> memory_read and memory_write

- tests/trinity/core/chain-management/test_initialize_data_dir.py
- tests/trinity/core/chain-management/test_initialize_database.py
- tests/trinity/core/chain-management/test_is_data_dir_initialized.py
- tests/trinity/core/chain-management/test_is_database_initialized.py
- tests/trinity/core/chains-utils/test_chain_config_object.py
- trinity/chains/__init__.py
- trinity/chains/mainnet.py
- trinity/chains/ropsten.py
- trinity/cli_parser.py
- trinity/constants.py
- trinity/main.py
- trinity/utils/chains.py
No support for syncing with the mainnet.
Added ability to sync with mainnet via `trinity` cli.  Also modified some internals to use `network_id` as the primary identifier for choosing what network you want to use.
> Add support for mainnet syncing to Trinity

- .gitignore
- docs/building_chains.rst
in "evm.chains.mainnet.__init.py"
there is import `from evm import constants`
which make `import evm.chains.mainnet as mainnet` throw error 
because  `evm.constants` did't contain `HOMESTEAD_MAINNET_BLOCK`
just import `from evm.chains.mainnet import HOMESTEAD_MAINNET_BLOCK`
instead of  `import evm.chains.mainnet as mainnet`
and call `HOMESTEAD_MAINNET_BLOCK` in `vm_configuration`
then every thing will work fine
> docs: evm.chains.mainnet.constants error 

- p2p/chain.py
- p2p/peer.py
- tests/p2p/integration_test_helpers.py
We were seeing timeouts too frequently and because of that I'd introduced
an eager retry mechanism, but it turns out those timeouts were because we
had too many cpu-intensive tasks that were blocking the main thread and
thus preventing the asyncio main loop from processing received msgs fast
enough. Now that those cpu-intensive tasks are performed in sub-processes,
we rarely see timeouts and in those cases it generally means the peer has
disconnected so instead of retrying we simply abort the sync with that
peer, which causes it to be resumed with a different peer.
Depends on #492
> p2p: Redesign handling of timeouts in ChainSyncer

- .travis.yml
- requirements-dev.txt
- tox.ini
Fixes #497
`mypy` was still on version `0.560`.
Upgraded to `0.580`. We had to split CI task to support this. We now run one CI job against `mypy` on Python 3.5 for the `evm` and another one on Python 3.6 for `trinity` and `p2p`. Similar to what we do with the `flake8` jobs. 
Unrelated, did we ever consider to run both `flake8` and `mypy` in one `lint` job so that we are down to just one job per Python version? We would go from 4 jobs (`flake8py35`, `flake8py36`, `mypy35`, `mypy36`) to 2 jobs (`lintpy35`, `lintpy36`).
> Upgrade mypy to version 0.580

- evm/__init__.py
- evm/computation.py
- evm/utils/logging.py
- evm/vm/gas_meter.py
- evm/vm/memory.py
- evm/vm/message.py
- evm/vm_state.py
- tests/conftest.py
- tests/core/memory/test_memory.py
- tests/core/vm/test_base_computation.py
Missing type hints
This adds type hints for `evm/computation` and some related classes. 
However, apart from just adding type hints, this introduces some supportive changes.
1. Instead of mutating `Logger` to add a `trace` method it introduces a `TraceLogger` and calls the `logging.setLoggerClass(...)` API to register it.
2. At places where we request a logger via `logging.getLogger('some.logger')` we do a `cast(TraceLogger, logging.getLogger('some.logger')` to give `mypy` a hint about the type (a `cast` doesn't do anything apart from hinting `mypy` what to assume about the type).
3. All the wiring of the trace logging was moved to a `setup_trace_logging` API in `evm.utils.logging`
4. I still left the `logging.TRACE = TRACE_LEVEL_NUM` but I'm actually tempted to get rid of that as well …
> Add more type hints

- p2p/eth.py
- p2p/rlp.py
Use an immutable variant of BlockHeader that also caches its RLP
representation.  By doing that we can compute the header's hash only
once, significantly improving performance when performing a chain sync.
> p2p: Use a custom BlockHeader implementation to improve performance

- p2p/chain.py
- p2p/peer.py
This way the main loop can keep running and consuming peer messages while
sub-processes are running the cpu-intensive tasks.
> p2p: ChainSyncer._handle_peer() no longer waits for handle_msg()

- trinity/cli_parser.py
Before, this is what got output when running `trinity --help`
```bash
$ trinity --help
usage: trinity [-h] [--version] [-l {debug,info}]
[--network-id NETWORK_ID | --ropsten]
[--sync-mode {full,light} | --light]
[--trinity-root-dir TRINITY_ROOT_DIR] [--data-dir DATA_DIR]
[--nodekey NODEKEY] [--nodekey-path NODEKEY_PATH]
{console,attach} ...
Trinity
positional arguments:
{console,attach}
console             run the chain and start the trinity REPL
attach              open an REPL attached to a currently running chain
optional arguments:
-h, --help            show this help message and exit
--version             show program's version number and exit
-l {debug,info}, --log-level {debug,info}
Sets the logging level
--network-id NETWORK_ID
Network identifier (1=Mainnet, 3=Ropsten)
--ropsten …
```
> add structure to the trinity cli commands

- evm/vm/forks/sharding/vm_state.py
Didn't set Binary Trie when generating transaction trie in Sharding(default to Hexary Trie) and result in node parsing error when trying to fetch value with Hexary Trie data in a Binary Trie.
Specify Binary Trie as trie_class in `make_trie_root_and_nodes`.
> Fix wrong trie class in generating transaction trie in Sharding

- evm/vm/base.py
- tests/sharding/fixtures.py
The `VM.apply_transaction` was invoking the `VMState.apply_transaction` in a very odd way, accessing the method on the class and passing in the `state` for the `self` argument, when it could instead simply invoke the method directly from the `state` variable.
Changed to directly invoke the method.
> Fix weirdness in how VM.state.apply_transaction was executed

- evm/vm/base.py
- evm/vm/forks/byzantium/__init__.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/homestead/__init__.py
- evm/vm/forks/sharding/__init__.py
- evm/vm/forks/spurious_dragon/__init__.py
- evm/vm/state.py
- tests/p2p/test_lightchain_integration.py
Both the `VM` and the `VMState` had the `block_class` defined.
This removes the `block_class` from `VM` and delegates to the `get_block_class` API of the `VMState` instead. Fixes #513
> Remove block_class from VM

- p2p/chain.py
We now fetch a batch of headers and then all the bodies/receipts for those
headers before persisting them. This makes the code a lot easier to follow
but also guarantees our ChainDB always has full blocks for everything up to
the current chain head.
> p2p: Redesign the fast-sync mechanism

- evm/vm/base.py
- tests/core/chain-object/test_chain.py
- tests/core/helpers.py
~Note, please wait for #397 to get merged, before merging this. It's a big one, and I don't want to be responsible for delaying it. :)~ _397 merged, and conflicts resolved via rebase_
`chain.estimate_gas(txn)` fails with a `ValidationError`, if there is a transaction already in the block.
`vm.state_in_temp_block()` is designed to make sure that a fresh block is available for estimating gas. However, the receipts created in `vm.get_state()` were always the receipts of the canonical head, rather than the receipts from the `header` passed to `get_state`. So some transactions were added to the temporary block. (and probably some other bad things were happening... it's a little surprising that no tests got triggered)
- Fixed `vm.get_state()` to create the receipt list based on the supplied …
> Fix gas estimation when a transaction is in the block

- evm/chains/tester/__init__.py
- evm/vm/base.py
- evm/vm/forks/byzantium/__init__.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/homestead/__init__.py
- evm/vm/forks/spurious_dragon/__init__.py
- evm/vm/forks/tangerine_whistle/__init__.py
- pytest.ini
- tests/core/tester/test_generate_vm_configuration.py
link: https://github.com/ethereum/web3.py/issues/729
The way that `evm.chains.tester.MainnetTesterChain` was done, it would require an update to the fork block number configuration for every new set of fork rules.  It also didn't allow extension with custom vms.
- Modified the `BaseVM` class to have a record of the *name* of the fork.
- Modified the helper function which generates the VM fork rules to derive it's available VMs from the `MainnetChain`
- Simplified the logic some so that it expects very explicitly defined start blocks and doesn't try to be *smart*.
> Adjust how MainnetTesterChain configures VMs to not require updates for every fork rule

- evm/chains/tester/__init__.py
- tests/core/tester/test_generate_vm_configuration.py
continuation of #521 
In my refactor it became invalid to not provide a vm that starts at block 0.  This is actually problematic for how this API is used in `eth-tester`.
Now if no vm is specified for block 0, it defaults to using the frontier vm.
> allow for vm configuration that doesn't include block 0

- evm/db/chain.py
- evm/vm/base.py
IIUC, `BaseVM.apply_transaction()` takes care of persisting the tx trie to the DB, and `ChainDB.persist_block()` was generating the trie just to assert the transaction_root is what we expect
> Move transaction_root validation out of ChainDB.persist_block()

- evm/vm/forks/byzantium/state.py
It was comparing the MAX_UNCLE_DEPTH to the uncle's block number instead
of to the block number delta.
> evm/vm: Fix max uncle depth validation

- evm/db/chain.py
Leftover type hints pointing at the now removed `BaseCollation` class.
Removed.
> mypy fix for removed BaseCollation

- docs/conf.py
I tried working on the docs but running `make html` in `docs` just left me with
```
$ make html
Running Sphinx v1.7.2
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3.5/objects.inv...
usage: sphinx-build [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
sphinx-build: error: the following arguments are required: -o/--output-dir
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```
I admit that I have never worked with `sphinx` before so there's a high chance that I'm doing it completely wrong. I tried to figure out if there's a @carver pattern to the rescue and noticed that I can build the docs for `eth-account` without problems.
In the …
> Fix doc generation task

- evm/vm/base.py
Not sure what maxsize to use, but assuming that method is used most of the time
to lookup the state of the current head, I think a large maxsize won't provide any benefit. The main motivation for the cache was actually to reduce the number of times we perform this during the importing of a single block, and it reduced the total time by 30% in that case.
Part of the fixes for #542
> Add an lru cache to BaseVM.get_prev_hashes()

- eth_typing/__init__.py
- eth_typing/misc.py
- evm/consensus/pow.py
- evm/constants.py
- evm/rlp/blocks.py
- evm/rlp/headers.py
- evm/rlp/transactions.py
- evm/utils/headers.py
- evm/vm/computation.py
- evm/vm/forks/frontier/constants.py
- p2p/rlp.py
As discussed in #499 for certain usages of `bytes` (and potentially others) we can benefit from introducing a NewType so that the type system forbids calling an API that expects an `Address` with just any other arbitrary bytes.
Implemented `Address` and `Hash32` NewType and used where appropriate.
> Convert addresses and hashes to NewTypes

- evm/db/batch.py
Type hint was missing making the linting on Travis fail (see e.g. https://travis-ci.org/ethereum/py-evm/jobs/367371776#L510).
Added the type hint.
> Add type hint for BatchDB.cache

- tests/core/test_blob_utils.py
As pointed out by @gsalgado Travis crashed sometimes (?) when executing the blob serialization tests, due to a very long reported test name. The test name was auto generated by `@pytest.mark.parametrize` using a 1MB collation body as parameter.
Pass an explicit test id to `@pytest.mark.parametrize` at the relevant tests.
> Shorten test ids for blob serialization tests

- evm/chains/base.py
- evm/vm/base.py
- evm/vm/state.py
- tests/core/chain-object/test_chain.py
- tests/core/helpers.py
- tests/core/vm/test_vm_state.py
We used to generate the tries for all block's transactions/receipts
after applying every transaction, but that is way too expensive. Now the
trie data is only generated once, after we've applied all transactions
> Redesign receipt/tx trie generation on block imports

- evm/chains/shard.py
- evm/db/shard.py
- evm/rlp/collations.py
- evm/rlp/headers.py
- tests/core/chain-object/test_shard.py
- tests/core/sharding/test_collations.py
- tests/database/test_shard_db.py
Shard chain class was missing.
A basic shard chain class has been added, along with some minor changes in the shard db.
Right now it's a very thin wrapper around the shard db. Originally I had implemented some additional functionality, but I was unsure what we'll actually end up using so I removed all but the most basic stuff. I think extending it on the go as needed is the better approach.
> Shard chain

- p2p/state.py
This way we make better use of peers with higher throughput and achieve
much faster syncs
> p2p: StateDownloader no longer sends requests to peers with pending requests

- .gitignore
What was wrong?
The directory was renamed to `.pytest_cache` in Pytest 3.4.0 so the directory was coming up in version control when using a newer Pytest version
Configured it to be set to `.cache` as it was before.
> Set fixed pytest cache dir

- p2p/exceptions.py
- p2p/peer.py
Peer used to simply close its network transport upon receiving a
Disconnect msg, which causes us to exit the read loop because our
next readexactly() call will then raise an IncompleteReadError, but
then it looks like the remote simply sent an EOF, which is not actually
the case.
Now when we receive a Disconnect msg we raise an exception, which gets
caught in Peer.read_loop(), causing it to return and the peer to finish
cleanly.
> p2p: Cleanly break out of read loop when remote disconnects

- .readthedocs.yml
- setup.py
ReadTheDocs can't build the docs anymore hence the last online version dates 4 months back.
Add `.readthedocs.yml` with the right settings (hopefully).
Ideally I'd test this on a separate branch directly here in the repo but I don't have write access yet so I hope these settings should just cut it.
> Fix broken ReadTheDocs build

- .readthedocs.yml
- setup.py
Mix of singular and plural in group names of dependencies
Made all singular as this is the common scheme across the different ethereum libraries.
> Fix small inconsistencies in dependency groups

- evm/db/chain.py
- evm/db/journal.py
- evm/vm/base.py
- evm/vm/state.py
- tests/database/test_journal_db.py
As discussed in #561 the current implementation of the `JournalDB` imposes efficiency problems on the system as every `set` and `delete` operation causes an extra `get` operation on the underlying db.
The new `JounalDB` works as follows.
`.record()` - starts recording and returns a `changeset_id` where all changes are recorded in. Nothing is written to the db. Any `set` and `delete` actions that are recorded into the active changeset. No extra `get` calls are made on the underlying database.
`.discard(changeset_id)` - throws away all changes that were recorded in the given changeset. Again, the underlying db isn't hit for any of this.
`commit(changeset_id)` - merges the given changeset into the previous changeset. If the previous changeset is the root changeset, the changes are written …
> Refactor JournalDB for efficiency

- p2p/auth.py
- p2p/constants.py
- p2p/peer.py
- p2p/server.py
- tests/p2p/dumb_peer.py
- tests/p2p/test_server.py
After auth handshake, the server should apply P2P handshake.
1. Add `Server.apply_p2p_handshake(peer)` function to apply p2p handshake.
2. Add `tests/p2p/test_server.py::test_two_servers` for simulating two servers. `server_1` is the bootstrap node for `server_2`, `server_2` will try to connect to `server_1`.
3. Use `DumbPeer` instead of `ETHPeer` for testing. (**No sub-protocol handshake yet**)
4. Add a testing daemon in `server.py` (basically, referred to `chain.py`).
* Run `server_1` (the bootstrap node):
```bash
python -m p2p.server -debug -server-address 127.0.0.1:33333 -privkey b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291
```
* Run `server_2`:
```bash
python -m p2p.server -debug -server-address 127.0.0.1:30303 -bootstrap …
```
> p2p: Testing P2P handshake

- evm/db/chain.py
- evm/db/state.py
- evm/vm/base.py
- evm/vm/state.py
https://github.com/ethereum/py-evm/commit/f6ffc5e5f78557133f348074fb17be2f2bcc383d introduced a regression where not all important data was written into the db (See #606).
This is an alternative approach to #607 that tries to address the problem with a less hacky solution. At its core, this PR doesn't really address the problem differently than #607 because it still boils down to another `persist()` call after block finalization.
However, this PR already paves the way for a more isolated usage of the `JournalDB` which *should* only be used for the transaction processing. This PR doesn't take it that far but it already removes the journaling APIs from the `ChainDB` entirely and introduces them on the `MainAccountStateDB` instead.
> Remove JournalDB usage from ChainDB

- evm/chains/base.py
- evm/db/chain.py
- evm/utils/db.py
- evm/vm/base.py
- tests/core/chain-object/test_chain.py
When working on something else I came across those APIs that were only used in a couple tests
Removed them!
> Get rid of APIs related to pending transactions

- evm/chains/base.py
- evm/vm/base.py
- evm/vm/state.py
- tests/conftest.py
- tests/core/chain-object/test_build_block_incrementally.py
- tests/core/chain-object/test_chain.py
- tests/core/conftest.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/core/vm/test_vm_state.py
- tests/json-fixtures/test_state.py
Fixes #579 
The way in which `eth-tester` uses py-evm requires the ability to incrementally apply transactions to the `tip` block and then to mine the block when ready.
Care is being taken to ensure that `VM.import_block` is still able to operate with a low amount of overhead when importing the block.
> **This is still a work in progress**
Implemented `Chain.add_transaction`.
> Incremental block construction

- evm/vm/base.py
`BaseVM` had an unused `clear_journal` method left.
Removed it
> Remove dead clear_journal method

- evm/consensus/pow.py
- evm/db/account.py
- evm/db/chain.py
- evm/db/hash_trie.py
- evm/rlp/headers.py
- evm/rlp/transactions.py
- evm/tools/fixture_tests.py
- evm/utils/address.py
- evm/utils/blobs.py
- evm/vm/base.py
- evm/vm/forks/frontier/blocks.py
- evm/vm/forks/frontier/computation.py
- evm/vm/forks/frontier/state.py
- evm/vm/forks/homestead/computation.py
- evm/vm/forks/spurious_dragon/computation.py
- evm/vm/logic/sha3.py
- p2p/auth.py
- p2p/discovery.py
- p2p/kademlia.py
- p2p/peer.py
- p2p/state.py
- tests/core/test_blob_utils.py
- tests/database/test_account_db.py
- tests/database/test_chaindb.py
- tests/fillers/build_json.py
- tests/json-fixtures/test_state.py
- tests/json-fixtures/test_virtual_machine.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_discovery.py
- tests/p2p/test_lightchain_integration.py
The eth_utils version was intended to be a convenience wrapper adding
support for arg types other than bytes, but that has a significant
performance overhead and is not needed in py-evm, so import directly
from eth_hash
Yet another change in our efforts to address #542
> Import keccak() from eth_hash instead of eth_utils

- evm/chains/base.py
- evm/db/account.py
- evm/tools/test_builder/builder_utils.py
- evm/utils/db.py
- tests/json-fixtures/test_state.py
The `AccoutDB.apply_state_dict` API was just a convenience API used mostly in testing.  The only place it was used outside of testing was during setup of genesis state.
Removed it from the `AccountDB` in favor of a stand-alone utility function.
> Remove apply_state_dict API

- evm/chains/base.py
- evm/db/account.py
- evm/db/chain.py
- evm/tools/test_builder/builder_utils.py
- evm/vm/state.py
- tests/p2p/test_state_sync.py
link: #611 #507 #599 
The `AccountDB` class used the property `AccountDB.root_hash`.  This value represents the `Header.state_root` and is more appropriately named `state_root`.
Renamed it.
> Piper/rename account db.root hash to account db.state root

- evm/utils/logging.py
The `trace` logger was broken in how it passed up the `args` to the main logger.
Added a `*`
> fix vm trace logger

- Makefile
- evm/chains/base.py
- evm/db/chain.py
- evm/vm/base.py
- tests/core/chain-object/test_chain.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/test_state.py
- tox.ini
Related to #599 & #507 - VM returns partially-completed block objects as a result of `apply_transaction()`
Return the header instead, and let `chain` deal with building the block (at the appropriate time). As a bonus, we build fewer block objects during `vm.import_block()`.
*TODO in follow-up PR: decide how to deal with the exact some problem with `header` which is only partially formed (no state/receipt root) -- maybe this is where a `TransactionDiff` comes in`*
> Return header instead of block from vm.apply_txn

- .readthedocs.yml
Our live doc site is currently broken not showing any of the API docs as seen here.
This PR fixes it as seen on the following screenshot (notice the URL. This is live on a special `doctest` branch that I pushed into this repo but will delete again now)
Apparently readthedocs had issues building our API docs with Python 3.5 (which should work in general, trio uses Python 3.5 for rtd as well and has no issues with the autodoc feature). Instructing readthedocs to build with Python 3.6 instead fixes the issue.
> Use Python 3.6 to generate docs

- evm/chains/base.py
- evm/vm/base.py
- evm/vm/forks/byzantium/__init__.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/frontier/state.py
- evm/vm/forks/frontier/validation.py
- evm/vm/forks/homestead/state.py
- evm/vm/forks/homestead/validation.py
- evm/vm/state.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/test_state.py
Related to #599 & #507 - there was state mutation inside `VM.apply_transaction()`, to update `gas_used`, and `get_block_by_header` lived in VM (we're generally looking to move block manipulation out of VM, into Chain).
There wasn't really any need for `gas_used` to be in the state, we can verify the transaction against the header in the VM, before even calling `state.apply_transaction`.
- add a new transaction verification, explicitly against the header
- make_receipt new uses the header to generate the cumulative gas used
- apply_transaction now builds on top of a passed-in header (rather than using a local mutation of `self.block.header`)
- `get_block_by_header` really needed to belong in Chain instead of VM.
- use only `account_db` instead of the full state to validate transaction …
> Delete gas used from state

- p2p/peer.py
Most of the current p2p nodes there haven't been responding lately or already have too many peers, so I digged a few more (via geth's admin.peers console cmd).
> Add more Ropsten peers to HardCodedNodesPeerPool

- setup.py
That release seems to be doing a lot more checks by default, and we're not ready for that yet. More info at http://mypy-lang.blogspot.pt/2018/05/mypy-0600-released.html
> Pin mypy to versions before 0.600

- Makefile
- evm/vm/base.py
- evm/vm/forks/byzantium/__init__.py
- evm/vm/forks/byzantium/state.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/forks/frontier/state.py
- evm/vm/forks/homestead/__init__.py
- evm/vm/forks/homestead/state.py
- evm/vm/forks/spurious_dragon/__init__.py
- evm/vm/forks/spurious_dragon/state.py
- evm/vm/state.py
Related to #599 & #507 
- state shouldn't care about `block_class` at all
- variable mutation internal to method that applies transactions sequentially
- moved `block_class` to VM
- this concept of applying a series of data one on top of the other seems oft-repeated in blockchains, so made a reusable `pipe_accumulator` to handle this case, and hopefully others.
> Block class to vm

- p2p/chain.py
- p2p/sync.py
- tests/p2p/integration_test_helpers.py
- tests/trinity/core/chains-utils/test_chain_config_object.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/chains/__init__.py
- trinity/cli_parser.py
- trinity/db/chain.py
- trinity/main.py
- trinity/utils/chains.py
- trinity/utils/mp.py
Trinity used to support only light sync; now it supports both light and full sync
Also:
* Changed the default from light to full sync, as light is very unreliable since we can't find peers
* Includes fixes for #580 and #632
> trinity: Add support for full node syncing and run that by default

- p2p/server.py
That was problematic because it would not return for 2s as long as
asyncio.Task.all_tasks() is not empty, and that will never be empty
since _wait_pending_tasks() runs as an asyncio task itself.
> p2p: Remove Server._wait_pending_tasks()

- evm/db/account.py
- evm/db/backends/base.py
- evm/db/backends/level.py
- evm/db/backends/memory.py
- evm/db/batch.py
- evm/db/chain.py
- evm/db/journal.py
- evm/db/shard.py
- tests/database/test_base_db_api.py
- tests/database/test_batch_db.py
The BaseDB was almost, but not quite, compatible with `collections.abc.MutableMapping`. That seemed to add an unnecessary burden on readers to understand/remember the differences.
The main differences were:
- `get(key, default=None)` now acts just like it does on other mappings (returning `None` by default, rather than raise an exception) -- required fixes in various places of the code
- Add `collections.abc.MutableMapping` as a superclass of `BaseDB`
- some renamings of internal implementations, to align with how `MutableMapping` works
- added an optional `_exists` method that can be strictly typed (since `__contains__` cannot be).
> Make DB compatible with MutableMapping

- p2p/server.py
- tests/p2p/test_server.py
When receiving a connection, `p2p.Server` did only perform the p2p handshake but not the sub protocol handshake.
Do the sub protocol handshake after a successful p2p handshake.
> Perform sub proto handshake in server

- evm/db/batch.py
- evm/db/diff.py
- tests/database/test_batch_db.py
- tests/database/test_db_diff.py
Many classes share access to a bunch of database state, and different layers all necessarily share the same view of the state. This leads to hard-to-reason-about code.
One step on the way there is to explicitly track changes to a database, and share those changes. Because the changes can include deletes, it's not *quite* as easy as a simple `dict`, but almost. A new `DBDiff` (read-only) and `DBDiffTracker` (read/write) were added to unify any key/value diffs that we pass around between classes.
Instead of modifying a database in place, this enables classes to return diffs that were a result of their actions. The calling method can keep the diff in memory, drop it, or apply it, at the leisure of the caller.
> A new DBDiff and DBDiffTracker, to track db changes

- p2p/DEVELOPMENT.md
- p2p/auth.py
- p2p/cancel_token.py
- p2p/chain.py
- p2p/discovery.py
- p2p/kademlia.py
- p2p/peer.py
- p2p/server.py
- tests/p2p/test_server.py
In some places we were not using CancelTokens at the deepest possible level
of the call stack, and as a consequence we were cancelling tasks that had
created sub-tasks and when those sub-tasks were destroyed by the event loop
(because their parents had been cancelled), we were getting ERROR messages
in the logs
(https://docs.python.org/3/library/asyncio-dev.html#pending-task-destroyed)
This makes sure we use CancelTokens correctly and also adds some docs on
how to do so.
> p2p: Ensure correct and consistent use of CancelTokens

- .gitignore
- evm/__init__.py
- evm/chains/base.py
- evm/db/chain.py
- evm/exceptions.py
- evm/vm/__init__.py
- evm/vm/base.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/vm.py
- p2p/lightchain.py
- tests/core/vm/test_frontier_computation.py
- tests/database/test_chaindb.py
The `Chain`, `ChainDB` and `VM` API and classes were not as well organized as they could be.  
- Methods were not consistently grouped
- Methods were not consistently ordered
- Docstrings duplicated across base and implementation classes.
- No implementation class for `VM`
- All `BaseXXX` classes are now pure abstract classes with no implementation details.
- Docstrings have been removed from `BaseXXX` classes with the exception of a few `BaseVM` methods which do not have default implementations in the main `VM` implementation class.
- Method ordering is now done by hierarchically sections (Header -> Block -> Transaction -> ...)
- Method ordering within a section is now alphabetical.
- Docstrings have been created for all methods on implementation classes (`Chain`, `ChaindB`, `VM`)
- …
> Cleanup to the Chain, ChainDB and VM classes and their base classes.

- p2p/chain.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/server.py
- p2p/service.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_lightchain.py
- tests/p2p/test_lightchain_integration.py
- tests/p2p/test_server.py
- trinity/main.py
We had several classes for our different services and they all had
slightly different APIs for running/stopping them. BaseService aims
to provide a standard API for that.
Includes #673 , so better to review that one first
> p2p: Implement a BaseService class and use it everywhere

- docs/guides/evm/architecture.rst
- docs/guides/evm/building_chains.rst
- docs/guides/evm/creating_opcodes.rst
Typos and misformatting in docs' guides section.
`aspell` and reading. :)
Source: [Fort Bragg Library](http://fortbragglibrary.org/paws-to-read/hedgehog-reading/).
> Documentation: fix typos in "Guides" section

- p2p/peer.py
PeerPool's main loop used to catch any exceptions, log them, restart all
peers and continue in the loop. This was useful because our services
generally run the PeerPool in the background (with `asyncio.ensure_future`),
but it turns out this is problematic because sometimes when exiting the
main process the PeerPool's main loop may get an exception
(a RuntimeError, because the event loop has been closed) before the
parent service has had a chance to tell the PeerPool to shut down, so we
end up in an infinite loop with the PeerPool catching those
RuntimeErrors and trying to restart all peers.
> p2p: PeerPool no longer restarts itself on unexpected exceptions

- evm/chains/shard.py
- evm/rlp/collations.py
- evm/rlp/headers.py
- p2p/sharding.py
- tests/p2p/test_sharding.py
Goal:
For the tests I've tried to setup two local nodes that are connected to each other (https://github.com/ethereum/py-evm/compare/master...jannikluhn:sharding-protocol?expand=1#diff-f7c78d280d6b0f400c831d798adf0781R152), but I didn't manage to do that (the `assert` checking if the nodes are connected fails). Since I've been stuck for quite some time on that and haven't made much progress, could someone who's familiar with the networking code could have a quick look?
> Attempt at a very simple sharding protocol

- evm/db/account.py
- evm/db/cache.py
- tests/p2p/test_state_sync.py
Right now, when an account changes multiple times within a transaction, then we:
- waste time calculating keccak on intermediate state
- waste time doing trie manipulation on intermediate state
- store unnecessary data for intermediate account values
- Journal the raw account values, before entering them into the trie. 
- Replaced values get dropped in the journal, in between calling `persist`, so they never hit the trie
Right now, this will save state at every `persist` call. We can do even better, saving it only at the end of every block, but this PR was getting full.
Side note: The account cache started returning stale results, because the state_root is no longer updated at every change. I tried to fix it in place, with a sprinkling of cache invalidations, but it was taking too long to …
> Journal before trie

- p2p/DEVELOPMENT.md
- p2p/chain.py
- p2p/peer.py
- p2p/server.py
- p2p/sharding.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/integration_test_helpers.py
- tests/p2p/test_server.py
- tests/p2p/test_sharding.py
- trinity/cli_parser.py
- trinity/main.py
With this, when we run trinity we'll also be listening for incoming peer
connections
Part of #651
> trinity: Use p2p.Server instead of running FullNodeSyncer directly

- p2p/chain.py
- p2p/service.py
- p2p/sharding.py
- p2p/state.py
- p2p/sync.py
There were multiple subclasses of the `Service` class all implementing the same logic for conditionally chaining it's cancel token with a parent token.
Moved the logic into the constructor for the base `Service` class.
> Move setup logic for token to Service class

- evm/vm/forks/homestead/transactions.py
See https://github.com/ethereum/py-evm/issues/692
Override the intrinsic gas calc in HomesteadUnsignedTransaction with homestead variant.
> Override homestead instrinsic gas calc in HomesteadUnsignedTransaction

- p2p/server.py
- setup.py
The `UPNP` code was only trying the first device.
Updated to loop over all devices to attempt port forwarding.  Also handle devices without the `WANIPConn1` property.
> UPNP across all found devices

- docs/guides/evm/building_chains.rst
- evm/chains/base.py
- evm/chains/header.py
- evm/db/chain.py
- evm/tools/fixture_tests.py
- p2p/chain.py
- p2p/server.py
- p2p/sync.py
- tests/core/chain-object/test_chain_retrieval_of_vm_class.py
- tests/core/conftest.py
- tests/database/test_chaindb.py
- tests/p2p/test_lightchain_integration.py
- tests/p2p/test_server.py
- trinity/chains/__init__.py
- trinity/main.py
The `Chain` class expected a `ChainDB` instance to be instantiated.  Changing this to be a `base_db` will make the transition to having the `Chain` use the `HeaderDB` easier.
The `Chain` class now expects a `base_db` and it instantiates its own `ChainDB` instance.
> Change `Chain` class to expect a `BaseDB` instance for instantiation.

- evm/chains/base.py
- evm/db/account.py
- evm/db/backends/base.py
- evm/db/batch.py
- evm/db/diff.py
- evm/vm/base.py
- evm/vm/forks/frontier/__init__.py
- evm/vm/state.py
We are storing state roots into the database for every step in the transaction. We only need to store the trie at the end of the block.
Added an extra batch db in AccountDB, so that we can calculate the state root without persisting, and only persist the new state root when absolutely necessary.
Bonus bugfix: `BatchDB` had a bug when it tried to skip deletes.
> Squash all trie changes, persisting minimally

- trinity/main.py
`trinity --light` was failing with roughly "args is not iterable"
Add a comma to make a real tuple when creating the lightnode process.
> light client launch fixup

- p2p/server.py
- trinity/__init__.py
- trinity/__version__.py
- trinity/chains/__init__.py
- trinity/cli_parser.py
- trinity/main.py
- trinity/rpc/ipc.py
- trinity/utils/chains.py
- trinity/utils/logging.py
- trinity/utils/version.py
Fixes #709 
The console output when running the trinity node needed some more information.
- added an ascii header
- added `enode` info for light node
- added path to database IPC socket.
- added network id.
```bash
$ trinity
INFO trinity.db 2018-05-17 12:42:08,787 - database: /Users/piper/.local/share/trinity/mainnet/db.ipc
INFO trinity 2018-05-17 12:42:09,792 -
______     _       _ __
/ / / /  / / / / / / /_/ /_/ /
/_/ /_/  /_/_/ /_/_/\__/\__, /
/____/
INFO trinity 2018-05-17 12:42:09,792 - Trinity/0.2.0a17/darwin/cpython3.6.3
INFO p2p.server.Server 2018-05-17 12:42:09,822 - Running server...
INFO p2p.server.Server 2018-05-17 12:42:14,827 - No UPNP-enabled devices found
INFO p2p.server.Server 2018-05-17 12:42:14,829 - …
```
> Add more info to terminal output for trinity

- trinity/utils/logging.py
Logging output is somewhat hard to read:
```
DEBUG root 2018-05-18 18:29:05,034 - Logging initialized
INFO p2p.server.Server 2018-05-18 18:29:05,067 - Running server...
INFO p2p.server.Server 2018-05-18 18:29:10,073 - No UPNP-enabled devices found
INFO p2p.server.Server 2018-05-18 18:29:10,074 - enode://bdd67f995510d373497248f62f05c5260dc5e5240df95863e3c4963a32090313420ead08c10173bf18039e713cbceaf4c7223a3089a98692fb4814829f169430@0.0.0.0:30303
DEBUG p2p.discovery.DiscoveryProtocol 2018-05-18 18:29:10,122 - boostrapping with [<Node(0x30b7@52.176.7.10)>]
INFO p2p.peer.PeerPool 2018-05-18 18:29:10,125 - Running PeerPool...
DEBUG p2p.peer.PeerPool 2018-05-18 18:29:10,125 - Last node discovery lookup too long ago, triggering another
DEBUG p2p.peer.PeerPool 2018-05-18 18:29:10,128 - Connecting …
```
> Trinity log output: reorder, align

- p2p/chain.py
- p2p/kademlia.py
- p2p/peer.py
- p2p/service.py
When you run trinity, the console output looks like this:
```bash
$ trinity
INFO  05-18 13:43:31       main
______     _       _ __
/ / / /  / / / / / / /_/ /_/ /
/_/ /_/  /_/_/ /_/_/\__/\__, /
/____/
INFO  05-18 13:43:31       main  Trinity/0.2.0a18/darwin/cpython3.6.3
INFO  05-18 13:43:31     server  Running server...
INFO  05-18 13:43:36     server  enode://7b8fb3e32de9aa5d7930fe0dd0e2365361b85c97daa1eb042ac37005f527bb80a450e9ec9012d53d8fcb94d015b115630f4556153fcf4e746993a29b14e13734@0.0.0.0:30303
INFO  05-18 13:43:36     server  network: 1
INFO  05-18 13:43:36       peer  Running PeerPool...
INFO  05-18 13:43:37       sync  Starting fast-sync; current head: #12287
INFO  05-18 13:43:47   kademlia  lookup finished for …
```
> reduce INFO level log output

- docs/guides/evm/building_chains.rst
- docs/quickstart.rst
- p2p/les.py
- p2p/lightchain.py
- tests/p2p/test_lightchain.py
- tests/p2p/test_lightchain_integration.py
- trinity/chains/mainnet.py
- trinity/chains/ropsten.py
- trinity/main.py
`LightChain` no longer tries to meet the BaseChain API. It should be renamed to avoid confusion with other Chains. 
Renamed to `LightPeerChain`. `LightPeerSyncer` seemed reasonable too, but there are other classes called synchronizer, and I didn't want to add any more confusion. Open to other ideas for names.
Generated with:
```sh
find {p2p,trinity,docs,tests} -type f -exec sed -i "s/LightChain/LightPeerChain/g" {} \;
```
Extracted from #717
> Rename LightChain -> LightPeerChain

- evm/chains/base.py
- evm/vm/base.py
- tests/core/conftest.py
- tests/json-fixtures/test_blockchain.py
The `validate_seal` method exists on the `Chain` class, however seal validation can and should be a `VM` level operation.
Issue Reference: https://github.com/ethereum/py-evm/issues/667
Move the `validate_seal` method to the `VM` class. The `VM` class should call out to this within it's `validate_block` method.
> Move the validate_seal method to the VM class.

- p2p/chain.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/sharding.py
- p2p/state.py
The various classes which are `PeerPoolSubscriber` subclasses were not consistently unsubscribing themselves from the peer pool.
Added a new context manager API so that unsubscribe-ing is automatic upon exiting the context.
> Add subscribe context manager API to PeerPoolSubscriber

- trinity/chains/__init__.py
- trinity/main.py
- trinity/utils/chains.py
In the `trinity` module we have a number of path objects that are typed as `str`.
The `pathlib` standard library module has a [PurePath](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath) class which is more appropriate.
Issue Reference: https://github.com/ethereum/py-evm/issues/725, https://github.com/ethereum/py-evm/pull/716#discussion_r189361151
Update the `trinity` module to use the `PurePath` type for all filesystem paths. If it seems appropriate, lets also update the code to actually use and return `PurePath` objects.
> Convert path types to use `PurePath`

- p2p/constants.py
- p2p/discovery.py
- p2p/server.py
- trinity/main.py
- trinity/utils/chains.py
Various places where we are juggling a list of bootnodes.
Moved this into the `ChainConfig` as a property which handles the logic for defaulting based on `network_id`
> Move bootnode config to `ChainConfig` object

- evm/chains/base.py
- evm/db/header.py
- p2p/cancel_token.py
- p2p/exceptions.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/service.py
- tests/p2p/test_cancel_token.py
- tests/p2p/test_lightchain.py
- trinity/chains/light.py
- trinity/chains/mainnet.py
- trinity/chains/ropsten.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/nodes/light.py
- trinity/nodes/mainnet.py
- trinity/nodes/ropsten.py
- trinity/rpc/format.py
- trinity/rpc/ipc.py
Want to use IPC to query the light chain, starting from trinity command line.
Still very much in progress, but this shows the number of the latest downloaded header:
```sh
$ trinity --ropsten --light --data-dir /tmp/trinity-light-ropsten/
... <logs> ...
```
```py
from web3 import Web3
w3t = Web3(Web3.IPCProvider('/tmp/trinity-light-ropsten/jsonrpc.ipc'))
w3t.eth.blockNumber
```
I've been hacking away to get `w3t.eth.getBlock('latest')` working, then I'll pinch this PR off.
Some outstanding questions:
- What is the best way to interface with `LightPeerChain` (formerly `p2p.lightchain.LightChain`) from a synchronous interface. I tried to avoid asyncio spreading virally through the code base. But still getting errors about futures on different threads, etc, and I'm new enough to asyncio that …
> Enable ipc queries to light chain

- p2p/exceptions.py
- p2p/peer.py
- trinity/cli_parser.py
- trinity/main.py
- trinity/utils/chains.py
link: https://github.com/ethereum/py-evm/issues/741
- Running `trinity --light` with a niave peer pool and discovery will rarely find an LES peer to connect to.
- Using `HardCodedNodesPeerPool` eliminates discovery, but also locks Trinity into only being able to connect to a few nodes.
- We will be implementing APIs for Trinity to support reserving slots for certain nodes and trusted nodes.
Implement a new `PeerPool` class which implements list of *preferred* nodes.  
- Anytime the peer pool is looking for a new node to connect to it will try to use one of the preferred nodes.  
- Each preferred node may only be used once every 300 seconds.
- If there are no preferred nodes which have not been used recently then it falls back to use the discovery protocol
> Add PreferredNodePeerPool

- README-trinity.md
- setup_trinity.py
- trinity/__init__.py
Fixes: https://github.com/ethereum/py-evm/issues/728
Trinity and Py-EVM are not the same python package but they live in the same repo.
Added a `setup_trinity.py` file which can be used to release **only** the trinity code (maybe)
> Try separating trinity and evm packages

- tests/trinity/core/chain-management/test_initialize_data_dir.py
- tests/trinity/core/chain-management/test_initialize_database.py
- tests/trinity/core/chain-management/test_is_data_dir_initialized.py
- tests/trinity/core/chain-management/test_is_database_initialized.py
- tests/trinity/core/chains-utils/test_chain_config_object.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/chains/__init__.py
- trinity/config.py
- trinity/main.py
- trinity/utils/chains.py
ChainConfig usage is expanding, and it's getting smarter. It shouldn't live in the sandboxed `utils` package anymore.
- Moved ChainConfig to `trinity/config.py`
- Added a `node_class` implementation to automatically look up the right node class based on the configuration.
> Move ChainConfig to trinity.config, add node_class

- trinity/chains/__init__.py
- trinity/config.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/utils/chains.py
- trinity/utils/xdg.py
Convert `PurePath` to `Path`. Cleaning up consistency of `Path` utilizations.
Issue Reference: https://github.com/ethereum/py-evm/pull/734
> Convert PurePath to Path. Cleaning up consistency of Path utilizations.

- evm/consensus/pow.py
- evm/vm/base.py
- evm/vm/forks/frontier/__init__.py
- tests/core/chain-object/test_mining.py
So, I'm trying to generate a full blockchain DB programatically, from scratch,
by creating arbitrary transactions and then mining the blocks. I intend to use
that to test the chain syncers
However, I first realized we currently cannot do that as BaseVM.mine_block() doesn't
set the block's mix_hash, so I changed it to do that, but now I get a validation
error on the POW difficulty check, and I've no idea why, so it'd be great if you
guys could have a look at this and maybe shed some light.
Also, is the change to BaseVM.finalise_block() something we'd want to merge?
Finally, can you guys think of a better way to programmatically generate a
blockchain DB with a dozen or so blocks? Or is this approach ok?
The failing test: https://circleci.com/gh/ethereum/py-evm/11905?utm_campaign=vcs-integrat …
> Implement a limited version of PoW mining

- p2p/peer.py
This is a bit of a hack, needed because of #768. If we come to the
conclusion we'll never need multiple simultaneous subscribers to a
PeerPool, we can close that issue and redesign PeerPool in a way to make
it clear it can only have one subscriber
> p2p: PeerPool no longer accepts multiple simultaneous subscribers

- p2p/kademlia.py
- p2p/peer.py
- Ensure PeerPool never runs multiple node discovery lookups in parallel
- KademliaProtocol.bond() no longer triggers
self.populate_not_full_buckets() when bondig fails as that can
potentially create a never-ending bonding spiral
The `AlreadyWaiting` errors (#737) seem to be gone with these changes
> p2p: A couple fixes to KademliaProtocol/PeerPool

- p2p/chain.py
- p2p/eth.py
- p2p/lightchain.py
- p2p/service.py
- p2p/state.py
- tests/p2p/integration_test_helpers.py
- tests/p2p/test_sync.py
Up until now we'd only fetch chain/state data, ignoring any peer requests for data
We now handle chain/state data requests from other peers.
Also adds tests for chain syncing and state downloading
> p2p: RegularChainSyncer now serves peer requests as well

- p2p/discovery.py
- p2p/kademlia.py
- tests/p2p/test_kademlia.py
fixes #760 #762 #737
replaces #764 #763 #761
Errors that occur during sync
Add condition checks.
> Handle errors during sync

- evm/constants.py
- p2p/shard_syncer.py
- p2p/sharding.py
- p2p/sharding_peer.py
- p2p/sharding_protocol.py
- tests/p2p/test_sharding.py
The previous version of the minimal^2 sharding protocol only allows for broadcasting collations meaning that syncing an existing chain is not possible
To the existing `Collations` message type (for collation transmission) add types `GetCollations` (for collation requests) and `NewCollationHashes` (for announcement of new collations).
Basic logic of the `ShardSyncer` that handles all these messages:
- whenever it proposes, send `NewCollationHashes` with the proposed collation hash and period
- whenever it receives `NewCollationHashes` reply with `GetCollations` containing the new hashes
- whenever it receives `GetCollations` reply with `Collations` containing the requested collations (provided it knows about them of course)
- whenever it receives `Collations` add the contained collations …
> Sharding protocol with collation requests

- p2p/chain.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/server.py
- p2p/service.py
- p2p/sync.py
- p2p/utils.py
- tests/p2p/test_lightchain.py
- trinity/chains/__init__.py
- trinity/config.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/nodes/mainnet.py
- trinity/nodes/ropsten.py
light and full nodes had some duplicate implementations, and the full node did not support requests over RPC
Not done, but:
- unify the light and full node launch code some more
- launch the RPC server with the full node (reusing the same logic from the base node implementation)
Some open issues:
- shutdown is still ugly on the full node
- had to stop using process pool as the default executor, because I couldn't get it to respect the signal handler (also GvR said it was probably a bad idea)
- Directly initialized the Chain for use with the RPC server. Is that a bad idea? The `ChainProxy` didn't really support anything I needed.
- probably linting and testing, I was only testing at the shell
> json-rpc support for full node

- setup.py
I tried installing `py-evm` on a fresh Ubuntu (with `python3.6-dev` and `python3-pip` installed) and ran into the following error with the `pytest-logging`
```
Collecting pytest-logging>=2015.11.4 (from py-evm==0.2.0a18)
Using cached https://files.pythonhosted.org/packages/dc/1e/fb11174c9eaebcec27d36e9e994b90ffa168bc3226925900b9dbbf16c9da/pytest-logging-2015.11.4.tar.gz
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
File "/tmp/pip-install-p6kq5wup/pytest-logging/setup.py", line 34, in <module>
exec(rfh.read(), None, _LOCALS)  # pylint: disable=exec-used
File "/py-evm/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec …
```
> Remove unmaintained pytest-logging dependency

- p2p/peer.py
- p2p/server.py
Also periodically (every 60s) reports number of connected peers.
> p2p: Track whether a peer connection is inbound or outbound

- evm/db/backends/level.py
- tests/trinity/core/chains-utils/test_chain_config_object.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/chains/__init__.py
- trinity/config.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/utils/chains.py
When trying to run Trinity on a fresh Ubuntu I ran into the following error.
```
INFO  05-28 12:52:55        main  
______     _       _ __       
/ / / /  / / / / / / /_/ /_/ / 
/_/ /_/  /_/_/ /_/_/\__/\__, /  
/____/   
INFO  05-28 12:52:55        main  Trinity/0.2.0a18/linux/cpython3.6.5
INFO  05-28 12:52:55        main  enode://781245c14c5885cf79df99e233733ec7a8fcdf8a9e3bfeef50aedd43b3e42d03@[:]:30303
INFO  05-28 12:52:55        main  network: 1
Process SpawnProcess-2:
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File …
```
> Ensure trinity.nodes is a proper python module

- p2p/chain.py
- p2p/peer.py
- p2p/server.py
- p2p/state.py
- setup.py
Without this the fast sync is insanely slow
Closes #778
> p2p: Explicitly use a ProcessPoolExecutor where needed

- p2p/server.py
- trinity/utils/logging.py
Those loggers are too noisy when in DEBUG level and they end up drowning
the important stuff
> trinity: Force INFO level for Peer/kademlia/discovery loggers

- p2p/auth.py
- p2p/exceptions.py
- p2p/peer.py
Fixes #776 
`ValueError` was escaping during `Peer.connect`
Changed `ValueError` exceptions to be `HandshakeFailure` exceptions which are caught and handled in `Peer.connect`.
> Raise HandshakeFailure instead of ValueError when Ack is wrong size

- p2p/kademlia.py
Occasionally receiving a `ping` from `this_node`.
Avoid trying to add `remote` to routing table if it is `this_node` and return early from `recv_ping` when `remote == this_node`.
> Return early in Kademlia.recv_ping if remote is this_node

- docs/guides/trinity/quickstart.rst
Installation fails on macOS if LevelDB is not installed.
Added a quickstart section for macOS installation.
> Add macOS section to quickstart guide

- evm/tools/fixture_tests.py
Pytest was imported globally in `evm/tools` but we don't want the evm to have a fixed dependency on Pytest.
Moved into function scope
> Don't import pytest globally

- .circleci/config.yml
The order of CI runs always resulted in one long running test case waiting to finish
Re-ordered to hopefully have faster test runs.
> re-order tests for faster runs

- tests/trinity/core/json-rpc/test_ipc.py
- trinity/rpc/modules/web3.py
Missing endpoint for `web3.sha3` call.
Added it.
> Add web3.sha3 endpoint

- docs/contributing.rst
- docs/fragments/virtualenv_explainer.rst
- docs/guides/trinity/quickstart.rst
Someone pointed out that the Quickstart was missing an explanation on `virtualenv`. 
We had that covered in the contributing guide and I decided to compile that into a generic explainer that we can stick into different places.
> Docs: Add generic virtualenv explainer

- p2p/peer.py
#782 
Catch it during the handshake and raise a proper `HandshakeFailure`
> Fixes #782 - uncaught RLP error

- p2p/exceptions.py
- p2p/p2p_proto.py
- p2p/peer.py
- p2p/protocol.py
#775 
Catch the `rlp` error within the `Disconnect` command class and log a warning, then raise a new exception `MalformedMessage` which is caught within `Peer.connect` as one of the *expected* exceptions.
> Handle ListDeserializationError during connection

- tests/trinity/conftest.py
- tests/trinity/utils/test_xdg_paths.py
- trinity/chains/__init__.py
- trinity/exceptions.py
- trinity/main.py
- trinity/utils/chains.py
- trinity/utils/logging.py
- trinity/utils/xdg.py
This fixes #784 where Trinity would not boot correctly if the `$HOME` variable isn't set.
Work through all fallbacks (e.g. `XDG_TRINITY_ROOT`, `TRINITY_DATA_DIR`) until we hit `$HOME` and if `$HOME` is also missing give a clear explanation to the user.
If the user decides to provide the `TRINITY_DATA_DIR` or passes `--data-dir` but that is outside of the `XDG_TRINITY_ROOT` all paths must be pre-initialized as trinity won't attempt to create any directories outside of the `XDG_TRINITY_ROOT`.
> Handle missing $HOME and report better info to user

- p2p/exceptions.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/utils.py
- tests/p2p/test_lightchain_integration.py
This is in preparation for another PR that will redesign the handling of peers in PeerSubscriber instances
Closes: #711
> p2p: Move on-demand retrieval methods from LESPeer to LightPeerChain

- p2p/constants.py
- p2p/peer.py
- p2p/server.py
- trinity/cli_parser.py
- trinity/config.py
- trinity/nodes/full.py
- trinity/utils/chains.py
We accept incoming peer connections but there's no way to limit the number of simultaneous connections.
Issue Reference: https://github.com/ethereum/py-evm/issues/771
Add a CLI flag to specify max number of peers, and have `p2p.Server` reject new connections once we reach that.
> [WIP] Add CLI argument to Trinity to limit number of connected peers

- p2p/peer.py
- p2p/server.py
- tests/p2p/test_server.py
- trinity/nodes/light.py
The `max_peers` limit is not being enforced for inbount peer connections.
Added enforcement to the `Server` class which handles these.
> Enforce max_peers limit on inbound connections

- p2p/peer.py
Yet another code path that didn't respect the max peers.  In the case where max peers is set to 10 and we are currently connected to 9 peers, the code would connect to *up-to* 10 more peers, allowing us to end up with approximately `max_peers * 2 - 1` peer connections.
Early break from the loop in `_connect_to_nodes` when the peer pool is full.
> Early exit when peer pool is full during _connect_to_nodes

- p2p/DEVELOPMENT.md
- p2p/cancel_token.py
- p2p/service.py
- tests/p2p/test_cancel_token.py
Not doing so was a bug that would cause us to leave running token.wait()
tasks behind, and although those are harmless they'd cause asyncio to
emit ERROR logs when shutting down.
Also, this is why we were not using wait_with_token() on non-asyncio
native coroutines (e.g. ChainDB coro_* methods).
> p2p: wait_with_token() now cancels its subtasks when cancelled

- evm/db/chain.py
- p2p/DEVELOPMENT.md
- p2p/cancel_token.py
- p2p/chain.py
- p2p/peer.py
- p2p/service.py
- p2p/sync.py
- tests/p2p/integration_test_helpers.py
- tests/p2p/test_cancel_token.py
- trinity/db/chain.py
This ensures we exit cleanly/immediately when the sync process is
terminated while we're waiting for a chain/DB operation to complete.
Includes #859
> p2p: Use self.wait() for chaindb operations

- p2p/chain.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/server.py
- p2p/sync.py
- p2p/utils.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/main.py
- trinity/utils/ipc.py
Those used to happen when a trinity-proxied Chain/DB service was terminated
before the networking process, but that shouldn't happen anymore.
Also logs more info in trinity when terminating sub-processes
> p2p: No longer catch "unclean" exceptions anywhere

- p2p/chain.py
- p2p/state.py
- p2p/utils.py
Fix #857 
Catch the case if `os.cpu_count()` returns 0. Handle it the same as when it returns `None`. (use a process pool of one)
> Don't crash ProcessPoolExecutor if cpu count is 0

- p2p/server.py
#874 
Caught the exception and logged a user friendly message.
```
$ trinity
INFO  06-06 13:35:01     logging  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs/trinity.log
INFO  06-06 13:35:01        main  Started DB server process (pid=8810)
INFO  06-06 13:35:01        main  Started networking process (pid=8816)
INFO  06-06 13:35:02        main  
______     _       _ __       
/ / / /  / / / / / / /_/ /_/ / 
/_/ /_/  /_/_/ /_/_/\__/\__, /  
/____/   
INFO  06-06 13:35:02        main  Trinity/0.2.0a26/linux/cpython3.6.5
INFO  06-06 13:35:02         ipc  IPC started at: /home/cburgdorf/.local/share/trinity/mainnet/jsonrpc.ipc
INFO  06-06 13:35:02      server  Running server...
INFO  06-06 …
```
> Catch unhandled timeout during UPNP device discovery

- p2p/peer.py
- p2p/server.py
That ensures it gets cancelled when the caller's token is triggered, even
if it is in the middle of an operation that uses the newly created Peer's
cancel token and wouldn't be otherwise cancellable.
Closes: #670
> p2p: Wrap peer.handshake() calls with wait_with_token()

- trinity/chains/__init__.py
- trinity/config.py
- trinity/utils/chains.py
Citing @carver from #894 
On master, if I run `trinity` in a fresh data dir, I get:
```
$ trinity --data-dir /tmp/trinity-ropsten/ --ropsten --light
ERROR  06-11 13:23:38        main  
It appears that /tmp/trinity-ropsten/logs/trinity.log does not exist.
Trinity does not attempt to create directories outside of its root path
Either manually create the path or ensure you are using a data directory
inside the XDG_TRINITY_ROOT path
```
Ok, fair enough, so I create a logs directory and try again
```
$ mkdir -p /tmp/trinity-ropsten/logs
$ trinity --data-dir /tmp/trinity-ropsten/ --ropsten --light
ERROR  06-11 13:23:38        main  
It appears that /tmp/trinity-ropsten/logs/trinity.log does not exist.
Trinity does not attempt to create directories outside of its root path
Either manually create …
```
> Fix wrong handling of logfile path

- p2p/lightchain.py
- p2p/p2p_proto.py
- p2p/peer.py
- p2p/sharding_peer.py
We weren't accurately reporting the disconnect reason to peers.
- Switched `subprotocol_error` from 0xc to 0x10
- Removed old usages of `error` reason
- Used more specific reasons in places that used to have `other`
- Let `TimeoutError` bubble up, and disconnect from peer with timeout reason
> Send disconnect reasons

- evm/chains/base.py
- evm/rlp/blocks.py
- evm/vm/base.py
- p2p/lightchain.py
Fixes #892 
When receiving a genesis header, check if it matches the canonical header already at block number 0. If they are not equal, raise a validation error that will drop the peer.
> validate genesis header in light sync

- p2p/auth.py
p2p/auth.py had diplicate code
abstracted code into function into _pad_eip8_data(data: bytes) -> bytes
I hope this is what was expected, please let me know if i should have done it a different way
> abstracts duplicate code fixes #899

- p2p/kademlia.py
- p2p/peer.py
> 2018-06-13 09:48:22,063 DEBUG: Connecting to <Node(0x2b8d@127.0.0.1)>...
2018-06-13 09:48:22,069 DEBUG: Could not complete handshake with <Node(0x2b8d5ad2d96607d5b9e66ea93bcf26e106f8502d9dab855aaa31d94b8a9f17fec2659dbcfb8b752b641154368f079dcf85e402ea5699cfd205136417a06dc4e2@127.0.0.1:30303)>: UnreachablePeer(ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 30303)"),)
With this we can try and reproduce #901
> p2p: Log more details on peer authentication errors

- p2p/chain.py
In regular-sync mode, there was a bug causing it to keep waiting even
after completing a sync with a given peer, but instead it should return
so that FastChainSyncer can trigger another sync the next time it is
notified about a new block
> p2p: FastChainSyncer._sync() always returns when sync is complete

- trinity/utils/ipc.py
Path handling used old fashioned `os.path.exists(str)` style even though we are dealing with a `pathlib.Path`
This is just a tiny refactoring making use of `Path.exists()` rather than `os.path.exists(str)`. Stumbled over this while working on #927 but I want keep #927 free from any changes that aren't type hints so that its less pain to review.
> Use Path.exists() instead of os.path.exists(str)

- LICENSE
- docs/conf.py
- setup.py
Different parts (license, docs, package info) used different copyright info.
Erased @pipermerriam and @carver from history :sweat_smile: and replaced with "Ethereum Foundation" for the family spirit :family_woman_girl_boy: :family_man_girl_boy:
> Use Ethereum Foundation for copyright info

- setup.py
PyCryptodome is horrifically slow and eth-hash was using it as a backend.
@jmyles laptop was getting too hot for his lap.
Changed the eth-hash backend to use pysha3/hashlib.
@jmyles laptop cooled down.
> Change eth-hash backend to pysha3

- tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
- trinity/rpc/format.py
There were some methods in `trinity.rpc.formatter` that weren't used by trinity at all. They were used in the tests though.
Moved methods to tests as they seem to have no business in trinity.
> Move methods from trinity to tests

- p2p/exceptions.py
- p2p/nat.py
- p2p/server.py
- p2p/service.py
If the first UPnP device you found was not working (say, because it was on a different subnet), then we just gave up.
Fixes #787 
- If setting up NAT on the first device fails, attempt to set up on the others
- Extracted UPnP logic out of p2p.server
Bonus fix:
- bugfix when canceling an already canceled service (now it will only warn instead of raise an exception)
> Support multiple UPnP devices

- p2p/chain.py
- p2p/discovery.py
- p2p/kademlia.py
- p2p/peer.py
- p2p/server.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/integration_test_helpers.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_lightchain_integration.py
- tests/p2p/test_server.py
- trinity/nodes/full.py
- trinity/nodes/light.py
We now have a separate service (DiscoveryService) that performs
discovery, when needed, and adds the peers to its PeerPool
Motivated by the discussion in #886, but also because discovery
shouldn't really be the responsibility of PeerPool
> p2p: Move peer-discovery out of PeerPool

- evm/chains/base.py
- evm/db/account.py
- evm/vm/base.py
- scripts/benchmark/checks/base_benchmark.py
- tox.ini
- trinity/__init__.py
- trinity/chains/__init__.py
- trinity/chains/header.py
- trinity/chains/light.py
- trinity/cli_parser.py
- trinity/config.py
- trinity/db/base.py
- trinity/exceptions.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/rpc/format.py
- trinity/rpc/ipc.py
- trinity/rpc/main.py
- trinity/rpc/modules/eth.py
- trinity/rpc/modules/evm.py
- trinity/rpc/modules/main.py
- trinity/rpc/modules/net.py
- trinity/rpc/modules/web3.py
- trinity/utils/chains.py
- trinity/utils/logging.py
- trinity/utils/mp.py
- trinity/utils/profiling.py
- trinity/utils/version.py
- trinity/utils/xdg.py
- The Trinity code base mixed typed defs with untyped defs and the
- `mypy` didn't protect us from further untyped defs landing in the code base
- `mypy` didn't protect us from implicit `Any` in generics (e.g. `Queue` which implicitly becomes `Queue[Any]`)
- there were lots of places that used `# type: ignore` effectively silencing `mypy`
- added all missing type annotations for Trinity
- enabled  `--disallow-untyped-defs` and `--disallow-untyped-defs` for Trinity to protect the code base from further untyped defs to land
- removed almost all `# type: ignore` comments from Trinity
- There are some places typed as `Any` that could be further improved
- There's one `# type: ignore` because `EmptyService` isn't a proper substitute for `IPCServer` (no common base clase, no matching `run(...)` …
> Add type hints for entire Trinity code base and enable stricter mypy checks

- tests/trinity/conftest.py
- tests/trinity/core/json-rpc/test_ipc.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/rpc/main.py
- trinity/rpc/modules/main.py
- trinity/rpc/modules/net.py
Previously the RPCModules had to deal with either a Server or a LightPeerChain which both just happend to had a `peer_pool` property that the RPCModules could read from.
That alone prevented us from properly typing things out which is why we silenced mypy.
Furthermore, the reason we had it this way was because the `peer_pool` property appeared asynchronously on the server and hence the RPCModules had to check for its existence.
Since we have the PeerPool available synchronously now, we don't need that hack anymore.
Refactored code so that the `RPCModule` deals with `PeerPool` directly
> Pass PeerPool to RPCModules

- p2p/peer.py
- p2p/server.py
As described in #882 there's a `MalformedMessage` error escaping.
Caught and logged exception. I'm not entirely sure if that is the right level to handle this but it's inspired by how we treat the exact same error in [`peer`](https://github.com/ethereum/py-evm/blob/7b660dc30fa6fd62df97e38c5d43dcf29d102437/p2p/peer.py#L679)
> Catch and log exception about malformed msg

- p2p/peer.py
During fast sync, there could escape a `NoConnectedPeers` exception as shown in #933
Removed raising that error in `get_peers()`. It seems wrong to me to have `PeerPool.get_peers()` raise an exception instead of simply returning an empty list.
Notice that by simply removing the exception, the calling code will properly recognize the empty list and throw a `NoEligblePeers` error which is later properly catched and handled as seen here.
https://github.com/ethereum/py-evm/blob/3dfbfa90e97d6066549db20343187e15d3633dd5/p2p/chain.py#L321-L323
On a similar note, I'm not totally sold on `highest_td_peer` property raising that exception either. Returning `None` strikes me as more natural here as well.
https://github.com/ethereum/py-evm/blob/3dfbfa90e97d6066549db20343187e15d3633dd5/p2p/peer.py#L700- …
> Fix escaped NoConnectedPeers error

- p2p/peer.py
- p2p/shard_syncer.py
- p2p/state.py
Three out of five `PeerPoolSubscriber` do not actually need to act upon the registration of other peers (counting the TxPool as well that still sits in a PR).
Instead, the majority of `PeerPoolSubscriber` provides the following implementation for `register_peer`
```python
def register_peer(self, peer: BasePeer) -> None:
pass
```
This strikes me as a hint that `register_peer` isn't a great candidate for being an abstract method on `PeerPoolSubscriber`.
I considered moving it to a whole different abstract class but it strikes me as most natural to keep it on `PeerPoolSubscriber` but just don't dictate to overwrite it.
> Make register_peer of PeerPoolSubscriber non-abstract

- evm/chains/base.py
- evm/chains/header.py
- evm/db/account.py
- evm/db/backends/base.py
- evm/db/chain.py
- evm/db/header.py
- evm/db/schema.py
- evm/rlp/blocks.py
- evm/rlp/transactions.py
- evm/vm/base.py
- evm/vm/computation.py
- evm/vm/logic/call.py
- evm/vm/opcode.py
- evm/vm/state.py
- scripts/benchmark/checks/base_benchmark.py
I noticed we had some places using the following syntax:
```python
class Foo(metaclass=ABCmeta)
```
whereas others used
```python
class Foo(ABC)
```
From StackOverflow (and citing the official documentation)
https://stackoverflow.com/questions/33335005/in-python-3-4-any-difference-between-using-abc-vs-abcmeta
>New class `ABC` has `ABCMeta` as its meta class. Using ABC as a base class has essentially the same effect as specifying  `metaclass=abc.ABCMeta`, **but is simpler to type and easier to read**.
Inherit from `ABC` rather than setting `metaclass=abc.ABCMeta`
> Inherit from ABC rather than setting metaclass

- evm/db/journal.py
- setup.py
- tox.ini
Mypy was on an outdated version.
Updated to `0.610` but disabled the `strict-optional` check for now as our code base does not pass it yet.
- [`reveal_locals()`](https://github.com/python/mypy/pull/3425)
- The type of the object returned by calling an async function used to be Awaitable; it’s changed to Coroutine since such objects support calling send() and throw() on them 
[More in the blog post](http://mypy-lang.blogspot.com/2018/06/mypy-0610-released.html)
> Update mypy to version 0.610

- evm/rlp/accounts.py
- evm/rlp/headers.py
- evm/rlp/logs.py
- evm/rlp/receipts.py
- evm/vm/forks/frontier/blocks.py
- evm/vm/forks/frontier/transactions.py
- evm/vm/forks/homestead/transactions.py
- evm/vm/logic/call.py
- evm/vm/logic/invalid.py
- evm/vm/logic/system.py
- p2p/kademlia.py
- p2p/les.py
- p2p/p2p_proto.py
- trinity/exceptions.py
[In Python 3, a call to `super()` without arguments is equivalent to `super(T, self)`](https://stackoverflow.com/questions/19776056/the-difference-between-super-method-versus-superself-class-self-method/19776143#19776143).
Removed superflous `T, self` from all invocations.
> Get rid of old fashioned super() invocations

- evm/rlp/transactions.py
- p2p/chain.py
- p2p/eth.py
- p2p/rlp.py
- setup.py
- tests/p2p/test_tx_pool.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/tx_pool/pool.py
As specified in #866 we need a minimal viable tx pool that may not work as a proper pool at first but at least relay transactions to peers. This PR serves as a stub to signal that I'm on it.
Implemented minimal viable transaction pool that simply relays transactions among connected peers.
> Minimale Viable Tx Pool

- p2p/chain.py
- p2p/constants.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/server.py
- p2p/sharding_peer.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/dumb_peer.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_auth.py
- tests/p2p/test_server.py
- tests/trinity/conftest.py
- trinity/nodes/light.py
> p2p: Ensure peers are on the same side of chain splits as us

- evm/chains/base.py
- p2p/server.py
- trinity/chains/__init__.py
My previous commit made some p2p code access Chain.vm_configuration, but
the trinity-proxied Chain doesn't expose that. This fixes it by adding a
get_vm_configuration() method to Chain and its trinity-proxied
counterpart
> trinity: Fix fallout from latest changes

- p2p/DEVELOPMENT.md
- p2p/discovery.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/server.py
- p2p/service.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/nodes/light.py
- trinity/tx_pool/pool.py
RopstenLightNode wasn't passing its CancelToken down to its
sub-services, so its _cleanup() method could return while we still had
pending asyncio tasks
Closes: #918
> trinity: Proper cleanup in RopstenLightNode

- setup.py
Lock down web3.py dependency to fix dependency issue with eth-pm. Eth-PM is a dependency of web3.py from 0.4.4 onwards and it's currently demanding for a lower version py-evm version, leaving us with a broken install.
Stick to version 0.4.3 for now
> Lock web3 dependency to 0.4.3

- evm/db/chain.py
- p2p/cancel_token.py
- p2p/chain.py
- p2p/discovery.py
- p2p/ecies.py
- p2p/eth.py
- p2p/exceptions.py
- p2p/kademlia.py
- p2p/les.py
- p2p/lightchain.py
- p2p/nat.py
- p2p/p2p_proto.py
- p2p/peer.py
- p2p/protocol.py
- p2p/sedes.py
- p2p/server.py
- p2p/service.py
- p2p/shard_syncer.py
- p2p/sharding_peer.py
- p2p/state.py
- p2p/sync.py
- p2p/utils.py
- tox.ini
- trinity/tx_pool/pool.py
P2P was missing many type hints and didn't have the `--disallow-untyped-defs` check yet which means that new code could potentially land without type hints (making the fight for 100 % coverage a bit of a fight against windmills)
Added type hints and enabled `--disallow-untyped-defs` check
> Add type hints for p2p package and enable stricter checks

- evm/chains/base.py
- evm/vm/base.py
There's no reason why it should be a VM method in the first place,
and by having it as a standalone function we don't need to attempt to
get a VM for an uncle block (in Chain.validate_uncles()), which is not
supposed to work as that requires having the block's body in our DB and
we never have block bodies for uncle blocks.
Closes: #954
> Turn VM.validate_uncle() into a @classmethod

- docs/guides/evm/understanding_the_mining_process.rst
- evm/chains/base.py
- evm/chains/mainnet/__init__.py
- evm/vm/base.py
- p2p/sync.py
- scripts/benchmark/checks/deploy_erc20.py
- scripts/benchmark/checks/mine_empty_blocks.py
- scripts/benchmark/checks/simple_value_transfers.py
- scripts/benchmark/utils/chain_plumbing.py
- tests/conftest.py
- tests/core/chain-object/test_build_block_incrementally.py
- tests/core/chain-object/test_chain.py
- tests/core/chain-object/test_chain_retrieval_of_vm_class.py
- tests/core/chain-object/test_gas_estimation.py
- tests/core/chain-object/test_mining.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/p2p/integration_test_helpers.py
- trinity/chains/__init__.py
- trinity/rpc/modules/eth.py
Keeping a pending block and header only really matters for mining. Remove that quirky part of state. With header gone, all critical state is held in the chaindb. Chain objects in different processes
will no longer diverge.
Note that although the chain now doesn't maintain a concept of a pending header, the VM must still be initialized on a pending header before importing a block. That's because VMs must not change block number during any operation. (So they have to "start" on the pending block they are about to import, somewhat counter-intuitively.)
If incremental activity like applying transactions are required, then use the new MiningChain class or the new `Chain.build_block_with_transactions()`.
#902 pointed out some challenges from keeping header state in the `Chain` object.
- Pushed …
> Move header state into special MiningChain

- p2p/discovery.py
- trinity/config.py
- trinity/utils/chains.py
The recently introduced PreferredNodeDiscoveryProtocol doesn't look up
the default preferred peers like the old PreferredNodePeerPool did, so
now we do that in ChainConfig when no preferred peers are specified in
the command line
> trinity: Use default preferred peers when none are provided

- evm/rlp/transactions.py
- evm/vm/forks/frontier/state.py
The `transaction.validate()` call in the next
line has exactly the same logic making this a
superfluous extra check.
https://github.com/ethereum/py-evm/blob/042cd4bc215d8567d560f43564dbee2aba5c970d/evm/rlp/transactions.py#L106-L113
Removed superfluous check
> Remove superfluous tx gas validation

- p2p/chain.py
- p2p/constants.py
When starting a sync with a peer, ChainSyncer used to always fetch the 192
headers prior to the current local head and reprocess them, which is very
wasteful specially when we're already fully synced. Now it only fetches
MAX_REORG_DEPTH previous headers and skips processing the ones we already
have.
Depends on #966
Closes: #967
> Improve logic to find common ancestor when starting sync

- evm/db/account.py
- evm/db/chain.py
- evm/vm/computation.py
- evm/vm/forks/frontier/computation.py
- evm/vm/forks/frontier/state.py
- evm/vm/forks/homestead/computation.py
- evm/vm/forks/spurious_dragon/computation.py
- evm/vm/forks/spurious_dragon/state.py
- evm/vm/logic/call.py
- evm/vm/logic/system.py
- p2p/__init__.py
- p2p/chain.py
- p2p/discovery.py
- p2p/peer.py
- p2p/server.py
- p2p/service.py
- p2p/shard_syncer.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/integration_test_helpers.py
- trinity/db/chain.py
- trinity/tx_pool/pool.py
- trinity/utils/logging.py
- When handling body/receipts requests for blocks we don't know, we'd
fail with an undhandled HeaderNotFound
- Handling of trie Node requests didn't work on trinity because it
used a ChainDB method that was not exposed in trinity's ChainDBProxy
It had been accidentally removed.
Peer was logging (with DEBUG level) all received/sent msgs, making it so
noisy that we had to forcibly set its level to INFO on trinity. This
changes it to log those on a different level that is currently never shown
when running trinity
Similaryly, change all debug() logs in evm/vm to use the new level as those
make trinity's log pretty much useless when syncing in regular
(block processing) mode
> A few small fixes

- tests/trinity/core/cli/test_trinity_repl.py
- trinity/console.py
- trinity/main.py
- trinity/utils/log_messages.py
The `trinity attach` command currently doesn't recognize when it fails to attach to a running `trinity` instance leaving users with unhandled exceptions upon `w3` usage.
Issue Reference: https://github.com/ethereum/py-evm/issues/959
Throw `FileNotFoundError` if the `ipc_file` not found when executing `trinity attach` command
> Log an informative error message when IPC file is not found

- evm/chains/base.py
- tests/p2p/test_tx_pool.py
- trinity/chains/__init__.py
- trinity/nodes/base.py
- trinity/nodes/mainnet.py
- trinity/nodes/ropsten.py
- trinity/tx_pool/pool.py
- trinity/tx_pool/validators.py
Currently the transaction pool relays transactions even if they are invalid making that an attack vector (see #945) 
- added a `validate_signed_transaction` API to the Chain
- make the `TxPool` take a `Callable[[BaseTransactionFields], None]` in its constructor as a validation method
- make the `TxPool` validate txs against the passed validation function
> Ensure Transaction Pool does not relay invalid transactions

- setup.py
- trinity/tx_pool/validators.py
https://github.com/ethereum/py-evm/blob/46f956ea048eafed6606f59a465af375f1be7a9a/trinity/tx_pool/validators.py#L47-L56
get called quite often and impact `ChainProxy`
Add time to live caching through @cachetools.func.ttl_cache decorator.
Closes #992
> add ttl to validators.py

- setup.py
This is a follow up to the [discussion about the version scheme used in setup.py](https://github.com/ethereum/py-evm/pull/997#discussion_r200872726). I brought in some inconsistency which this PR fixes.
Used range based version selection only bound by the major version.
> Use consistent version range scheme in setup.py

- p2p/chain.py
- tests/p2p/integration_test_helpers.py
- trinity/db/chain.py
That ensures we add lookup entries from TX hash to block/idx.
Closes: #529
> Use persist_block() instead of persist_header() in FastChainSyncer

- p2p/cancel_token.py
- p2p/chain.py
- p2p/service.py
- p2p/state.py
- p2p/sync.py
- tests/p2p/test_sync.py
I noticed a low peer count during a state sync (which makes it quite slow) and it turns out that's because peers attempt to fetch data from us and disconnect as we fail to reply. This should ensure we keep a high peer count, speeding up the state sync significantly
Depends on #980
> StateDownloader now handles data requests from peers

- p2p/chain.py
- p2p/peer.py
- p2p/sharding_peer.py
- p2p/state.py
- trinity/plugins/builtin/tx_pool/pool.py
It used to handle only GetBlockHeader requests, and now handles the rest as well
Includes commits from other PRs, so please review just https://github.com/ethereum/py-evm/pull/993/commits/f80d8ba0708137fee153b860f2b94fb75b17b267
> FastChainSyncer now handles data requests from peers

- evm/chains/base.py
- trinity/chains/light.py
- trinity/plugins/builtin/tx_pool/plugin.py
- trinity/plugins/builtin/tx_pool/validators.py
#998 introduced inheritance of `LightDispatchChain` -> `Chain`. For many methods, the `Chain` implementations will are broken if run in a `LightDispatchChain`. They expect a `chaindb`, but the dispatch chain only has a `headerdb`. It seems safer, easier to reason about, and quicker to isolate problems, if we only inherit `BaseChain`.
- Move some key methods that don't depend on `chaindb` from `Chain` to `BaseChain`.
- Require header as part of `get_vm_class()` so that it can be implemented in `BaseChain`
> Inherit BaseChain from LightDispatchChain

- evm/utils/logging.py
- trinity/chains/__init__.py
> trinity: Proxied services now record remote exceptions' tracebacks 

- eth/chains/base.py
- eth/chains/mainnet/__init__.py
- eth/vm/base.py
- p2p/chain.py
- p2p/constants.py
- p2p/peer.py
- setup.py
- tests/core/vm/test_mainnet_dao_fork.py
- trinity/chains/light.py
For every header batch, pick a random subset and check the seal only on those.
Before this change: ```Imported 192 headers in 1.33 seconds, new head: #3583663```
After this change: ```Imported 192 headers in 0.53 seconds, new head: #3585558```
Closes: #932
> During fast/light sync, check seal on a small subset of headers

- p2p/exceptions.py
- trinity/cli_parser.py
- trinity/main.py
- trinity/utils/logging.py
logs to stdout are annoying, especially when invoking `trinity console`
- move logs to stderr
- add warning and error options to cli logging parser
- bonus syntax fix in upnp exception
> Logs to stderr

- p2p/service.py
classes should rarely have mutable data structures set at the class level
moving the instantiation to the init constructor
> fixes issue #1012

- p2p/constants.py
- p2p/discovery.py
- p2p/kademlia.py
Parity 1.10 (and earlier) nodes send the wrong token on pong messages
(https://github.com/paritytech/parity/issues/8038). This change keeps
a mapping of wrong tokens to the ones we expect, and uses that whenever
we get a pong with one of those wrong tokens.
> p2p/discovery: Workaround a parity bug that causes pongs with wrong token

- eth/precompiles/modexp.py
- p2p/chain.py
- p2p/constants.py
- p2p/peer.py
- p2p/utils.py
- tests/p2p/test_utils.py
Related to #868 -- slow peers can dramatically slow down syncing
- track throughput performance of peers
- favor high-throughput peers, sending them bigger requests
- if performance of a peer is bad enough, we will eventually not request anything from them (this happens naturally in the current approach, because the proportional number of block parts requested is `floor`ed and so you can end up with 0 parts requested if a peer is slow enough)
As mentioned in #868 a better solution is eventually to stream all block part requests, rather than batching them into header chunks of 192. This is a performance patch on the way there, although significant parts of PR would be obsoleted by such a solution. It would take a while to get that solution right, and probably belongs in the next release …
> Track peer performance, favor fast peers

- trinity/cli_parser.py
- trinity/config.py
- trinity/main.py
- trinity/utils/filesystem.py
- trinity/utils/ipc.py
Fixes #831 
All the apparent reasons for a failed restart involve a process that's hanging around.
- Track running process ids in pid files
- Add a `fix-unclean-shutdown` subcommand that gracefully closes any processes that are still running
> Fix unclean shutdown

- docs/api/eth/db/api.db.chain.rst
The `AsyncChainDB` was recently moved into Trinity but wasn't removed from the documentation, leaving us with broken docs.
```
WARNING: autodoc: failed to import class 'AsyncChainDB' from module 'eth.db.chain'; the following exception was raised:
File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/sphinx/util/inspect.py", line 204, in safe_getattr
return getattr(obj, name, *defargs)
AttributeError: module 'eth.db.chain' has no attribute 'AsyncChainDB'
During handling of the above exception, another exception occurred:
File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
obj = attrgetter(obj, attrname) …
```
> Remove AsyncChainDB from evm api docs

- p2p/peer.py
- p2p/shard_syncer.py
- p2p/state.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_lightchain_integration.py
- tests/p2p/test_peer.py
- tests/p2p/test_sharding.py
- tox.ini
- trinity/plugins/builtin/tx_pool/pool.py
This way callsites are less likely to get a list of peers and hold them while making blocking calls, as these peers may disconnect in the meantime.
Closes: #1016
> PeerPool is now an asynchronous iterable

- trinity/plugins/builtin/tx_pool/plugin.py
The transaction pool has had some unexpected side effects which are effecting connectivity to peers as well as syncing.
Change the transaction pool to be opt-in, and have it be disabled by default.
> Make the transaction pool disabled by default

- p2p/peer.py
- p2p/server.py
- trinity/plugins/builtin/tx_pool/pool.py
- The tx pool loop was *probably* causing us to occasionally time out during sync
- The tx pool loop was trying to send to peers which had already disconnected causing lots of console warnings
- made the loop yield for each iteration
- changed how peers are iterated over to account for in-flight disconnections.
- fixed some places where `peer.disconnect` was not being *awaited*
TODO
> Fix transaction pool send loop logic

- p2p/utils.py
```
veselin@p2p-id:~$ venv/bin/trinity 
INFO  07-18 12:29:26        main  
______     _       _ __       
/ / / /  / / / / / / /_/ /_/ / 
/_/ /_/  /_/_/ /_/_/\__/\__, /  
/____/   
INFO  07-18 12:29:26        main  Trinity/0.2.0a26/linux/cpython3.6.6
INFO  07-18 12:29:26        main  Trinity DEBUG log file is created at /home/veselin/.local/share/trinity/mainnet/logs/trinity.log
INFO  07-18 12:29:26        main  Started DB server process (pid=860)
INFO  07-18 12:29:27        main  Started networking process (pid=862)
INFO  07-18 12:29:29      server  Running server...
INFO  07-18 12:29:29         nat  Setting up NAT portmap...
INFO  07-18 12:29:29         ipc  IPC started at: …
```
> bug fix: cpu_count should always be above 0

- p2p/chain.py
- p2p/eth.py
- p2p/exceptions.py
- p2p/les.py
- p2p/peer.py
- p2p/protocol.py
- p2p/server.py
- p2p/service.py
- tests/p2p/dumb_peer.py
Also, instead of ignoring non-BlockHeaders messages received while the DAO
fork check is pending, we store them and re-add to subscribers' msg queues
when the fork check is successful and the peer is actually added to the
pool
Closes: #1025
> p2p: Perform DAO fork check only when peer is added to PeerPool

- p2p/service.py
- tests/trinity/conftest.py
- tests/trinity/core/json-rpc/test_ipc.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/rpc/ipc.py
Fixes #689
Also, the ipc socket file is left dangling when the service is cleaned up.
- convert to BaseService
- can set custom asyncio loop on BaseService
- cancel a service running on a different thread
- remove ipc socket file on server shutdown
- some helpful contextual info: show the target data folder that fix-unclean-shutdown is using to fix (I was trying to clean a bad `trinity --ropsten` with a `trinity fix-unclean-shutdown`. I needed `trinity --ropsten fix-unclean-shutdown` but that wasn't obvious without a little extra logging)
> Convert IPCServer to a BaseService

- trinity/main.py
`trinity fix-unclean-shutdown` was not cleaning up the JSON-RPC ipc socket file.
Added logic to clean it up.
> Also cleanup the JSON-RPC ipc socket in fix-unclean-shutdown

- p2p/chain.py
- p2p/lightchain.py
- p2p/peer.py
- p2p/shard_syncer.py
- p2p/state.py
- tests/p2p/peer_helpers.py
- tests/p2p/test_sharding.py
- tests/p2p/test_tx_pool.py
- trinity/plugins/builtin/tx_pool/pool.py
* Renamed to PeerSubscriber because that's what it really is
* New @abstractmethod max_queue_size, to force each subscriber to define their own
* Peer now keeps a list of actual PeerSubscribers instead of just their msg queues
* PeerSubscriber provides APIs to add msgs to queue and check queue
size, abstracting underlying implementation
* If an attempt is made to add a msg but the queue is full, we log a
warning and drop the msg (Closes: #1032)
This should also help debug #1052 and decide how to fix it
> p2p: Some improvements to PeerPoolSubscriber

- p2p/chain.py
- p2p/state.py
- p2p/sync.py
- p2p/utils.py
Also, when profiling, do not run anything in an asyncio executor as
those would not be profiled if we did.
> Make it easy to profile the ChainSyncer

- .circleci/config.yml
- tests/trinity/conftest.py
- tests/trinity/integration/test_boot.py
- tox.ini
- trinity/tools/async_process_runner.py
- trinity/utils/async_iter.py
We currently do not have any integration tests for Trinity, that really test it on the command line level. That is, run Trinity the same way as a user would run it and check whether it behaves the way we assume it should behave.
This has biten us over and over as it is **very hard** to guarantee to ship software that works™ when one has to rely on manual human testing for these things.
This adds some new testing facilities to run Trinity, the same way a user would do, and then do certain assertions about the things it responds.
In particular we test that,
- Trinity logs out sequence of expected messages
- Trinity does not log out `Traceback (most recent call last)` in the first 20 seconds of booting
These assertions are provided for the following invocations
```
trinity,
trinity --light …
```
> Add integration tests for Trinity

- trinity/__init__.py
When `trinity` is not installed we fall back to the `py-evm` version for the version number.  We don't want to have any confusion when viewing this number
When this happens, prefix the version string with `eth-`
> Prefix trinity version with eth if trinity not installed

- trinity/utils/logging.py
During state sync the logs were innundated with logging statements for every single trie node being scheduled for retrieval.
Reduce logging level to `INFO` for that logger.
> quiet logging of StateSyncer during state sync

- tests/trinity/integration/test_boot.py
- trinity/tools/async_process_runner.py
As @pipermerriam pointed out `Iterable[str]` is satisfied by any `str` itself but will be an Iterable of any single char of that string which isn't quite what our API expects.
Turn it into `Tuple[str, ...]`
> Use Tuple[str, ...] instead of Iterable[str] in AsyncProcessRunner

- docs/guides/eth/understanding_the_mining_process.rst
Stumbled over this broken link in the docs. Did a quick search and it seems to be the last broken link between guides.
Converted to proper syntax.
> Fix broken link in docs

- setup.py
Before this change, web3 specified a tighter <0.3.0 constraint, so it
caused a pip conflict when trinity installed 0.3.0.
> let web3.py specify the eth-account dependency

- .circleci/config.yml
- Makefile
- docs/conf.py
- docs/guides/eth/building_chains.rst
- tox.ini
1. We have no job that checks if the docs can still be built (e.g. source files get moved/deleted but docs aren't updated will cause failure)
2. The examples in our docs aren't validated which means they can get out of date quickly
1. This configures `doctest` to validate examples (only one example so far)
2. This adds a `py36-docs` job to our CI which validates that docs can be built and also validates the examples using `doctest`.
3. The `building chains` example was updated to be validated with `doctest`. Notice that only the first part of the example uses doctest yet. The second one needs to be updated and moved but I'll tackle that in a separate PR.
> Add CI check to ensure docs are valid and use doctest to validate examples

- p2p/chain.py
- p2p/discovery.py
- p2p/exceptions.py
- p2p/nat.py
- p2p/peer.py
- p2p/server.py
- p2p/service.py
- p2p/state.py
- tests/p2p/integration_test_helpers.py
- trinity/rpc/ipc.py
We were still using the `OperationCancelled` exception from the local `p2p` library and so `OperationCancelled` requests were not being correctly handled
Switched to use new one from the new cancel token library
> Switch to cancel-token library exception class

- setup.py
- tests/p2p/conftest.py
Some of our `p2p` tests use real networking.
Change to use the new library `pytest-asyncio-network-simulator` which mocks out the networking.
> Use new network simulator library in tests

- p2p/chain.py
- p2p/exceptions.py
- p2p/kademlia.py
- p2p/peer.py
- p2p/service.py
- p2p/state.py
- tests/p2p/test_state_sync.py
Keep track of which nodes we requested to every peer so that we know which
ones they're missing when they reply with just a subset of what was
requested. That way we can avoid re-requesting those missing nodes to peers
that don't have them. #1073
Also, when a reply from a peer contains only a subset of what was
requested, we immediately re-request the missing ones. Closes: #1077
And a quick workaround to avoid losing peers during state sync (#1074)
> state-sync: don't request trie nodes to peers known not to have them

- p2p/state.py
Reduces the size of the messages being logged during state sync.  My original approach of using fixed widths resulted in weird formatting as state sync starts.  As it turns out, the size of these numbers doesn't vary much between messages so allowing the width to organically grow with the width of the numbers seems aceptable.
> Reduce size of state sync status message

- trinity/utils/logging.py
fixes https://github.com/ethereum/py-evm/issues/1085
Reduce the logging level for the `trie` namespaced logger to `ERROR`
> Quiet down the missing SyncRequest messages

- p2p/state.py
State syn clogging output was still confusing to read.
Replaced separators between labels and values from `: ` to `=` (the same as geth does)
> cleanup state sync logging round 2

- eth/vm/forks/__init__.py
- eth/vm/forks/constantinople/__init__.py
- eth/vm/forks/constantinople/blocks.py
- eth/vm/forks/constantinople/computation.py
- eth/vm/forks/constantinople/opcodes.py
- eth/vm/forks/constantinople/state.py
- eth/vm/forks/constantinople/transactions.py
As stated in #1107 we don't have the base structure for the Constantinople fork yet.
Adds all the base structure to support the Constantinople fork. Notice that this doesn't yet add the `ConstantinopleVM` to any chain though.
> Prepare base ConstantinopleVM structure

- p2p/chain.py
- p2p/eth.py
- p2p/exceptions.py
- p2p/les.py
- p2p/peer.py
- p2p/protocol.py
- p2p/state.py
- tests/p2p/test_header_request_object.py
- tests/p2p/test_peer_block_header_request_and_response_api.py
- trinity/utils/headers.py
Still too much manual work to be done for round trip requests for block headers.
- established base class for p2p requests for data in `p2p.peer.BaseRequest`
- setup data structure on `ETHPeer` which houses a mapping between `Command -> Future`.
- In the `handle_sub_process_msg`, if there is a waiting future for a given command, it will set the future result.
- New API `ETHPeer.get_block_headers` which does the full request/response round trip.
This has a really nice side effect of not needing the chain syncers to handle the `BlockHeaders` response, and instead can just `await peer.get_block_headers(...)`, removing a decent amount of complexity from the class.  If we continue this pattern for the rest of the block body parts I think the chain syncer is going to look a lot cleaner and …
> Further flesh out round trip request/response API

- .circleci/config.yml
- setup.py
- tox.ini
Nothing; Python 3.7 is out, and it would be nice to start testing for compatibility.
~~Implements~~ Closes #970.
The most basic set of tests, `core`, is now also run with a `circleci/python:3.7` image.
The image lacks some dependencies to build wheels locally (`gmp`, `leveldb`, likely others); so some packages are bumped to versions where wheels have Python 3.7 support. These are:
* `plyvel` - https://plyvel.readthedocs.io/en/latest/news.html#plyvel-1-0-5
* `coincurve` - https://pypi.org/project/coincurve/#id4
Source: [friendlyferret](https://www.friendlyferret.com/how-many-types-of-ferrets-are-there/)
> Test core with py3.7

- trinity/utils/logging.py
One of the logging statements during state sync drowns out all of the other messages.
Adjust the logging level for that logger to only report `ERROR` level logs.
> quiet logging of No SyncRequest found messages durign state sync

- p2p/peer.py
- tests/p2p/test_peer_subscriber.py
- tests/trinity/core/peer_helpers.py
- trinity/plugins/builtin/tx_pool/pool.py
- trinity/sync/full/chain.py
- trinity/sync/full/state.py
- trinity/sync/light/chain.py
- trinity/sync/light/service.py
- trinity/sync/sharding/service.py
fixes #1055
All `PeerSubscriber` classes must now implement a `subscription_msg_types` which defines which types of messages it will add to it's queue.  Any message not the specified types is discarded.  Including the base `p2p.protocol.Command` in the list results in all messages being included in the queue.
> PeerSubscribers now specify what messages they are interested in

- trinity/sync/full/state.py
I have found it helpful to be able to see how many nodes in the affected logging statements.
Added a count to them.
> Log number of trie nodes in StateSyncer debug logging

- .circleci/config.yml
- tox.ini
PR #1109 enabled testing with Python 3.7 for the `core` tests only. This is useful to show support by dependencies, but not much else.
This PR enables `trinity{,-integration}` tests. As discussed in #1129, the rest aren't very useful (yet), and would prolong CI runs (by about 50%).
Closes #1129 as superceded. (This is a squashed/rebased version.)
(Some [discussion below](https://github.com/ethereum/py-evm/pull/1135#discussion_r207134409) that urged me to add this, so the fact doesn't slip through.)
See [relevant `tox` doc section](https://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings).
**TL;DR:** a "factor" is a segment of a `testenv`'s name. E.g., `testenv:py37-trinity-integration` has 3 factors: `py37`, `trinity`, and `integration`. A factor can be …
> Run trinity integration tests with py3.7

- tests/trinity/core/integration_test_helpers.py
- tests/trinity/core/p2p-proto/test_state_sync.py
- tests/trinity/core/p2p-proto/test_sync.py
- trinity/db/base.py
- trinity/exceptions.py
- trinity/server.py
- trinity/sync/full/hexary_trie.py
- trinity/sync/full/service.py
- trinity/sync/full/state.py
- trinity/sync/full/trie.py
> Move HexaryTrieSync from py-trie here, and make it async

- trinity/sync/full/state.py
Fixes #1133 
Reduced the logging level to `TRACE`.  After running stat sync continuously for days now, these messages provide no useful information in the debug logs and merely serve as noise.
> Reduce logging about no idle peers

- p2p/peer.py
`Peer.read_msg` can throw a decryption error.
```
File "/home/piper/projects/py-evm/p2p/service.py", line 76, in run
await self._run()
File "/home/piper/projects/py-evm/p2p/peer.py", line 334, in _run
cmd, msg = await self.read_msg()
File "/home/piper/projects/py-evm/p2p/peer.py", line 348, in read_msg
header = self.decrypt_header(header_data)
File "/home/piper/projects/py-evm/p2p/peer.py", line 460, in decrypt_header
expected_header_mac, header_mac))
```
Handle it in the main `_run` loop.
> Handle decryption error

- tests/conftest.py
- tests/json-fixtures/test_state.py
- tests/p2p/test_peer_collect_sub_proto_msgs.py
- tests/p2p/test_peer_subscriber.py
- tests/trinity/core/p2p-proto/test_node_data_request_object.py
- tests/trinity/core/p2p-proto/test_peer_node_data_request_and_response_api.py
- tests/trinity/core/p2p-proto/test_server.py
- trinity/p2p/handlers.py
- trinity/protocol/common/managers.py
- trinity/protocol/common/requests.py
- trinity/protocol/eth/handlers.py
- trinity/protocol/eth/managers.py
- trinity/protocol/eth/proto.py
- trinity/protocol/eth/requests.py
- trinity/protocol/les/managers.py
- trinity/protocol/les/requests.py
- trinity/sync/full/state.py
The `GetnodeData` and `NodeData` commands can be done as a singe awaitable round trip call using the new round trip peer request API
Setup a new request manager for `NodeData` requests/response and integrated it into the `StateSyncer`
> Expand round trip to GetNodeData and NodeData commands

- trinity/sync/full/state.py
- trinity/utils/cancellation.py
Fixes #1162 
Created a new decorator `trinity.utils.cancellation.async_handle_cancellation` which can be used to handle the `OperationCancelled` exception for a full function.
> Handle OperationCancelled in state downloader background task

- eth/db/trie.py
- p2p/peer.py
- tests/trinity/core/p2p-proto/test_block_bodies_request_object.py
- tests/trinity/core/p2p-proto/test_node_data_request_object.py
- tests/trinity/core/p2p-proto/test_peer_block_body_request_and_response_api.py
- tests/trinity/core/p2p-proto/test_peer_block_header_request_and_response_api.py
- tests/trinity/core/p2p-proto/test_peer_receipts_request_and_response_api.py
- tests/trinity/core/p2p-proto/test_receipts_request_object.py
- trinity/p2p/handlers.py
- trinity/protocol/common/managers.py
- trinity/protocol/common/requests.py
- trinity/protocol/eth/handlers.py
- trinity/protocol/eth/managers.py
- trinity/protocol/eth/proto.py
- trinity/protocol/eth/requests.py
- trinity/protocol/les/managers.py
- trinity/protocol/les/proto.py
- trinity/protocol/les/requests.py
- trinity/sync/full/chain.py
Builds on https://github.com/ethereum/py-evm/pull/1159
Fixes https://github.com/ethereum/py-evm/issues/1131
This finishes expanding the round trip API for the `eth` protocol to all of Headers, NodeData, Receipts, and BlockBodies request/response pairs.  The `FastChainSyncer` and `RegularChainSyncer` classes have been reworked to use this API.
> Expand round trip api to block bodies

- p2p/service.py
The logging message the the `BaseService` emits on cancellation is now too noisy with the increased number of services being run.
Reduced the logging level to `DEBUG`
> Reduce logging level of BaseService cancellation message

- eth/chains/base.py
- eth/utils/spoof.py
- eth/vm/computation.py
- eth/vm/forks/frontier/state.py
- eth/vm/state.py
- setup.py
- tests/conftest.py
- tests/core/chain-object/test_contract_call.py
- tests/trinity/core/json-rpc/test_ipc.py
- tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
- trinity/chains/light.py
- trinity/rpc/modules/eth.py
- trinity/utils/validation.py
Need an eth_call endpoint, according to #1061 
Add a new `Chain.get_transaction_result()` method. Test that method and the identity precompile.
TODO:
- test calling a contract with a few error conditions:
- We could try to monkey-patch validation
- If we force the gas price to 0, it could affect execution
- If we add balance to the sending account, it could affect execution
- We could force the gas to 0, then inspect the trace for any `GASPRICE` opcodes, and bail if found
- We could add to the user balance, then inspect the trace for any `BALANCE` opcodes, and bail if found
- we could try each of the previous two in succession, then bail if BOTH fail.
~~I'll probably bail on this last todo and put it in an issue to handle later.~~
> [WIP] add chain.get_transaction_result and rpc eth_call

- p2p/peer.py
Turns out we only handled `MalformedMessage` during DAO fork checks.  If a peer sends a malformed message outside of this context, it isn't caught.
Moved the handling of `MalformedMessage` directly into the `Peer._run` loop.
> Move handling of MalformedMessage to the main Peer._run

- trinity/sync/full/state.py
Something is wrong with the peer request tracking in the state sync which causes us to request nodes from a peer which is still waiting for a response, and thus an `AlreadyWaiting` exception is escaping.
Catch the exception and log a warning so we don't forget about it.
> FYI, this section of functionality is up for being refactored very soon so this is only intended to be a stop-gap fix.
> Handle AlreadyWaiting exception in state sync

- trinity/main.py
- trinity/plugins/builtin/fix_unclean_shutdown/plugin.py
- trinity/plugins/registry.py
As stated in #1069, the `fix-unclean-shutdown` command doesn't need to live in the core trinity code and is better suited to live in the plugin space.
Moved it into a plugin.
> Convert "fix-unclean-shutdown" to plugin

- tests/trinity/core/chain-management/test_initialize_data_dir.py
- tests/trinity/core/chain-management/test_initialize_database.py
- tests/trinity/core/chain-management/test_is_data_dir_initialized.py
- tests/trinity/core/chain-management/test_is_database_initialized.py
- tests/trinity/core/chains-utils/test_chain_config_object.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/config.py
- trinity/nodes/base.py
- trinity/nodes/light.py
- trinity/protocol/les/proto.py
- trinity/server.py
- trinity/utils/chains.py
This avoids duplicating some logic to run a PeerPool/DiscoveryService,
but also causes LightNode to setup NAT port forwarding and accept
incoming peer connections.
Also changed the default peer limit when running in light mode to half
of the limit used when in full mode.
Closes: #1003
> Use trinity.Server in LightNode

- p2p/discovery.py
- p2p/nat.py
- p2p/peer.py
- trinity/plugins/builtin/tx_pool/pool.py
- trinity/protocol/common/managers.py
- trinity/sync/common/chain.py
- trinity/sync/full/service.py
- trinity/sync/light/service.py
- trinity/sync/sharding/service.py
The previous fix for this in #1177 did not take the async nature into account when detecting whether cancellation has been requested.
Added a `self.sleep(0)` before the `self.is_running` check.
> Fix full sync service cancellation detection

- tests/trinity/core/p2p-proto/test_server.py
> Properly test the auth/p2p handshake on incoming peer connections

- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/main.py
- trinity/utils/ipc.py
On slow systems, it may take a while before the IPC socket file is created.
We wait for this file for 1 second only; and, whether it's present or not, continue in the same manner.
The networking process wants this file to be present, fails if it's not, and effectively "hangs" the node.
The timeout was increased, from 1 second to 10.
If the timeout is reached, an exception is raised, an attempt is made to shut down the DB process, and an exit with error code 1 (generic) is performed.
Closes #1168 - should perhaps open a more specific issue, taking the notes there into account?..
Two processes, one is "too fast"...
Source: not sure; found [on pinterest](https://www.pinterest.com/pin/162903711496032131/).
> Workaround: wait longer for IPC socket file to appear

- setup.py
- tox.ini
Installing `py-evm` installed `p2p` and `trinity`
modified `install_requires` to only include `eth` dependencies. 
https://github.com/ethereum/py-evm/pull/1188#issuecomment-413697522
> removed p2p and trinity dependencies from py-evm(eth)

- p2p/protocol.py
- tests/trinity/core/p2p-proto/test_stats.py
- trinity/protocol/common/exchanges.py
- trinity/protocol/common/handlers.py
- trinity/protocol/common/managers.py
- trinity/protocol/eth/exchanges.py
- trinity/protocol/eth/peer.py
- trinity/protocol/les/exchanges.py
- trinity/protocol/les/peer.py
- trinity/utils/decorators.py
Trying to call `get_stats()` on the exchange handler was crashing. Broken during #1184 
Keep a link to all the exchange managers, and use them to call get stats.
> ExchangeHandler stats fix

- p2p/DEVELOPMENT.md
- p2p/discovery.py
- p2p/nat.py
- p2p/peer.py
- p2p/service.py
- tests/p2p/test_service.py
- tests/trinity/core/integration_test_helpers.py
- trinity/plugins/builtin/tx_pool/pool.py
- trinity/protocol/common/exchanges.py
- trinity/protocol/common/managers.py
- trinity/sync/common/chain.py
- trinity/sync/full/state.py
- trinity/sync/light/service.py
- trinity/sync/sharding/service.py
There was a sprinkling of `while service.is_running:` and `while not service.cancel_token.triggered:` throughout the code base. Almost all of the `is_running` calls were evil: they continue silently running something even after the cancel token was triggered.
Added `is_operational`, which is true after the server pre-start steps are complete and until cancel has been triggered.
Now all the while loops are non-negative, and independent of the cancel implementation.
> Add BaseService.is_operational

- eth/chains/base.py
- p2p/nat.py
- p2p/service.py
- setup.py
- tests/p2p/test_service.py
- tests/trinity/utils/test_task_queue.py
- trinity/chains/light.py
- trinity/protocol/common/managers.py
- trinity/protocol/eth/peer.py
- trinity/protocol/les/peer.py
- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
- trinity/sync/light/chain.py
- trinity/utils/datastructures.py
Step 1 of #868 -- queue headers instead of batching them
Fixes #1215 
Main changes:
- Queue up headers for processing in later stages (instead of waiting for all post-processing to finish before requesting the next batch of headers)
Follow up work:
- Decouple the header sync from the post-processing stages. It doesn't really need to be a subclass I think
- Do the same queue processing for later steps, like downloading block bodies.
- Track one queue per peer, so that a peer is never waiting on another peer to do its own request.
> Sync headers in queue instead of batch, add Peer types

- eth/vm/logic/arithmetic.py
- tests/core/opcodes/test_opcodes.py
0^0 == 1, but this wasn't tested for.
Caught by [`exp8.json` test](https://github.com/ethereum/tests/blob/10ab37c095bb87d2e781bcf112b6104912fccb44/VMTests/vmArithmeticTest/exp8.json) (not yet tracked in tests fixture on `master`).
Semi-accidentally caught in PR #1181, which updated the JSON test fixtures to a newer version, which does contain the `exp8.json` test. The failure got lost among others.
Can be seen in `py3{5,6}-vm` CI tests: for the EVM bytecode `0x600060000a600055`, which is:
```
000000: PUSH1 0x00
000002: PUSH1 0x00
000004: EXP
000005: PUSH1 0x00
000007: SSTORE
```
... there was a `15000` gas use delta (to that of expected): as if the storage was (re-)set to 0, not 1. Mentioned CI runs:
* [py35-vm](https://circleci.com/gh/ethereum/py-evm/59992?utm_campaign=vcs-integration-lin …
> eth/vm/logic/arithmetic: handle exp(X,0) == 1.

- docs/api/eth/tools/api.tools.builders.rst
- docs/api/eth/tools/api.tools.fixtures.rst
Live docs are broken (#1222)
This achieves the same visuals but doesn't use `autofunction` which I believe is causing the issue with the live docs.
> Docs: Use automodule instead of autofunction to workaround RTD issue

- .readthedocs.yml
- docs/api/eth/tools/api.tools.builders.rst
- docs/api/eth/tools/api.tools.fixtures.rst
The live docs are broken (#1222)
This does:
1. Bump up the dependencies requirements for the RTD job to include `p2p` and `trinity` which matches the `py36-docs` job. That does also mean that in the future, if docs break because of some dependency drama, we should notice that in CI as the job is equivalent with the RTD job
2. Revert the previous attempted fix that replaced `autofunction` with some hacky workaround as that didn't have anything to do with it.
I validated that this works by pushing a `doc_fix` branch into this repo (that I will remove again in a second) and reconfiguring RTD to use that branch.
Here's the working live site based on that branch
> Fix live docs (this time for real!)

- p2p/discovery.py
- p2p/exceptions.py
- p2p/kademlia.py
- tests/p2p/test_discovery.py
- tests/p2p/test_kademlia.py
- trinity/server.py
KademliaProtocol has no reason to exist as both classes just keep references
to each other and go back and forth, e.g.:
disc.recv_ping() -> kademlia.recv_ping() - > disc.send_pong()
Now everything related to handling of discovery messages is in
DiscoveryProtocol, and kademlia.py contains only the RoutingTable and
code related to calculating the distance between peers.
> Merge KademliaProtocol into DiscoveryProtocol

- .circleci/config.yml
- tox.ini
All CI jobs except for the linter jobs use the `py{version}` as a prefix while the linter jobs have it as a suffix. This is confusing me again and again when running tox locally. I think I'm even the one who screwed that up as one of the first things I screwed up in the repo :grin: 
Swap it!
> Swap py-prefix in lint job names

- tests/trinity/core/p2p-proto/test_stats.py
- trinity/protocol/common/constants.py
- trinity/protocol/common/exchanges.py
- trinity/protocol/common/handlers.py
- trinity/protocol/common/managers.py
- trinity/protocol/common/normalizers.py
- trinity/protocol/common/trackers.py
- trinity/protocol/common/types.py
- trinity/protocol/eth/exchanges.py
- trinity/protocol/eth/handlers.py
- trinity/protocol/eth/normalizers.py
- trinity/protocol/eth/requests.py
- trinity/protocol/eth/trackers.py
- trinity/protocol/les/exchanges.py
- trinity/protocol/les/handlers.py
- trinity/protocol/les/normalizers.py
- trinity/protocol/les/trackers.py
- trinity/utils/logging.py
Builds on https://github.com/ethereum/py-evm/pull/1220
We need some more useful metrics on peers.
Expanded to collect:
- EMA of the round trip request time
- EMA of the percentage of requested data that was returned (as a number between 0-100)
- EMA of the items-per-second returned by the peer
> Expand peer stats tracking

- tests/core/builder-tools/test_chain_initializer.py
- tests/trinity/core/p2p-proto/test_peer_block_header_validator_api.py
- trinity/protocol/common/managers.py
- The `timeout` parameter for the Exchange API was not being enforced correctly
- Two independent processes which issue requests over the exchange API consistently encounter the `AlreadyWaiting` exception.
For the timeout, we keep track of when the request started within the response candidate stream and enforce the *time remaining* for each payload candidate.
For the concurrency issue, the `Manager` class now has an `asyncio.Lock` on it which is acquired and released as part of the request/response cycle.  Concurrent requests will run up against this lock.  In order to differentiate between a peer `Timeout` and a timeout in acquiring the request lock, when lock acquisition times out the `AlreadyWaiting` exception is raised instead.
> Enforce timeout correctly and add lock for concurrency handling

- eth/vm/forks/spurious_dragon/state.py
`computation_class = SpuriousDragonComputation` has been assigned twice.https://github.com/ethereum/py-evm/blob/0e3663568651dcdcd8b7e4a1341219f9252bba96/eth/vm/forks/spurious_dragon/state.py#L39-L40
delete
> Delete duplicate assign statement

- p2p/kademlia.py
- scripts/benchmark/utils/meters.py
- tests/trinity/integration/test_lightchain_integration.py
- trinity/sync/sharding/service.py
- trinity/utils/ipc.py
- trinity/utils/timer.py
`time.time()` is not the most precise mechanism to measure performance. Also time might go backwards, if the system clock is reset. A number of places presumed a monotonically increasing clock when using `time.time()`. Behavior would be erratic/buggy if time moved backwards.
Depending on the precision needs, `perf_counter()` (high precision) or `monotonic()` normal precision was swapped in.
Still some questionable usages in:
- p2p/discovery.py
- trinity/sync/full/state.py
- tests
But they (potentially) "expose" the time value across API boundaries, which is highly undesirable. (only the diffs should be exposed with `perf_counter` or `monotonic`.
> Prefer time.perf_counter or monotonic over time()

- p2p/peer.py
fixes #1241 
Unhandled exception when connecting to peers.
Added an `except` clause to handle it.
> add handling for MalformedMessage during peer connection

- Makefile
- p2p/peer.py
- p2p/service.py
- tests/p2p/test_service.py
- tox.ini
When child services couldn't start (in `run_child_service` or `run_daemon`), the stack had lost who the calling parent was because of asyncio indirection.
- Raise exceptions earlier in the flow, with clearer messaging
- ValidationError slightly more helpful than RuntimeError
Also, prefer `run_child_service` over `run_task` in peer, because it has more info
to give better error messages.
> Clearer service exceptions

- p2p/peer.py
- p2p/protocol.py
- p2p/service.py
- trinity/protocol/common/managers.py
- trinity/protocol/eth/peer.py
- trinity/protocol/les/peer.py
- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
Some sync cases were crashing:
- when no peers available for sync download
- when no receipts are received in the entire batch
Some messages are not formatted correctly, or unclear
Some unnecessary cruft remained from exploratory implementations.
Crash fixes:
- early escape from no receipts
- catch `NoEligiblePeers`, log, and pause
Improve & fix formatting on exception messages and logs
Remove cruft (like the `complete_token`, in favor of just canceling the service)
Add a new `BaseService.cancel_nowait()` that can be called from inside the service without hanging.
> Improve fast-sync reliability & clean up messages

- p2p/auth.py
- p2p/discovery.py
- p2p/kademlia.py
- p2p/p2p_proto.py
- p2p/peer.py
- p2p/protocol.py
There were a few places where the formatted strings were not injecting the correct variables. Part of the issue was using `format()` with `%s`.
f-strings are the best. We should use them more. Using a variety of the formatting in the same repo is bound to lead to bugs (like a couple found here). Ergo, let's standardize on f-strings in p2p and trinity. This one only touches p2p.
Replaced every `format()` usage with an f-string.
> p2p string formatting with f-strings

- tests/trinity/utils/test_task_queue.py
- trinity/utils/datastructures.py
Two things:
- Some tasks are not inherently sortable, and get inserted with the exact same priority. When this happens, the `TaskQueue` tries to sort on the task itself and blows up.
- When an invalid sorting function (`order_fn`) is supplied to `TaskQueue` things blow up without much information why.
- Wrap the task completely before inserting to the `PriorityQueue` (so it never tries to sort on the original task)
- Raise an exception with more information if `order_fn` has strangely-broken comparisons.
> Allow unsortable tasks in TaskQueue

- eth/db/chain.py
- eth/db/header.py
- tests/database/test_header_db.py
- tests/trinity/core/integration_test_helpers.py
- trinity/db/header.py
- trinity/sync/light/chain.py
Noticed [this comment](https://github.com/ethereum/py-evm/pull/1151#discussion_r210757360) and jumped on it.
The `persist_header` API did not allow updating batches. By doing so, we can save some time as there is some work inside that method that can be shared across multiple updates.
- make the method accept a `Union[BlockHeader, Iterable[BlockHeader]]` and internally wrap single values in a list
- update call site in light change syncer to take advantage.
Btw, I think there's a further optimization that we could do. Here's a call site:
https://github.com/ethereum/py-evm/blob/cde40dbd953186aafc2832d915261089ec589002/trinity/sync/light/chain.py#L67-L70
Seems like we are fetching the canonical head right after the usage of `persist_header`. However, we know this internally and could change …
> Make 'persist_header' accept batches

- p2p/discovery.py
- tests/conftest.py
- tests/p2p/test_discovery.py
New, highly experimental, DiscoveryByTopicProtocol class that looks
up nodes by topic and falls back to kademlia's random node ID lookups
when not enough topic nodes are found.
> Implement node discovery by topic, using discv5

- trinity/chains/__init__.py
- trinity/utils/logging.py
Just fixing two minor mypy things I came across.
- one unnecessary `type: ignore`
- one superfluous `Union[...]`  
Removed `Union` and added correct type hints.
> Fix minor typing issues

- p2p/peer.py
- tests/trinity/integration/test_lightchain_integration.py
- trinity/protocol/common/proto.py
- trinity/protocol/eth/proto.py
- trinity/protocol/les/commands.py
- trinity/protocol/les/peer.py
- trinity/protocol/les/proto.py
- trinity/sync/light/service.py
Another extraction from #1259 
This cleans up the usage of the `ChainInfo` object.  The light peer previously stored a reference to this locally.  I suspect we can revive something like this at some point but for now this reduces some complexity and makes #1259 cleaner to read.
> Remove chain info property from LESPeer

- eth/chains/base.py
- eth/rlp/receipts.py
- eth/vm/base.py
- eth/vm/forks/byzantium/__init__.py
- tests/trinity/core/integration_test_helpers.py
- trinity/chains/__init__.py
- trinity/chains/light.py
- trinity/sync/full/chain.py
fixes #1246
See #1246 
Both the `Chain` and `VM` classes now expose a `validate_receipt` method.  This validation is called during receipt creation by the VM class as well as during chain sync.
> Move receipt validation to Chain and VM methods

- trinity/cli_parser.py
- trinity/main.py
- trinity/utils/logging.py
Using just `--log-level DEBUG` didn't correctly effect the stderr log level.
Removed the defaults for `--stderr-log-level` so that we can detect when the value has not been provided and to default it to the global log level if provided by `--log-level`.
> Fix logging configuration

- eth/precompiles/modexp.py
- tests/core/vm/test_modexp_precompile.py
- tests/json-fixtures/test_blockchain.py
- tests/json-fixtures/test_state.py
- tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
See issue #1152, in particular https://github.com/ethereum/py-evm/issues/1152#issuecomment-417284202.
* The `ethereum/tests` git submodule in `fixtures` is rather old:
* 2017-12-08 - https://github.com/ethereum/tests/commit/47b09f42c0681548a00da5ab1c98808b368af49a - merge of PR https://github.com/ethereum/tests/pull/374.
* `py-evm` PR #1181 enables `ConstantinopleVM` testing with a much newer test set; having these changes "lumped together" makes it harder to attribute CI run failures to one or the other, at least at a cursory look.
Incrementally:
* [Updates the submodule](https://github.com/ethereum/py-evm/pull/1224/commits/3fef4bd3d596eb4a16fc63ae4c6795bfaa03b641) to:
* 2018-01-22 - https://github.com/ethereum/tests/commit/db8ae9de91c303caad3eb9354015c07a0ec3adc3 - merge of PR …
> Update ethereum/tests fixtures

- p2p/service.py
- tests/trinity/utils/test_task_queue.py
- trinity/protocol/common/handlers.py
- trinity/protocol/common/managers.py
- trinity/protocol/common/trackers.py
- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
- trinity/sync/full/service.py
- trinity/utils/datastructures.py
- trinity/utils/timer.py
Requests for block data and receipts were batched together. A slow peer can dramatically slow down this process.
Roughly, put everything into queues so they can run independently, and one peer isn't waiting on another to finish.
Numbers vary widely, but I've seen as high as 1500 blocks imported in 5 s.
TODO:
> Download all data in queues (instead of batches) while fast & regular syncing

- p2p/discovery.py
- p2p/exceptions.py
- tests/p2p/test_discovery.py
This basically adds two new APIs that allow us to ask a remote node for
a discv5 ticket (DiscoveryProtocol.get_ticket()) and then use that to
register ourselves under a given topic (DiscoveryProtocol.send_topic_register())
> Implement discv5 topic registration

- setup.py
prevent releases from using outdated setuptools which strips enviroment markers from the released wheel.
> Pin setuptools>=36.2.0

- p2p/service.py
- trinity/sync/full/chain.py
Using `loop.call_later` directly won't get cancelled with the service.
`BaseService` wraps a lot of coroutines, which makes for bad messages and stack traces.
- Added a new `BaseService.call_later()` that cancels with `BaseService`.
- Decorate the wrappers with `@functools.wraps(awaitable)`
> BaseService extensions

- docs/conf.py
CI build fails for docs job https://circleci.com/gh/ethereum/py-evm/75639?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Use the newer option format
> Do not use deprecated sphinx option

- p2p/discovery.py
- tests/trinity/integration/test_trinity_cli.py
The `DiscoveryService` had an `asyncio.Lock` object set as a class variable.  Aside from this being problematic since it would mean that all instances of the `DiscoveryService` share this object, instantiating the `Lock()` object has the side effect of populating the default event loop for the thread.
The `p2p.discovery` module is imported in the `./tests/trinity/conftest.py` file which is loaded when running the integration tests.  This results in the event loop being set prior to the execution of those tests.
While working on https://github.com/ethereum/py-evm/pull/1286/files this import was removed resulting in this CI failure
https://circleci.com/gh/ethereum/py-evm/75904?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
``` …
```
> expose strange bug

- setup.py
- tests/trinity/integration/test_trinity_cli.py
- trinity/__init__.py
- trinity/tools/async_process_runner.py
The default event loop provided by `asyncio` is written in python.  Python is slow...
There exists a library called [`uvloop`](https://github.com/MagicStack/uvloop) which is a c implementation of the python event loop which is supposed to be up to 2x faster.
If the installation platform is Linux or Darwin, install `uvloop` and set it as the default event loop.
> Use uvloop on unix and darwin

- docs/cookbooks/index.rst
- docs/guides/eth/building_an_app_that_uses_pyevm.rst
- docs/guides/eth/understanding_the_mining_process.rst
- eth/chains/base.py
- eth/db/__init__.py
- eth/db/chain.py
- eth/db/header.py
- eth/tools/builder/chain/builders.py
- eth/tools/fixtures/helpers.py
- scripts/benchmark/utils/chain_plumbing.py
- tests/conftest.py
- tests/core/chain-object/test_chain_get_ancestors.py
- tests/core/chain-object/test_chain_retrieval_of_vm_class.py
- tests/core/chain-object/test_header_chain.py
- tests/core/opcodes/test_opcodes.py
- tests/database/test_chaindb.py
- tests/database/test_header_db.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- tests/trinity/core/integration_test_helpers.py
- tests/trinity/core/p2p-proto/test_server.py
- tests/trinity/core/p2p-proto/test_sync.py
- tests/trinity/core/peer_helpers.py
- tests/trinity/integration/test_lightchain_integration.py
- trinity/chains/__init__.py
We want to use atomic writes in chaindb and headerdb, but they only have access to the `BaseDB` API.
Make `ChainDB` and `HeaderDB` (and all the knock-on effect classes, like `Chain`) require a `BaseAtomicDB` argument for setup.
This PR doesn't actually use the new atomic writes anywhere, it's all setup.
> Require BaseAtomicDB in ChainDB and HeaderDB

- p2p/discovery.py
- p2p/kademlia.py
- tests/p2p/test_discovery.py
- tests/p2p/test_kademlia.py
Sometimes a NEIGHBOURS response from remote peers will include nodes
with a loopback or private network address that is not reachable to us,
so we must skip those. We must also skip those on reserved networks or
with an unspecified address (0.0.0.0).
Closes: #821
> During node discovery, skip those with invalid addresses

- Dockerfile
- the images is base python:3.6
so i think don't create new virtual environment
- use --no-cache-dir
The following is a comparison of space
```bash
➜  pyevm git:(master) ✗ docker images ethereum/trinity
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ethereum/trinity    nocache             adfa8f214bfa        4 minutes ago       1.09GB
ethereum/trinity    latest              8798f7795bc6        9 minutes ago       1.32GB
```
> Make docker images smaller

- p2p/discovery.py
- p2p/peer.py
- p2p/service.py
- trinity/utils/logging.py
The handle_peer_count_requests() coroutine runs as a background task but
did not exit when the pool's cancel token was triggered.
Also introduce a custom log formatter for trinity that uses the last
element of the logger's name instead of the module, otherwise it's not
clear where they're coming from (specially for those generated by
BaseService subclasses).
> Fix a never-ending subtask in BasePeerPool

- eth/tools/fixtures/fillers/formatters.py
- p2p/discovery.py
- p2p/kademlia.py
- p2p/p2p_proto.py
- p2p/peer.py
- tests/json-fixtures/test_state.py
- trinity/plugins/builtin/attach/console.py
- trinity/server.py
- trinity/sync/common/chain.py
- trinity/sync/full/state.py
- trinity/sync/light/service.py
A couple simple warnings are being raised in trinity code. These were found with #1312 
- Stop using the deprecated `combine_argument_formatters()`
- Use `logging.warning` instead of `logging.warn`
> Some simple warning fixups

- eth/vm/forks/byzantium/__init__.py
- eth/vm/forks/byzantium/headers.py
- eth/vm/forks/constantinople/__init__.py
- eth/vm/forks/constantinople/constants.py
- eth/vm/forks/constantinople/headers.py
- tests/core/vm/test_rewards.py
We need to implement [EIP1234](https://eips.ethereum.org/EIPS/eip-1234)
Refactored Byzantium implementation to be more reusable for Constantinople. Left a comment inline for an alternative implementation idea.
> Implement EIP 1234

- setup.py
- trinity/extensibility/__init__.py
- trinity/extensibility/exceptions.py
- trinity/extensibility/plugin.py
- trinity/extensibility/plugin_manager.py
- trinity/main.py
- trinity/plugins/builtin/attach/plugin.py
- trinity/plugins/builtin/fix_unclean_shutdown/plugin.py
- trinity/plugins/builtin/json_rpc/plugin.py
- trinity/plugins/builtin/light_peer_chain_bridge/plugin.py
- trinity/plugins/builtin/tx_pool/plugin.py
- trinity/utils/shutdown.py
Currently, plugins that run in the shared network process do not shutdown cleanly in all scenarios (see #1284). To be more precise, they only shutdown if they happen to be chained with some `CancelToken` which is triggered. This means that for all current plugins that run in the networking process (`TxPool`, `LightPeerChainBridge`) there isn't a real problem as these will simply shutdown based the fact that e.g the `PeerPool` shuts down or the `LightPeerChain` shuts down. However, this is still leaving us with two problems:
1. Plugins that do not have a logical dependency that they can rely on to initiate cancellation are left out
2. Plugins can't stopped individually (think, future command `trinity stop-plugin <plugin-name>`
Before we dive into how exactly it was fixed, let's first take …
> Ensure shared process plugins shutdown cleanly

- trinity/sync/full/service.py
FullNodeSyncer._run() attempted to delete a local variable that was
defined inside an if block, which would cause a NameError when the
if block was not executed.
> Fix a couple places that deleted a name defined conditionally

- trinity/protocol/common/managers.py
- trinity/sync/full/chain.py
Mildly related race conditions during peer shutdown:
1. A peer's response future might be set, but not collected, when it is shut down. This was causing uncaught `asyncio.InvalidStateError` when trying to set an exception on the response future.
2. A peer may get launched and shut down immediately, which was confusing the `ExchangeManager`. It interpreted a closed service as always being unstarted.
1. Catch the error, log it, and continue (nothing further needs to happen).
2. Detect if the service has been started and shut down, and return a `PeerConnectionLost` to indicate to the caller that the peer is now unavailable.
Plus, drop a typically unnecessary log down to trace.
> Peer shutdown race conditions

- trinity/main.py
- trinity/utils/logging.py
- trinity/utils/version.py
`trinity` is spouting a bunch of warnings, and no one noticed. Presumably because none of us explicitly turned warnings on.
Check if we are in a pre-release version (alpha or beta). If so, turn on warnings. This will help us catch warning things sooner.
I'm not totally convinced it's a good idea, but it did help me do some cleanups. Also, it seems to highlight a bunch of unclean connection handling.
> Turn on warnings by default, if in prerelease

- trinity/sync/common/chain.py
`BaseHeaderChainSyncer` did a lot of things all together, like pick the peer to sync with, and then do all the header syncing with that peer. This structure was not friendly to changes like swapping in a new peer mid-stream to do the header-sync, or switching to a skeleton header sync.
Added a new service that only runs for the lifetime of a single peer's header syncing. This splits the code that does peer selection out of the code that actually syncs with the given peer.  I have some code for the mid-sync-swap drafted, but I suspect that will require some more conversation. I'm hoping that we can get this merged in the meantime.
~~Marked wip because I'm getting type errors in code that wasn't touched. cc cburgdorf for ideas?~~ _(Nevermind, the type errors are only showing up on my local …
> Split peer selection from header sync

- tests/p2p/helpers.py
- tests/p2p/test_discovery.py
- tests/p2p/test_discovery_v5.py
The original `tests/p2p/test_discovery.py` test module monkeypatches the timeout to be `0.01` for kademlia requests because all of the tests used mocked out networking and thus, should not exceed that timeout.
With the addition of discovery v5, some of the tests were now making network requests, which resulted in timeouts on slower hardware (like our CI environment)
Partitioned the tests so that the ones which make actual network requests are separate from the ones that don't.
> Fix flakey discovery tests

- scripts/db-shell.py
- tests/trinity/core/chain-management/test_initialize_data_dir.py
- tests/trinity/core/chain-management/test_initialize_database.py
- tests/trinity/core/chain-management/test_is_data_dir_initialized.py
- tests/trinity/core/chain-management/test_is_database_initialized.py
- tests/trinity/core/config/test_trinity_config_object.py
- tests/trinity/core/database/test_database_over_ipc_manager.py
- trinity/chains/__init__.py
- trinity/config.py
- trinity/extensibility/events.py
- trinity/extensibility/plugin.py
- trinity/extensibility/plugin_manager.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/plugins/builtin/attach/plugin.py
- trinity/plugins/builtin/ethstats/ethstats_service.py
- trinity/plugins/builtin/fix_unclean_shutdown/plugin.py
- trinity/plugins/builtin/json_rpc/plugin.py
- trinity/plugins/builtin/light_peer_chain_bridge/plugin.py
- trinity/utils/chains.py
- trinity/utils/logging.py
As part of https://github.com/ethereum/py-evm/pull/1299 I found that the logic within the `ChainConfig` was getting too complex.  
To combat this, I decided to split the config into two parts.
- The `ChainConfig` which **only** handles configuration of the `Chain` object.
- The `TrinityConfig` which handles everything else.
This pull request does step 1 in this, renaming the existing `ChainConfig` to `TrinityConfig`.  A subsequent PR will introduce the new `ChainConfig`.
> Rename ChainConfig to TrinityConfig

- trinity/plugins/builtin/ethstats/plugin.py
Users were using ethstats server URL without path. Fixes #1337.
Added example with path in `--help` output, added default server URLs for mainnet and ropsten.
> added default server URL for mainnet and ropsten, improved help message

- trinity/plugins/builtin/ethstats/plugin.py
PR #1343 was merged before (20 hours prior to) PR #1348, but the latter didn't pick up the changes for some reason, and hasn't been run against actual `master` at the moment of merge.
In other words, PR #1348 had all CircleCI integration check-boxes green prior to @cburgdorf squash-merging it, but that was against an old commit.
So far, identified one minor change that caused breaks - network ID constants being moved to a different module.
It's a crash!..
Source: [Soggydan Benenovitch on flickr](https://www.flickr.com/photos/soggydan/6092175826/in/pool-62721506@N00)
> Trinity ethstats plugin: fix CI breakage due to constant having moved

- eth/tools/fixtures/normalization.py
There are 2 issues with the function `normalize_bytes` in eth/tools/fixtures/normalization.py#L68
1) The `if condition` should be checking whether the `len(value)` is 0 first, and then move on to verifying `is_hex(value)`. The problem arises when `value = b''`
2) As per the `eth_util library`, `is_hex function` takes only strings as argument. So the bytes should be converted to string using value = value.decode('utf-8') in the beginning of the function.
1) The `if condition` was reversed
2) `bytes` is converted to `string` using `decode('utf-8')` function
> Fix Minor Bugs in Tools

- eth/vm/memory.py
The If Clause code will never be executed and `validate_lte` would replace its functionality always. Hence need to delete this lazy extension.
The If Clause is to be deleted instead of the `validate_lte`, because if that was kept then we would be increasing memory without charging gas for the increased memory.
> Remove Unnecessary Lazy Extension Code

- trinity/protocol/common/handlers.py
- trinity/protocol/common/peer.py
- trinity/protocol/eth/handlers.py
- trinity/protocol/les/handlers.py
- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
- trinity/sync/light/chain.py
- trinity/sync/light/service.py
_I hadn't had a good tussle with mypy for a while, and I like punishment._
`HeaderRequestingPeer` was an old "poor coder's" version of `BaseChainPeer`
_Rope-a-dope with mypy, plus a crucial assist from cburgdorf._
Replaced `HeaderRequestingPeer` with `BaseChainPeer`, and resolve the mypy fallout.
> Use BaseChainPeer instead of HeaderRequestingPeer

- .circleci/config.yml
- eth/utils/blake.py
- eth/vm/forks/byzantium/__init__.py
- eth/vm/forks/byzantium/headers.py
Mypy tests were not being triggered for `eth` module.
1. Fixed CircleCI setting
2. Fixed some type hints errors
> Fix mypy tests for `eth` package

- pytest.ini
I got stuck on debugging longer than necessary, because timestamp was
missing from the default pytest log format.
Add timestamp, and other features that make pytest similar to the trinity logging format
> Use similar log formatting in pytest & trinity cli

- scripts/benchmark/utils/chain_plumbing.py
The current benchmarks use an impromptu API to create the chains that are used for benchmarking.
We now have some more solid `builder tools` to create chains. These tools allow the creation of chains using a declarative, fluent API which we do use already in several tests. These `builder tools` are now integrated in `Benchmarks` for building the chains.
> Use chain builder tools to cleanup benchmarks

- eth/vm/forks/byzantium/transactions.py
- eth/vm/forks/constantinople/transactions.py
- eth/vm/forks/frontier/transactions.py
- eth/vm/forks/homestead/transactions.py
- eth/vm/forks/spurious_dragon/transactions.py
- eth/vm/logic/call.py
- scripts/benchmark/utils/tx.py
- tests/core/helpers.py
- tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
There are lots of places in the codebase with either classes or functions which take 6+ parameters. In these cases, calling these using positional arguments can be both error prone as well as hard to read.
* Errors arise when arguments are accidentally called in the wrong order.
* Difficult readability comes when it's not clear what each parameter actually means since sometimes multiple parameters might be called with the same constant value `f(b'', b'')`.
PEP3102 introduces a new syntax for requiring certain arguments to be called as keyword arguments. Based on the above format the function signatures and the way in which they were called throughout the system were changed. The functions which were changed are as follows
>evm/vm/logic/call.py
>272:def compute_eip150_msg_gas(computation, …
> Require parameters to be passed as keyword arguments for long function signatures

- setup.py
Mypy is still on 0.620
Updated to 0.630
New features: http://mypy-lang.blogspot.com/2018/09/mypy-0630-released.html
> Update mypy to 0.630

- p2p/peer.py
- p2p/service.py
- trinity/protocol/common/monitors.py
- trinity/protocol/eth/monitors.py
- trinity/protocol/les/monitors.py
- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
- trinity/sync/light/chain.py
Sometimes a class wants to know if there is a chance of a new tip (based on a new peer or a new block).  Previously the best way to do it was to become a `PeerSubscriber`. That adds a lot of extra code overhead.
Added a new tip monitor class. When you want to act on potentially new tip info, simply do:
```py
tip_monitor = ETHChainTipMonitor(...)
asyncio.ensure_future(tip_monitor.run())
async for highest_td_peer in tip_monitor.wait_tip_info():
do_something_with_new_tip(highest_td_peer)
```
Pulled out of #1353 -- with a few random logging improvements.
The `highest_td_peer` getting returned is a little weird here. It is the closest implementation to the old way of doing things. One alternative would be to return the peer that provided the new tip info. I kept the current implementation, …
> Chain tip monitor

- eth/utils/address.py
- tests/core/address-utils/test_address_generation.py
The generated address for the new CREATE2 opcode turned out to be wrong. By the time that I implemented it, there were no test cases so the implementation was a shot in the dark (and still kinda is, as this only partly covers what CREATE2 does).
Now we do have test cases and they discovered a bug in our implementation.
Correctly interpret salt + add tests.
> Fix bug in CREATE2 address generation + add test

- scripts/benchmark/utils/chain_plumbing.py
Accidentially passed wrong value for `genesis_state` in `get_chain`
Changed passed parameter.
> Fix incorrect parameter to get_chain

- eth/consensus/pow.py
- eth/db/account.py
- eth/precompiles/ecadd.py
- eth/precompiles/ecmul.py
- eth/precompiles/ecpairing.py
- eth/precompiles/ecrecover.py
- eth/precompiles/modexp.py
- eth/utils/numeric.py
- eth/utils/transactions.py
- eth/vm/forks/spurious_dragon/transactions.py
- eth/vm/stack.py
Came across this while working on something else. Seems we had some helpers in `eth.utils.numeric` that we also have in `eth_utils`. Guess those were in place from a time where `eth_utils did not exist or at least did not have these methods.
Migrated to `eth_utils`.
> Migrate util usage to eth_utils

- setup.py
- tests/trinity/conftest.py
- trinity/extensibility/events.py
- trinity/extensibility/exceptions.py
- trinity/extensibility/plugin.py
- trinity/extensibility/plugin_manager.py
- trinity/main.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/plugins/builtin/ethstats/plugin.py
- trinity/plugins/builtin/json_rpc/plugin.py
- trinity/plugins/builtin/light_peer_chain_bridge/plugin.py
- trinity/plugins/builtin/tx_pool/plugin.py
Currently plugins have two different ways of consuming events:
1. Comsuming `lahja` events through the `EventBus`
2. Consuming *plugin events*  through `handle_event`
With the upcoming `lahja` release, this can be unified.
1. Plugins consume `EventBus` events only
2. `should_start` is gone. The model has turned. While previously the `PluginManager` called `_start()` on the plugins, plugins do now call `handle_start()` themselves.
3. Because of the former, it is now the responsible of the plugin base classes to flip a `running` property on which the `PluginManager` figures out which plugins need to be stopped
3. The `Node` does not depend on the `PluginManager` any more
2. I think the `start` and `handle_start`  methods could use better names. The `handle_start` method is what plugins need …
> Refactor plugin support to exclusively use EventBus events

- p2p/peer.py
There's a hack in `PeerPool` that can be removed as soon as #1331 lands which updates to `lahja` `0.9.0` which makes this hack obsolete.
Removed hack.
> Remove obsolete hack

- setup.py
- trinity/utils/logging.py
- trinity/utils/shellart.py
Do you spot the `ERROR` in here?
Me, neither!
Colors! :rainbow: 
With this change, everything worse than `ERROR` is printed bold and red and everything worse than `WARNING` (but less bad than `ERROR`) is printed bold and yellow.
Notice that this copies the `shellart` util that we already use in the benchmark to Trinity because there doesn't seem to be a common space to share between both projects and the file is simple and small enough that I think the copy is ok.
> Colorize shell output based on log level

- tests/trinity/integration/test_trinity_cli.py
- trinity/events.py
- trinity/extensibility/plugin.py
- trinity/main.py
- trinity/plugins/builtin/ethstats/plugin.py
- trinity/plugins/builtin/tx_pool/plugin.py
1. Trinity always prints `Keyboard Interrupt: Stopping` on shutdown even if the shutdown was not initiated by a `KeyboardInterrupt`
2. The `message` parameter to `kill_trinity_gracefully` was never used and hence removed
1. Trinity now prints the reason for the shutdown next to the `Shutting down Trinity` as well as next to the `Trinity shutdown complete` message, making it more obvious to the user why Trinity was shutdown
2. `message` parameter was removed
> Fix and improve logging output

- tox.ini
- trinity/nodes/full.py
- trinity/nodes/light.py
As seen with #1385 and https://github.com/python/mypy/issues/5771 `mypy` currently doesn't provide us the type safety that we expect it should.
Turns out, we didn't install all expected dependencies for the `mypy` run. That means, `mypy` was checking the source code but didn't have any of the other dependencies installed. Having the dependencies installed is important for mypy to infer the type info it needs to do its checks.
> Ensure mypy checks correctly in CI

- eth/beacon/aggregation.py
- eth/beacon/block_committees_info.py
- eth/beacon/block_proposal.py
- eth/beacon/db/chain.py
- eth/beacon/helpers.py
- eth/beacon/state_machines/base.py
- eth/beacon/state_machines/forks/serenity/__init__.py
- eth/beacon/state_machines/forks/serenity/attestation_records.py
- eth/beacon/state_machines/forks/serenity/blocks.py
- eth/beacon/state_machines/validation.py
- eth/utils/bitfield.py
- eth/utils/numeric.py
- tests/beacon/state_machines/conftest.py
- tests/beacon/state_machines/test_block_validation.py
- tests/beacon/state_machines/test_proposer.py
- tests/beacon/state_machines/test_state_machines.py
- tests/beacon/test_aggregation.py
- tests/beacon/test_helpers.py
- tests/core/bitfield-utils/test_bitfields.py
Apologize for the fat PR. 🙈 
#1381 - StateMachine - per block transition and attestation
1. No `update_ancestor_hashes`  design in this PR
2. No RANDAO reveal design in this PR
3. No versioning design in this PR
1. `helpers.py`
1. Bugfix `get_hashes_to_sign` - shouldn’t re-hash the latest hash
2. Remove multiple slots per committee option: https://github.com/ethereum/eth2.0-specs/pull/62
3. Rename `get_proposer_position` to `get_block_committees_info`, it will return `BlockCommitteesInfo` as a simple structure of the committee information context.
2. `eth.beacon.state_machines.base.py`
1. **Import block APIs**
1. Import the given block into state machine
2. Call process APIs; if valid, update the states in memory
2. **Process block APIs** (all are classmethods)
1. Pure functions for …
> Per block transition and attestation

- eth/beacon/block_proposal.py
I broke the py35-lint checks... `BlockProposal.shard_block_hash` should be `Hash32`.
Change it to `Hash32`.
(Sorry! (and I should have rebased))
/
😿
> Fix type hints

- scripts/benchmark/utils/chain_plumbing.py
Currently, all our benchmarks run against the `MemoryDB`. Unfortunately, that means we are missing out to measure pretty much all optimizations that are about reducing the number of hits to read/write to the database.
In other words, if some optimizations save e.g. two hits to the DB we will barely see any difference in the benchmarks as data updates in-memory are just super fast compared to the actual cost when we hit the disk (which will be the case with something like `LevelDB`.
Issue : #1359 
While creating the chains, for each benchmark the chains were created one with `MemoryDB` and one with `LevelDB` in `chain_plumbing.py` which is the base for all the benchmarks.
> Memory db to level db

- eth/tools/_utils/normalization.py
- eth/tools/builder/chain/builders.py
- eth/tools/fixtures/fillers/common.py
- eth/tools/fixtures/fillers/state.py
- eth/tools/fixtures/fillers/vm.py
- eth/tools/fixtures/helpers.py
- eth/tools/fixtures/normalization.py
- tests/core/fixture-tools/test_normalize_state.py
- tests/json-fixtures/test_state.py
State tests are out of date and there seem to be some structural changes to fix before we can move #1181 forward
- update to latest `ethereum/tests` submodule
- handle new `sealEngine` property
- workaround issue with the way these tests are generated and the side effects that causes in respect to state clearing (shout out to @pipermerriam for the awesome debugging session helping with that :pray:)
> Update state tests

- eth/beacon/state_machines/base.py
- eth/beacon/types/crystallized_states.py
- tests/beacon/state_machines/test_block_validation.py
- tests/beacon/state_machines/test_proposer.py
- tests/beacon/state_machines/test_state_machines.py
- tests/beacon/test_genesis_helpers.py
- tests/beacon/types/test_crystallized_state.py
#1381
Before adding the [whole cycle transition process](https://github.com/ethereum/eth2.0-specs/blob/master/specs/beacon-chain.md#state-recalculations-every-cycle_length-slots), first, adding `compute_cycle_transitions`.
1. `compute_cycle_transitions` does two things:
1. Check if `block.slot_number >= crystallized_state.last_state_recalc + config.CYCLE_LENGTH`; if yes: 
- Call `compute_per_cycle_transition` (a.k.a. `initialize_new_cycle` in `beacon_chain` repo) to compute new cycle and get updated states.
- TODO in other PRs: `compute_crosslinks` will call `compute_crosslinks` and `apply_rewards_and_penalties`.
- Check if it's ready for dynasty transition.
- If yes, call `compute_dynasty_transition`
2. Return the updated states.
2. Renamed `total_deposits` to `total_balance` as the …
> Add `compute_cycle_transitions`

- eth/_warnings.py
- eth/chains/base.py
- eth/constants.py
- eth/db/backends/level.py
- eth/db/chain.py
- p2p/nat.py
- setup.py
- trinity/__init__.py
This commit fixes ImportWarning-s issue (#1402, #1370). As mentioned in referred issue, this is a Cython bug fixed in master and not yet available. We can't fix it in py-evm modules.
A suggested [workaround](https://bugs.launchpad.net/lxml/+bug/1732505/comments/4) was used.
> Suppress ImportWarning messages

- docs/api/trinity/api.cli.rst
- docs/api/trinity/extensibility/api.extensibility.events.rst
- docs/api/trinity/extensibility/api.extensibility.exceptions.rst
- docs/api/trinity/extensibility/api.extensibility.plugin.rst
- docs/api/trinity/extensibility/api.extensibility.plugin_manager.rst
- docs/api/trinity/extensibility/index.rst
- docs/api/trinity/index.rst
- trinity/extensibility/__init__.py
- trinity/extensibility/exceptions.py
- trinity/extensibility/plugin.py
- trinity/extensibility/plugin_manager.py
Plugins didn't have proper API docs yet. There were also some easy to fix glitches that this PR addresses. Notice that this is just a first step towards a full detailed plugin guide which is coming in a separate PR (#1429 )
- created API docs
- created `TrinityBootInfo` type to reduce complexity of several method signatures
- Use `pass` instead of `raise` for abstract methods
- Fix that ugly thing were we return `None` as a context
> API docs + some fine tuning for Plugin API

- eth/chains/ropsten/__init__.py
- eth/chains/ropsten/constants.py
The Constantinople fork has occured on ropsten but our `RopstenChain` was not updated.
Updated the `RopstenChain` to include the constantinople fork
> enable Constantinople fork in Ropsten chain

- trinity/main.py
The ASCII "trinity" header that is printed out when running the trinity command uses forward slashes.  These cause warnings because python thinks they are supposed to be escape sequences.
Update header to use raw strings.
> Fix warnings when printing Trinity cli header

- eth/chains/mainnet/__init__.py
- eth/chains/mainnet/constants.py
- eth/chains/tester/__init__.py
- eth/tools/builder/chain/builders.py
- eth/tools/fixtures/helpers.py
- eth/vm/forks/homestead/__init__.py
- eth/vm/forks/homestead/headers.py
- tests/core/chain-object/test_chain_reorganization.py
- tests/core/tester/test_generate_vm_configuration.py
- tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
- trinity/protocol/common/boot.py
The default `HomesteadVM` came with the dao fork block number already set.  This didn't seem semantically correct since the block number would differ based on the chain configuration and what chain it was used in.
Changed to have the block number configured within the context of the mainnet chain.
> Move mainnet DAO fork config into mainnet configuration

- eth/tools/_utils/git.py
- eth/tools/_utils/hashing.py
- eth/tools/_utils/mappings.py
- eth/tools/_utils/normalization.py
- eth/tools/_utils/vyper.py
- eth/tools/builder/chain/builders.py
- eth/tools/fixtures/_utils.py
- eth/tools/fixtures/fillers/_utils.py
- eth/tools/fixtures/fillers/common.py
- eth/tools/fixtures/fillers/main.py
- eth/tools/fixtures/fillers/state.py
- eth/tools/fixtures/fillers/vm.py
- eth/tools/fixtures/generation.py
- eth/tools/fixtures/helpers.py
- eth/tools/fixtures/loading.py
- eth/tools/fixtures/normalization.py
- eth/typing.py
- eth/utils/datatypes.py
- tox.ini
- trinity/rpc/modules/evm.py
Issue : #1398
Adding the type hints for `eth.tools` module completely.
> Complete Type Hinting for `eth.tools`

- trinity/utils/version.py
Version string was being created as:
```
Trinity/eth-0.2.0a33/linux/namespace(_multiarch='x86_64-linux-gnu', cache_tag='cpython-36', hexversion=50726384, name='cpython', version=sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0))3.6.5
```
Fixed the missing `.name` property in the f-string.
> fix broken implementation of version string

- docs/guides/trinity/architecture.rst
- docs/guides/trinity/index.rst
- docs/guides/trinity/writing_plugins.rst
- tests/trinity/plugins/test_examples.py
- trinity/extensibility/exceptions.py
- trinity/extensibility/plugin.py
- trinity/plugins/builtin/ethstats/plugin.py
- trinity/plugins/builtin/json_rpc/plugin.py
- trinity/plugins/builtin/light_peer_chain_bridge/plugin.py
- trinity/plugins/builtin/tx_pool/plugin.py
- trinity/plugins/builtin/tx_pool/pool.py
- trinity/plugins/examples/__init__.py
- trinity/plugins/examples/peer_count_reporter/plugin.py
For people to start contributing Trinity plugins or building their own applications with the Trinity + Plugins Model we need to do a good job of teaching them how to use the Plugin API. So we need a detailed guide for the Plugin API. Notice that this PR is a spin off from #1424 to allow #1424 to get merged sooner while I take more time for writing the guide.
This is a draft version that we may merge anyway to have **something** for DEVCON !V
> Create guide on how to create plugins

- trinity/main.py
Currently, when sending a SIGTERM to the Trinity
main process, Trinity doesn't shut down gracefully.
The main process shuts down but the child processes
doesn't.
This can easily be reproduced:
1. Run `trinity`
2. Take note of the `pid` printed as *Started main process (pid=`<pid-to-note>`)*
3. Open another terminal and run `kill <pid>
Notice that the main process is killed but the child processes keep on running.
This change does two things:
- print out the main process id at boot
- handle SIGTERM correctly
Relates to #1461
> Ensure Trinity handles SIGTERM send to main process

- trinity/plugins/builtin/ethstats/ethstats_client.py
When the ethstats plugin connects without secret we get a string response instead of the expected JSON object. This then further leads to a `TypeError` if we try to access an attribute on that string.
Check if `raw_message` is a string and raise an exception. Also ensure ethstats errors are logged as `warning` not `info`.
> Ensure ethstats plugin handles incorrect server responses

- p2p/peer.py
Fixes #1455 
(Well, it doesn't fix the issue the way that 1455 originally asked to, but I would rather prevent the problem than do occasional cleanups after an unknown problem occurs)
Identify if a peer has disconnected during the boot up process, and if so, don't add it to the pool.
> If peer disconnects during boot, don't add to pool

- eth/tools/fixtures/loading.py
- tests/conftest.py
- tests/json-fixtures/test_state.py
- tox.ini
The statetest fixtures have different definitions
for each fork and we must ensure to only run
test against against the intended fork (e.g run
Constantinople state tests against Constantinople VM).
We can not rely on `pytest -k` matching for that
as that matches against an identification string that
includes the path and name of the test file which in
some cases also contains fork names. A test file may
be named "ConstantinopleSomething.json" but still
contains individual definitions per fork.
Add a mechanism so that the intended fork can be passed as `--fork` and then internally filter the generated fixtures against that.
Notice that this does only apply to state tests as these are the only test files expands into multiple test cases per fork.
The following table compares the number of …
> Ensure state tests only run against the intended fork

- trinity/plugins/builtin/ethstats/ethstats_service.py
If an `uptime` is not submitted, the dashboard displays `NaN%` for the node; and also `NaN%` for the averaged uptime of all tracked nodes.
Hard-coded to "100%".
Original JS `ethstats` client keeps count of failed/total data collection/submission events, so that it can showcase downtime. We're not doing this, and perhaps shouldn't (yet) - much better things to do...
Also, the displayed uptime gradually drops for nodes that have disconnected, so this works "good enough".
Source: [BuzzFeed's Adorably](https://mobile.twitter.com/Adorably/status/527095681430069248); author unknown
> `ethstats` plug-in: send 'uptime' to prevent "NaN%" display on dashboard

- trinity/sync/common/chain.py
- trinity/sync/full/chain.py
- trinity/sync/full/service.py
- trinity/sync/light/chain.py
We currently do not log when the fast-sync has finished. Two reasons to have this:
1. Achieve symmetry (we do log when fast sync begins)
2. Have it easier to grep the logs to see if a fast-sync finished or not
Add a `info` log when the fast sync has finished.
> Log when fast-sync has finished

- setup.py
- setup_trinity.py
Outdated info in `setup.py`. Also pip should prevent people from trying to install Trinity on Python versions below `3.6`.
Related: https://github.com/ethereum/snake-charmers-internal-handbook/issues/3
Magic!
I believe that the `python_requires` change does only affect people who try to install Trinity from pypi as anyone else who would `pip install -e [trinity]` directly from the repository root, would hit the `setup.py` file instead of the `setup_trinity.py` file.
> Cleanup classifiers and add python_requires to setup.py

- tests/trinity/core/humanize-utils/test_humanize_elapsed.py
- trinity/protocol/common/trackers.py
- trinity/sync/full/chain.py
- trinity/utils/ema.py
- trinity/utils/humanize.py
fixes #1423 
The logging output during chain sync didn't expose certain valuable metrics.
Improved logging output to explose;
- num blocks
- num transactions
- EMA of blocks-per-second
- EMA of transactions-per-second
- elapsed time since last logging message
- head block number and hash (first and last 4 hex digits)
- age of head block in a terse format
```
INFO  11-19 11:39:40       FastChainSyncer  blks=326   txs=193    bps=62   tps=73    elapsed=5.0  head=#267756 (566e…b671)  age=3y1m4w
INFO  11-19 11:39:46       FastChainSyncer  blks=284   txs=287    bps=62   tps=72    elapsed=5.6  head=#268040 (9dba…a01c)  age=3y1m4w
INFO  11-19 11:39:51       FastChainSyncer  blks=330   txs=396    bps=62   tps=72    elapsed=5.0  head=#268370 (148f…eeb7)  age=3y1m4w
INFO  11-19 11:39:58 …
```
> Improve logging output during chain sync

- p2p/auth.py
- p2p/peer.py
fixes #1403 
As part of our peer connection logic we initiate a low level connection, then create a `Peer` instance, then perform a handshake, followed by starting the peer service.  If anything goes wrong before the service starts, the connection will be left open causing these warnings.
wrapped the handshake step in a `try/except` which closes the connection in the event of an error.
> Ensure network connection is closed when handshake with peer fails

- trinity/sync/full/chain.py
Recent logging changes introduced a non-ascii symbol that may cause an exception if it isn't supported.
Using `...` seams like the safer option.
> Replace unicode char with three dots

- eth/db/backends/level.py
- trinity/sync/full/state.py
- trinity/utils/os.py
As described in #1479, currently, with the state sync, it can happen that the caching db consumes too many open file descriptors so that the process exceeds the maximum number of open file descriptors that the OS can handle.
Let the state sync cache db consume only half of the available open file descriptors. This is somewhat expired by what `geth` does but not entirely the same. I didn't feel comfortable copying an approach which wasn't triggered by an immediate need to solve it that way.
The chosen approach here seems simple enough to try out.
> Limit the max open files of state sync cache db

- setup.py
- tests/trinity/integration/test_trinity_cli.py
Trinity attach interaction test did not work properly.
The test attaches to running Trinity and interacts with the console using pexpect module.
Test verifies that the w3 object is available reads network version.
Based on Christoph Burgdorf's [christoph.burgdorf (at) gmail.com] test skeleton.
Fixes: https://github.com/ethereum/py-evm/issues/1472
> test_trinity_cli: Add Trinity attach web3 interaction test.

- trinity/utils/mp.py
I've spent hours lately debugging weird multiprocessing issues that turned out to be caused by the fact that Pythons **default** method to spawn processes on Unix (`fork`) just doesn't work well yet with `asyncio`.
This doesn't seem to be well documented yet but it is [well](https://bugs.python.org/issue21998#msg325820) [known](https://bugs.python.org/issue22087#msg318140) among the Python team. This may be fixed with Python 3.8.
I added a warning at the place where we define `spawn` as our process launch method because every know and then we may wonder why we use `spawn` and attempt to change it. This might save us some painful debugging hours.
> Add warning regarding `fork` and asyncio

- eth/__init__.py
The way the system recursion limit was being set allowed for the recursion limit to end up being lowered.
Adjusted to use a `max` between the desired limit and the current limit.
> Adjust recursion limit setting logic

- eth/chains/base.py
- trinity/chains/light.py
The light client couldn't validate header chains, in sync or async contexts.
Interestingly, it appears that our light sync is not currently running full header validations :(
On the up-side, we will be getting those for "free" in #1392 (which is where this PR was stripped from)
- Move `validate_chain` to a classmethod on the base class
- Inherit `validate_chain` in the light chain
- Add the async call using `async_method("validate_chain")`.
> Support light client header validation during sync

- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
Can't get block body from light peers.
An initialization cycle was introduced by [this line](https://github.com/ethereum/py-evm/commit/75be226ddd2da06066f1c7a3b7fe0e3826e201a9#diff-49f4c2ce3b6081ee05a5a002420f0446R70), which causes `_peer_chain` to be `None` in the `LightDispatchChain`, which prevents the light dispatch chain from making any requests to peers
(Symptom is something like: `None object doesn't have attribute coro_get_block_by_header`)
Always use a full chain instance in the server, even a `LightServer`. It should always be asking for data locally, instead of trying to ask other peers.
> Always use a full chain instance in local server

- README.md
- docs/contributing.rst
- docs/guides/trinity/quickstart.rst
- docs/introduction.rst
Our Readme feels a bit overloaded and it contains information that is better covered in the docs.
- cleaned up Readme
- moved some things into the docs
- fixed some broken links
- updated the introduction texts
Here is how that looks like now:
To be honest, I could be convinced to even go a step further and remove this whole *goals* stuff and just go with a very short intro on Py-EVM and Trinity.
> Simplify and deduplicate README

- docs/guides/trinity/quickstart.rst
The quickstart still used the removed `trinity console` command.
Updated info to use `trinity attach`
Fixes #1525
> Update quickstart to not use obsolete command

- eth/vm/base.py
A receipt with many logs from the same address or with the same topics will end up checking each duplicate against the bloom filter, resulting in many extra `keccak` calls.
Keep track of the values that have already been checked and skip any subsequent duplicates.
> Speed up receipt validation.

- setup.py
- setup_trinity.py
- trinity/__init__.py
- trinity/bootstrap.py
- trinity/main.py
- trinity/main_beacon.py
We currently do not have any bootstrapping for the beacon node.
There are several routes we can take to add maintain an entirely different node type in the same code base.
One pragmatic solution is to maintain multiple main files and expose multiple top level commands
E.g. There would not only be `trinity` but also `trinity-beacon` (name to be discussed).
While this comes with the slight disadvantage of occuping an entirely different command, it gives us the most freedom for experimentation.
Also, it should be relatively straight forward to merge the bootstrapping at a later point in time. So this is just me trying to be pragmatic.
Steps:
1. I moved everything from `main.py` to `bootstrap.py` that I consider generic enough to be useful for any type of program that we want to support in …
> Add support for trinity-beacon command

- tests/trinity/integration/test_plugin_discovery.py
- trinity/bootstrap.py
- trinity/main.py
- trinity/main_beacon.py
- trinity/plugins/registry.py
trinity and trinity-beacon are two different pieces
of software that just share a common code base.
Hence they need to be bootstrapped with different
built-in plugins.
Relates to: #1545
Make `setup_plugins` take an `Iterable[BasePlugin]` and separate the plugins in each bootstrapping code.
> Separate plugins between trinity and trinity-beacon

- eth/vm/logic/system.py
`CREATE2` does not match the spec, [https://eips.ethereum.org/EIPS/eip-1014](EIP-1014).
PR #1181 was therefore failing fixtures.
Use missing gas amount of 32000 (as `CREATE` does); increment nonce.
Source: unknown; found [here](https://gr8poems.blogspot.com/2010/12/two-parrots.html)
> eth/vm/logic/system: fix CREATE2 failures on BadOpcode test fixture

- tests/trinity/core/utils/test_percentile.py
- tests/trinity/core/utils/test_standard_deviation.py
- trinity/protocol/common/managers.py
- trinity/protocol/common/trackers.py
- trinity/sync/full/constants.py
- trinity/utils/percentile.py
- trinity/utils/stddev.py
I wanted to *tune* our timeouts based on historical peer performance.
A simple standard for setting timeouts is to use something like N standard deviations above the Xth percentile for response time.  Under generally *normally* distributed data this should yield a number for which the majority of requests will complete within fine tuned to the peer's historical performance.
- Implemented a percentile tracker which approximates the desired percentile using a constant size memory footprint and added it to the stats that we track about peer performance.
- Implemented a standard deviation tracker which approximates the standard deviation of response times using a constant memory footprint.
- Modified the `trinity.protocol.common.manager.Managers` to take advantage of this data and set the …
> Use 99th percentile and standard deviation to dynamically tune peer timeout

- setup.py
- tests/trinity/conftest.py
- trinity/constants.py
- trinity/plugins/builtin/ethstats/ethstats_service.py
- trinity/plugins/builtin/light_peer_chain_bridge/light_peer_chain_bridge.py
- trinity/rpc/modules/eth.py
- trinity/rpc/modules/net.py
Prior to this change, whenever we made a `request(SomeEvent())` on the `EventBus`, the event traveled out to every connected endpoint(read: different processes) and waited for *someone* to respond.
This is great in a way because it really embraces loose coupling. However, for many request we really know that there should only be one single party to receive the request and give us a response. Spreading these requests across each and every connected process seems like an unnecessary waste of resources. 
For some critical events it could even be considered a security issue as someone could trick people into installing a plugin which listens for specific events and answers them in a malicious way.
With the latest Lahja release the `request` API accepts a `BroadcastConfig` (similar to the …
> Upgrade Lahja and make requests less wasteful

- eth/tools/fixtures/helpers.py
- tests/json-fixtures/test_blockchain.py
Intended to address #1562 
- Instead of failing with "these block hashes do not match", blockchain
tests now fail with "this part of the state tree does not match".
- The tests were inefficient, they first checked that the state hash
matched and then checked that the states matched. It's unlikely the
states will ever not match!
- Some validations needed to be deferred until after state-tree
comparison, or else they would fail the test early with an unhelpful
message.
Failures used to look like this:
```
E       eth_utils.exceptions.ValidationError: Mismatch between block and mined block on 3 fields:
E        - header.state_root  :
E           (actual)  : b"R\xafB',,\xd3\xcb\x8b#W\x98)wL\xc4fLm\x90m\x08\xbb\xed\xc0\x03\x8e\x7f\xfcO:X"
E           (expected): …
```
> Failing blockchain tests now emit a state diff

- eth/tools/fixtures/helpers.py
Instead of emitting expected - actual, emit actual - expected.
Rationale (by @veox):
> For example, as things stand, if a fixture-expected value is 1000, and
> the actual produced by py-evm is 500, the printed message will show a
> delta of 500 - that is, a net positive, whereas what truly happened is
> py-evm having produced a value that's too low. This is confusing: say, a
> miner's account balance showing "Delta: 500" makes one think that the
> miner received 500 wei more than expected (which is not true).
Reference:
- https://github.com/ethereum/py-evm/pull/1181#issuecomment-445986061
- https://github.com/ethereum/py-evm/pull/1573#issuecomment-446404858
> Emit better balance diffs when comparing accounts

- trinity/sync/full/constants.py
Accidentally merged something that should not have been merged in #1553 in the sync constants.
Reverted it.
> Revert unintentional change to sync constant

- trinity/protocol/common/managers.py
Occasionally, during shutdown, the `ResponseCandidateStream` would set an exception on the pending request, only to emit an asyncio "never gathered" exception, due to random service shutdown ordering.
Just before the RCS is garbage collected, cancel any futures that were uncollected.
> Resolve dangling future in ResponseCandidateStream

- eth/beacon/block_committees_info.py
- eth/beacon/helpers.py
- tests/beacon/conftest.py
- tests/beacon/helpers.py
- tests/beacon/test_helpers.py
#1510
- Fix `get_shard_committees_at_slot`
- The reason why I add `_get_shard_committees_at_slot` is for making the tests easier.
- Fix `get_block_hash`
- Add `get_beacon_proposer_index`
- Add `get_attestation_participants`
- Add `get_effective_balance`
- Add `get_new_validator_registry_delta_chain_tip`
Also, make the tests for these functions not depend on genesis state or block.
> Rework helper functions - part 2

- eth/vm/code_stream.py
Nothing really, I actually was curious what numba @jit would do in terms of VM speed on all the function of `arithmetic.py` - it had no effect. Then ended up finding this, and seems to be faster, Interested to find if this is just a margin of error (I gave it x3 runs each) ?
Before:
```
------------------------------------------------------------------------------------------------------------------------------------------------
|       Total       |    389.244     |     12504      |       -        |      9012      |         -          | 2,337,825,400  |       -        |
|        Avg        |     4.990      |      160       |     32.124     |      116       |       23.153       |   29,972,121   | 6,006,064.601  |
============================================================================= …
```
> Just for fun: Minor speedup on CodeStream.

- .circleci/config.yml
- eth/__init__.py
- eth/tools/fixtures/helpers.py
- eth/vm/forks/constantinople/opcodes.py
- eth/vm/logic/system.py
- tests/conftest.py
- tests/json-fixtures/test_blockchain.py
- tests/json-fixtures/test_transactions.py
- tox.ini
`py-evm` doesn't yet pass the full Constantinople test suite.
This started as a copy of PR #1181, so that Christoph doesn't have to act as a gatekeeper for every tiny fix I propose.
Closes #1181 as superseded/conflicting.
The PR updates the upstream `ethereum/tests` (git sub-module in dir `fixtures`), enables tests for Constantinople, and fixes the breaks introduced by that.
NOTE: some test are very slow or consume a lot of memory, making it impossible to pass CI on CircleCI's "open source contributor" tier (the process gets OOM-killed). All of these are in `SLOW_TESTS`. All tests pass locally for me.
Source: [Valdas Augustinas @ efoto.lt](https://www.efoto.lt/node/404410)
> Update ethereum/tests fixtures to v6.0.0-beta.2 + fix revealed consensus failures

- eth/tools/builder/chain/__init__.py
The `mainnet_fork_fns` iterable on the `eth.tools.builder.api` object was incorrectly being wrapped with `staticmethod`.
Removed the wrapper.
> Remove incorrect staticmethod wrapper

- eth/beacon/enums.py
- eth/beacon/enums/signature_domain.py
- eth/beacon/enums/special_record_types.py
- eth/beacon/enums/validator_registry_delta_flags.py
- eth/beacon/enums/validator_status_codes.py
- eth/beacon/helpers.py
- tests/beacon/conftest.py
- tests/beacon/helpers.py
- tests/beacon/test_helpers.py
#1510 part 3
1. Add `get_fork_version` and `get_domain` and tests. Spec: https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#get_fork_version
2. Put `ValidatorStatusCode`, `ValidatorRegistryDeltaFlag`, and `SignatureDomain` in `eth/beacon/enums.py`.
> Add `get_fork_version` and `get_domain` helpers

- tests/trinity/core/configuration/test_trinity_config_object.py
- trinity/bootstrap.py
- trinity/config.py
- trinity/main.py
- trinity/main_beacon.py
- trinity/plugins/builtin/json_rpc/plugin.py
As we aim to support more and more node types using one common `TrinityConfig` becomes seems to become less sustainable as it would mean that e.g. we need to add things for the beacon node into the `TrinityConfig` that will just be noise for other node types. In language theory speak, that would lower the cohesion of the `TrinityConfig`which is a bad thing.
Related discussion: https://github.com/ethereum/py-evm/pull/1556#discussion_r240014047
1.This introduces a concept of sub configurations which need to be derived from `BaseSubConfig`. 
```python
class BaseSubConfig:
def __init__(self, args: argparse.Namespace, base_config: TrinityConfig) -> None:
self.args = args
self.base_config = base_config
```
2. `TrinityConfig.from_parser_args` now accepts an additional `Iterable[BaseSubConfig` to …
> Teach TrinityConfig to handle sub configs

- docs/guides/trinity/writing_plugins.rst
The "Writing Plugins" guide had a module namespace wrong
Changed it from `BaseIsolatedProcessPlugin` to `BaseIsolatedPlugin`
> Correct module namespace in docs guide

- p2p/constants.py
- p2p/discovery.py
- p2p/events.py
- p2p/kademlia.py
- p2p/peer.py
- trinity/nodes/base.py
- trinity/nodes/full.py
- trinity/nodes/light.py
- trinity/plugins/builtin/peer_discovery/plugin.py
- trinity/plugins/registry.py
- trinity/server.py
Currently the peer discovery runs in the networking process among a lot of other things. Moving it into an isolated plugin should:
- increase efficiency of syncing as the peer discovery probably takes a fair share of computing power
- increase decoupling as it breaks up the networking code into smaller pieces 
- improve reusability as the new discovery can be accessed from any other interested party since it is integrated with the event bus 
- inverted the model in the `DiscoveryService` so that it doesn't know about the `PeerPool` and instead just exposes an API for consumers to request peer candidates from
- the API is exposed over the EventBus so that it can be requested from any other process
- created an isolated plugin to run the new discovery service in a separate process
- removed …
> Move peer discovery into an isolated plugin

- tests/trinity/core/utils/test_humanize.py
- trinity/sync/full/chain.py
- trinity/utils/humanize.py
We're likely to write little bits of hash display code here and there. Better to have a common utility.
Inspired by https://github.com/ethereum/py-evm/pull/1392#discussion_r240773225
Decided to keep it super simple by only supporting the long form.
The short form seems just so short to implement, that it's better not to worry about the utility, like:
```py
f"{header.hash[:4].hex()}"
```
I don't feel super strongly though.
_"hash browns"_
> Pretty hash display utility

- tests/trinity/utils/test_ordered_task_preparation.py
- trinity/utils/datastructures.py
Some use cases are totally fine with duplicates in `OrderedTaskPreparation`, but they have a bit of boilerplate to overcome the dups.
Add option to drop duplicates when registering tasks.
> Option to ignore duplicates in OrderedTaskPreparation

- eth/beacon/types/deposit_data.py
- eth/beacon/types/deposit_input.py
- tests/beacon/conftest.py
- tests/beacon/types/test_deposit_data.py
- tests/beacon/types/test_deposit_input.py
- tests/beacon/types/test_deposit_parameters.py
Reflect https://github.com/ethereum/eth2.0-specs/pull/310/
- Rename DepositParameters to DepositInput
- Add a test for DepositData
> Fix #1619, Rename DepositParameters to DepositInput

- trinity/extensibility/plugin.py
While working on #1605 I noticed a wrongly placed `event_bus.stop()`. 
https://github.com/ethereum/py-evm/blob/977a446737569f66ab4c2fb931e3c8417fd16547/trinity/extensibility/plugin.py#L317-L319
The intend of this code is to stop the endpoint for an isolated process but the problem is,  this code runs in the process of the `PluginManager` which is the `main` process.
At best, this just doesn't do anything and at worst it causes weird things.
The real `endpoint.stop()` needs to happen inside the the process of the isolated plugin which in fact every isolated plugin takes care of itself.
E.g. this here
https://github.com/ethereum/py-evm/blob/977a446737569f66ab4c2fb931e3c8417fd16547/trinity/plugins/builtin/json_rpc/plugin.py#L70
boils down to …
> Remove wrongly placed event_bus.stop()

- eth/precompiles/ecadd.py
- eth/precompiles/ecmul.py
- eth/precompiles/ecpairing.py
- eth/precompiles/ecrecover.py
- eth/precompiles/identity.py
- eth/precompiles/modexp.py
- eth/typing.py
- eth/validation.py
- eth/vm/computation.py
- eth/vm/logic/context.py
- eth/vm/logic/logging.py
- eth/vm/logic/memory.py
- eth/vm/logic/sha3.py
- eth/vm/logic/system.py
- eth/vm/memory.py
- eth/vm/message.py
[@veox pointed out](https://github.com/ethereum/py-evm/pull/1588#issuecomment-446986235) that some of the tests use a very large amount of memory. I did some profiling and found the biggest offenders. Here are the top 10, sorted from least to greatest. This number tracks total allocations (from tracemalloc), not maximum size in memory.
```
[static_Call50000_identity_d1g0v0_Byzantium] 2.1G
[static_Call50000_identity2_d1g0v0_Byzantium] 2.1G
[static_Call50000_identity2_d1g0v0_Constantinople] 2.1G
[static_Call50000_rip160_d0g0v0_Byzantium] 2.6G
[static_Call50000_rip160_d0g0v0_Constantinople] 2.7G
[static_Call50000_rip160_d1g0v0_Constantinople] 2.7G
[static_Call50000_rip160_d1g0v0_Byzantium] 2.7G
[static_Call50000_ecrec_d1g0v0_Byzantium] 2.8G
[static_Call50000_ecrec_d1g0v0_Constantinople] 2.8G …
```
> Reduce memory usage of tests

- eth/beacon/aggregation.py
- eth/utils/bls.py
- tests/beacon/test_aggregation.py
- tests/core/bls-utils/test_bls.py
#1565 
1. Follow the logic from [the BLS signature verification
](https://github.com/ethereum/eth2.0-specs/blob/master/specs/bls_verify.md)
2. Replace BN128 with BLS-12-381 curve.
3. Replace the current blake hashing function with keccak-256.
* Please ignore the `eth/beacon/aggregation.py` for now. It's supposed to be updated in other PRs.
* This PR is opened for reviewing the reference implementation. The current CI error is due to other type hinting issues. @carver, feel free to solve that and merge #1576 before it, I'll resolve the conflicts. :)
> Update BLS signature module

- eth/beacon/aggregation.py
- eth/beacon/helpers.py
- eth/beacon/types/blocks.py
- eth/beacon/types/states.py
- eth/beacon/utils/hash.py
- eth/beacon/utils/random.py
- eth/utils/bls.py
- tests/beacon/conftest.py
- tests/beacon/db/test_chaindb.py
- tests/beacon/types/test_states.py
- tests/beacon/utils/test_hash.py
- `hash_` is unclear name for the specific hash that used everywhere in eth2.0
- rename `hash_` to `hash_eth2`
> Fix #1564, rename hash_ to hash_eth2

- eth/beacon/helpers.py
- eth/beacon/types/validator_records.py
- tests/beacon/test_helpers.py
- tests/beacon/types/test_validator_record.py
> Add new beacon helpers and implement tests

- Makefile
- docs/contributing.rst
- scripts/release/test_package.py
#1608 release issues - hard/slow/error-prone to test a local package of a release
Add a new script and `Makefile` target.
Works locally, in fact I think I found a bug that would affect the next release. PR for that will show up tomorrow.
> Add `make package` target to test packaged release

- docs/api/trinity/extensibility/api.extensibility.plugin.rst
- trinity/extensibility/__init__.py
- trinity/extensibility/plugin.py
- trinity/extensibility/plugin_manager.py
- trinity/utils/ipc.py
As described in #1605, in current `master` isolated processes are stopped sequentially with blocking calls. The more we are moving towards a multiprocess architecture, the more this is going to be a problem.
One thing to highlight here is that all our current isolated plugins have their own signal handling logic which means they essentially begin unwinding **before** the `PluginManager` tells them to `stop`. However, that's an implementation detail of these plugins.
Here's a comparison taking down trinity with 8 isolated dummy plugins that **do rely on the `PluginManager`** to tell them to stop.
Current Master:
```
^C    INFO  12-18 20:47:09               trinity  Shutting down Trinity (CTRL+C / Keyboard Interrupt)
INFO  12-18 20:47:09         PluginManager  Shutting down PluginManager …
```
> Ensure isolated plugins are stopped concurrently

- eth/beacon/types/attestations.py
- eth/beacon/types/blocks.py
- eth/beacon/types/deposit_input.py
- eth/beacon/types/exits.py
- eth/beacon/types/proposer_slashings.py
- eth/beacon/types/slashable_vote_data.py
- eth/beacon/types/validator_records.py
#1635
- Update whenever `uint384` is in the spec.
- `get_new_validator_registry_delta_chain_tip` untouched, since it will be replaced with tree hash soon.
> Fix #1635, update pubkey and signature length: `uint256` to `uint384`

- eth/beacon/state_machines/base.py
- eth/beacon/state_machines/state_transitions.py
After https://github.com/ethereum/py-evm/pull/1633 was merged, some imports are broken. This is because all `utils` directories where renamed to `_utils` and #1633 did not rebase on top when it landed. Since it provided **new code** that imported from `utils` git could not identify this possible breakage upfront.
Renamed imports to `_utils`.
> Fix broken imports

- scripts/release/test_package.py
Some exceptions/scenarios would cause the temporary dir to not be deleted.
Found in post-merge #1630 review
Used the `TemporaryDirectory()` context manager.
> Package test: always delete temp dir

- eth/_utils/spoof.py
- eth/estimators/gas.py
- eth/typing.py
- eth/vm/spoof.py
- tests/core/helpers.py
- trinity/rpc/modules/eth.py
The `SpoofTransaction` data type was located in a private namespace.
Move it to a public namespace so that it can be used by 3rd party libraries.
> Move SpoofTransaction out of private namespace

- eth/beacon/deposit_helpers.py
- eth/beacon/helpers.py
- eth/beacon/types/states.py
- eth/beacon/types/validator_records.py
- tests/beacon/conftest.py
- tests/beacon/helpers.py
- tests/beacon/test_deposit_helpers.py
- tests/beacon/test_helpers.py
- tests/beacon/types/test_states.py
- tests/beacon/types/test_validator_record.py
Fixes #1647
Put `ValidatorRecord.balance: int` to `BeaconState.validator_balances: Sequence[int]`.
> Put validator balances into a separate list in the state

- eth/_utils/bitfield.py
- eth/_utils/bls.py
- eth/beacon/aggregation.py
- eth/beacon/constants.py
- eth/beacon/deposit_helpers.py
- eth/beacon/helpers.py
- eth/beacon/state_machines/configs.py
- eth/beacon/state_machines/forks/serenity/configs.py
- eth/beacon/state_machines/validation.py
- eth/beacon/types/attestation_data.py
- eth/beacon/types/attestations.py
- eth/beacon/types/blocks.py
- eth/beacon/types/crosslink_records.py
- eth/beacon/types/deposit_data.py
- eth/beacon/types/deposit_input.py
- eth/beacon/types/exits.py
- eth/beacon/types/fork_data.py
- eth/beacon/types/pending_attestation_records.py
- eth/beacon/types/proposal_signed_data.py
- eth/beacon/types/proposer_slashings.py
- eth/beacon/types/shard_committees.py
- eth/beacon/types/shard_reassignment_records.py
- eth/beacon/types/slashable_vote_data.py
- eth/beacon/types/states.py
- eth/beacon/types/validator_records.py
- eth/beacon/types/validator_registry_delta_block.py
- eth/beacon/typing.py
- tests/beacon/conftest.py
This is an attempt to fix #1383
- Add `NewType`s in `eth/beacon/typing.py`
I added some additional new types:
1. Differentiate signatures in `bytes` and `Tuple[int, int]` form.
```python
BLSSignature = NewType('BLSSignature', bytes)  
BLSSignatureAggregated = NewType('BLSSignatureAggregated', Tuple[int, int]) # Tuple[uint384, uint384]
```
2. Add `Timestamp` and `Second` types.
3. Add a `ValidatorIndex` type.
- Are 5th slot and 5 slots considered same `SlotNumber` type?
- Do we need `uint64` and `uint384` types to differentiate different integers? The purpose is to check the intention of the variable rather than to check integer length or signed/unsigned.
- CommitteeIndex
> Add beacon chain related new type

- eth/beacon/db/chain.py
- eth/beacon/state_machines/base.py
- eth/beacon/state_machines/forks/serenity/blocks.py
- eth/beacon/types/blocks.py
- tests/beacon/conftest.py
- tests/beacon/db/test_beacon_chaindb.py
- tests/beacon/state_machines/forks/test_serenity_operations.py
- tests/beacon/state_machines/test_demo.py
- tests/beacon/state_machines/test_proposer_signature_validation.py
- tests/beacon/test_helpers.py
- tests/beacon/types/test_block.py
Make `StateMachine` better.
1. Add `BeaconBlock` layer between `BaseBeaconBlock` and
`SerenityBeaconBlock`.
- IMO the rule is:
- In `eth.beacon.state_machines.forks.serenity` - use `SerenityBeaconBlock`.
- In type hinting - use `BaseBeaconBlock`.
- In other cases - use `BeaconBlock`.
2. Update `StateMachine.__init__()`
3. Add `BeaconChainDB.block_class` and `BeaconChainDB.set_block_class(block_class)`: now it's forkable.
- TBD: It's for `rlp.decode(block_rlp, sedes=sedes)` with different subclasses of `BaseBeaconBlock`. Now I use set_block_class per `StateMachine` initialization, but I do think it doesn't a beautiful thing to do.
> Update StateMachine.__init__() and add `BeaconBlock`

- eth/beacon/deposit_helpers.py
- eth/beacon/helpers.py
- eth/beacon/types/attestation_data_and_custody_bits.py
- eth/beacon/types/blocks.py
- eth/beacon/types/custody_challenges.py
- eth/beacon/types/custody_reseeds.py
- eth/beacon/types/custody_responses.py
- eth/beacon/types/deposit_input.py
- eth/beacon/types/pending_attestation_records.py
- eth/beacon/types/slashable_vote_data.py
- eth/beacon/types/states.py
- eth/beacon/types/validator_records.py
- tests/beacon/conftest.py
- tests/beacon/helpers.py
- tests/beacon/test_deposit_helpers.py
- tests/beacon/test_helpers.py
- tests/beacon/types/test_attestation_data_and_custody_bit.py
- tests/beacon/types/test_block.py
- tests/beacon/types/test_casper_slashings.py
- tests/beacon/types/test_slashable_vote_data.py
- tests/beacon/types/test_validator_record.py
#1671 part 1: proof of custody placeholders
1. Apply #1671: add proof of custody placeholders 
2. Renamings of https://github.com/ethereum/eth2.0-specs/issues/358 ideas: `poc_` to `custody_`
- `poc_seed_changes` => `custody_reseeds`
- `poc_challenges` => `custody_challenges`
- `poc_responses` => `custody_responses`
- `ProofOfCustodyChallenge` => `CustodyChallenge`
- `poc_commitment` => `custody_commitment`
- `last_poc_change_slot`=> `latest_custody_reseed_slot`
- `second_last_poc_change_slot` => `penultimate_custody_reseed_slot`
-  `aggregate_signature_poc_0_indices` => `custody_bit_0_indices`
- `aggregate_signature_poc_1_indices` => `custody_bit_1_indices`
3. Add `AttestationDataAndCustodyBit` data structure
4. Update `SlashableVoteData.messages`: use `AttestationDataAndCustodyBit`
> Add proof of custody placeholders

- .circleci/config.yml
- tox.ini
Fallout from PR https://github.com/ethereum/py-evm/pull/1577#discussion_r241148668.
CI jobs have `eip150`, `eip158` in their names.
One has to know the numbers refer to hard-forks to understand jobs don't check for kitty support, or the like.
Renamed CI job name (label only).
(Or was the original request to rename it throughout the codebase?..)
Source: thumbnail of a [video on framepool](http://muc1.framepool.com/en/shot/856590910-pribilof-islands-eared-seal-eyes-closed-curiosity)
> CI: rename EIP15{0,8} tox jobs to their long-form fork names.

- eth/_utils/numeric.py
See #1550.
Used `decimal` module of Python to calculate the square root, which is ~4 times faster than the implementation described in Ethereum 2.0 specs.
> Implement fast integer square root

- eth/_utils/blobs.py
- eth/_utils/merkle.py
- eth/beacon/_utils/hash.py
- tests/core/merkle-utils/test_merkle_trees.py
Replace #1674
Fix #1673
It's #1674 without `get_updated_merkle_accumulator`
- Refactor `eth._utils.merkle` APIs
- Add `get_merkle_root`
> Add `get_merkle_root`

- eth/db/chain.py
- eth/tools/fixtures/helpers.py
There were a few instances of docstrings with inconsistent style.
Fixed them.
> Remove last occurrences of apostrophe docstrings

- eth/db/chain.py
- eth/exceptions.py
- tests/database/test_eth1_chaindb.py
The ChainDB API could use the `get_transaction_receipt` method. This function is aimed to get the `Receipt` of the `Transaction` specified by the `Transaction Index` in the block of the provided `BlockHeader`. This function would also be useful to implement the `eth_getTransactionReceipt` JSON RPC function.
The `Transaction Index` is RLP encoded and searched in the `receipt_db` whose root would be present in the `Header`.
> Implement get_transaction_receipt function as part of ChainDB

- eth/tools/builder/chain/builders.py
- tests/core/builder-tools/test_chain_builder.py
Previously the order in which `chain_class_without_seal_validation` would cause `MRO` errors when called on an instance of `NoChainSealValidationMixin` class. (Because `chain_class` is superset of `NoChainSealValidationMixin` class)
The order was changed so that the superset class is added in the front. This prevents the `MRO` errors.
> Change inheritance order for chain_class_without_seal_validation

- eth/_utils/generator.py
- eth/rlp/headers.py
- eth/vm/base.py
- eth/vm/execution_context.py
- eth/vm/state.py
- tests/core/generator-utils/test_cached_iterable.py
- tests/core/generator-utils/test_cached_iteratable.py
Fixes #648 
The `execution_context` variable and also the `ExecutionContext` class now stores the variable `prev_hashes` or `_prev_hases` as a `Generator` object. Even the function `get_prev_hashes` of `eth/vm/base.py` returns a `generator` object instead of `tuple`.
The `Generator` object is converted to tuple only if `get_ancestor_hash` function of `eth/vm/state.py` is called, which is in turn called only by the `BLOCKHASH` opcode functionality.
> Lazily evaluate vm.previous_hashes

- eth/chains/base.py
- eth/db/chain.py
Currently, if we want to implement the `getTransactionReceipt` JSON RPC functionality, then we would have to go all the way to the `ChainDB` part of the `Chain API`. This PR aims to make this functionality available as part of the `Chain API`, so that the convention of JSON RPC implementations using only the Chain API and not the `chaindb` part of the `Chain`, is followed.
The `get_receipt_by_index` of `chaindb` was used in the `Chain API`, so as to abstract the usage.
> Add get_transaction_receipt method to Chain API

- setup.py
A while back we started using `setuptools-markdown` to correctly render markdown files in pypi.  
We just started getting CI failures that seem related to this requirement: https://circleci.com/gh/ethereum/py-evm/126552?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Also, the requirement requires the user to have a system requirement installed (`pandoc`)
Now pypi supports markdown directly so we can remove it 
Emulated this project: https://pypi.org/project/markdown-description-example/
https://pypi.org/project/markdown-description-example/
> Remove pandoc and setuptools markdown requirement

- eth/db/account.py
- eth/vm/code_stream.py
- eth/vm/forks/frontier/state.py
- scripts/benchmark/checks/deploy_dos.py
- scripts/benchmark/checks/erc20_interact.py
- scripts/benchmark/checks/simple_value_transfers.py
- scripts/release/test_package.py
- setup.py
- tests/core/code-stream/test_code_stream.py
- tests/core/stack/test_stack.py
- tests/json-fixtures/test_transactions.py
There are some linting checks that we want like:
- no mutable values for default arguments
- `getattr(x, 'value)` since we can use `x.value` since the attribute string is a constant value
- see more at https://github.com/PyCQA/flake8-bugbear
Added `flake8-bugbear` to the `[lint]` installs.
> Flake8 bugbear

- setup.py
Our live API docs are broken because `pysha` is needed for autodoc to be able to build and extract the docs.
Added pysha as a `docs` dependency.
> Add pysha as dependency for docs

- eth/vm/logic/system.py
`selfdestruct` calls `_selfdestruct` which already does `raise Halt('SELFDESTRUCT')`.
The `raise Halt('SELFDESTRUCT')` in `selfdestruct` is unreachable as a result.
Removed the superfluous `raise Halt` from `selfdestruct`.
`selfdestruct_eip150` and `selfdestruct_eip161` use `_selfdestruct`, hence removed the superfluos code from `selfdestruct` and not  from `_selfdestruct`.
> remove superfluous raise Halt from selfdestruct

- README.md
Change from: 
https://py-evm.readthedocs.io/en/latest/quickstart.html
Change to:
https://py-evm.readthedocs.io/en/latest/guides/quickstart.html
Link was wrong
Changed link
> update Quickstart link

- tests/core/consensus/test_pow_mining.py
- tests/json-fixtures/test_blockchain.py
- The pow tests take an especially long time
- Blockchain tests fail in a surprising way: if a block import succeeds, but with the wrong state, then we only notice when the next block import fails to find its expected parent.
- Shorten pow tests, comment to help understand what reasonable parameters are
- Immediately verify and fail if a single import fails
> Minor testing cleanup

- eth/db/backends/base.py
- eth/db/backends/memory.py
- eth/db/diff.py
- eth/db/journal.py
- tests/database/test_db_diff.py
- tests/database/test_journal_db.py
Wanted an easy way to get access to all pending changes. (for #1735 )
- Added a new `JournalDB.diff()` which reuses the `DBDiff` class used elsewhere to represent a single diff
- Added test that `JournalDB.diff().apply_to(db)` is equivalent to `JournalDB(db).persist()`
- Added a new `DBDiff` equality test to help test its use in the journal
- Added `__iter__` and `__len__` to MemoryDB to enable equality and length checking
Several of these changes seem only a bit related. The final goal was the journal db change, so all the other changes support building and testing that. Still, if you would like me to split it out, I can. It is already split into separate commits, so it will be easy.
> Get access to all the pending JournalDB changes

- eth/db/batch.py
- tests/database/test_batch_db.py
I want to commit queued changes to a target database (specifically, I want to commit changes to an atomic write batch)
Added new `BatchDB.commit_to()` method and tests.
> Commit batch to target db

- scripts/benchmark/checks/deploy_dos.py
- scripts/benchmark/checks/erc20_interact.py
- tests/json-fixtures/test_blockchain.py
Fixes #1733 -- St Petersburg is regularly one of the slowest tests to run
Addresses #1607 -- benchmarking is slow
No reason to think that any slow Constantinople tests are fast in Petersburg, so I just duplicated them all over.
Run duration changed from 8:31 -> 1:43
Benchmark was just sloppily changed while waiting for someone to clean up #1629 . I don't think it's reasonable to shorten the "Simple value transfer" even though it's the biggest offender (2 minutes total). I think the right solution to that is to make it so that we can process more than 10 tx/s X)
Run duration changed from 5:45 -> 2:36
> Skip slowest ConstantinopleFix fixture tests and Benchmarks

- eth/db/journal.py
- tests/database/test_journal_db.py
When storage is deleted, I want a quick way to immediately clear all data, but still be committable/rollback-able as normal. (We didn't have to deal with this before, because we simply calculated and kept *all* intermediate storage states mid-block.)
Now I want to journal the changes, but it wasn't built for the idea of clearing out all underlying data, then rolling that back. So I added `JournalDB.clear()`.
Added `clear()` method and tests.
Also note c8c1643 which fails on master. It seems like this should be the desired behavior: when a key is deleted (but not persisted) then `journal.exists(key)` should return `False`. (Master returns `True`)
> Add JournalDB.clear()

- eth/db/journal.py
- tests/database/test_journal_db.py
We will maintain a list of JournalDB's (one for each active storage slot). 
When we create a JournalDB in the middle of a block, it may not have been keeping up will all previous checkpoints. If an earlier checkpoint is discarded, we can simply reset the entire JournalDB. If an earlier checkpoint is committed, then we want to commit everything but we don't want to persist it.
We could track the first checkpoint seen and commit back to that, but this public API on JournalDB seemed cleaner: Hence the new `squash()`.
It is ideal for a number of reasons to reuse the same checkpoint id for each of the different journals. This makes for a short and sweet checkpoint ID for the whole set of journals.
Added implementations and tests for `JournalDB.squash` and `.record(custom_checkpoint_id)`
> JournalDB.squash() and custom checkpoint ID

- eth/vm/base.py
- eth/vm/forks/byzantium/headers.py
- eth/vm/forks/frontier/headers.py
- eth/vm/forks/homestead/headers.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/test_virtual_machine.py
This makes it easier to inspect data, even if the block transactions are
missing (for example, during light sync or parts of beam sync)
Loading the VM immediately tries to look up the block in the database, but we don't always have the block ready. (Also, it's slower, for cases when we don't need the block)
Lazily generate `vm.block` when it's needed. Often all we need is the header, so make that directly accessible on the VM, and prefer its usage `vm.header` over `vm.block.header`.
> Lazy VM.block generation

- eth/db/batch.py
- tests/database/test_batch_db.py
I have a scenario where I want to delete all intermediate data, but leave the underlying data immutable. (Specifically: adding several items to a trie, which generates a bunch of nodes we don't need)
Unfortunately, that means that in memory, the trie tries to "delete" the old root hash (and other old nodes). We don't have to worry about this getting propagated to the DB, because we use `BatchDB.commit(apply_deletes=False)`. But, sometimes we need to read out of those nodes that we deleted during the process, while we are in the process of reading.
Added a new init flag to `BatchDB` that allows you to read through deletes. If a delete happens in batch, you fall back to getting whatever the wrapped database tells you the value is.
`read_through_deletes` and `apply_deletes` seem heavily …
> Batch db optional read through delete

- eth/db/journal.py
- tests/database/test_journal_db.py
- `KeyError` was being swallowed during `persist()`, which caused some painful debugging
- On any kind of error during `persist()`, `JournalDB` was dropping all its changes on the floor (those that haven't yet been persisted, anyway)
(Pulled from #1735)
- Track whether the wrapped DB has the key, and don't attempt delete if it was already missing (slight performance benefit, too)
- Catch exceptions and rebuild the pending diff of changes so that `persist()` can be reattempted after catching an exception
> JournalDB updates: stop swallowing KeyError & keep diff if persist() errors

- eth/db/account.py
- eth/db/journal.py
- eth/db/storage.py
- eth/rlp/accounts.py
- eth/tools/fixtures/fillers/_utils.py
- eth/vm/state.py
- tests/database/test_account_db.py
- tests/json-fixtures/test_blockchain.py
We are currently calculating storage roots at every storage change.
We need to request state from other nodes at the previous block boundary, even when running the query from in the middle of block execution.
It's also a waste of disk space, and a waste of cycles on `keccak` hashing for the trie reorgs.
- Moved the storage logic out of `AccountDB` into new `StorageDB`
- Set up a similar pipeline, with a special database adapter that looks up storage roots on demand
- The storage db now keeps a journal of changes in their decoded state (slot number and int value) rather than keeping a journal of trie changes.
- Moved the storage API used by VM execution out to `state.set_storage(...)` instead of `state.account_db.set_storage(...)`, which seems like an improvement. Going forward, it lets us …
> Move storage lookups into new StorageDB

- eth/rlp/transactions.py
- tests/json-fixtures/test_transactions.py
A mainnet test previously showed this method took 3.8% of the total
import_block() time. After this change it was 0.5% of the total.
> Cache transaction.get_sender()

- eth/vm/code_stream.py
- tests/core/code-stream/test_code_stream.py
A mainnet test previously showed this method took 7.1% of the total
import_block() time. After this change it was 0.9% of the total.
Importing blocks is too slow.
Started going after some low-hanging fruit. The other things are simple enough to slam together in a single PR, but this optimization is involved enough to isolate for review.
A decent chunk of the time was actually set manipulation (about 20% of that 7.1%). The rest was just the time it took to iterate over all the code and check for validity.
The primary win is probabalistic: often we can tell that an opcode is valid without having to backtrack through all the code, even if we have to make a few hops back to find out for sure. It still takes O(n) to calculate in the …
> CodeStream.is_valid_opcode() speedup

- eth/tools/_utils/normalization.py
- mypy.ini
- tox.ini
Our `mypy` invocation was getting rather lengthy and hence discouraged adding further checks which is bad as we all love to be punished and bow to our `mypy` master as often as we can.
- migrated to `mypy.ini` file
- added more checks and fixed some issues in the process
[//]: # (For important changes, please add a new entry to the release notes file)
[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)
> Migrate to mypy.ini file

- eth/db/journal.py
- tests/database/test_journal_db.py
A tiny refactor to JournalDB. The active part of `commit()` was only ever called by `persist()`, so that logic now lives in `persist()` where it will cause less confusion.
Closes #1762 
This leaves one hole open: If you call `commit()` with the root changeset you'll end up in a bad state. All your data is now lost and calling methods will probably give you exceptions until you call `JournalDB.reset()`. There are a few things we could do here:
1. Ignore the problem. Users shouldn't have access to `root_changeset_id` and in fact trinity never uses it.
2. Change `Journal.commit()` such that this is okay. If you're `Journal.commit()`ing the root changeset then squash changes like before but put them back into the Journal under a new root changeset.
3. Throw a `ValidationError` when the user …
> Separate JournalDB's commit() and persist()

- eth/db/journal.py
A mainnet test previously showed this method took 7.0% of the total
import_block() time. After this change it was 0.6% of the total.
OrderedDict docs say that `__reversed__` is natively supported, so I took a shot at `first(reversed(...keys()))` and that gave a significant speedup.
> JournalDB.latest_id speedup

- eth/vm/computation.py
Shaved off 1.5% of total import_block() time.
- inline some hot code
- avoid some attribute lookups
- appease mypy without an ignore or cast
> Apply computation speedup

- eth/vm/code_stream.py
`CodeStream.__next__()` is called a lot, and is slow
A mainnet test previously showed this method took 5.0% of the total
import_block() time. After this change it was 2.6% of the total.
Removed a couple attribute lookups
> Optimize code stream iteration

- eth/db/account.py
- eth/db/journal.py
- eth/db/slow_journal.py
- eth/db/storage.py
- eth/db/typing.py
- eth/vm/state.py
- tests/database/test_journal_db.py
JournalDB was taking a lot of time to handle the checkpoint/rollback machinery. ~8.3% of the import block timing
Fixes #1775
- Switch from uuid -> int checkpoints
- Switch underlying data structure to a single "latest" data, with dicts for rollback
- Use `__slots__` for faster attribute and method lookups
- Move some validation down from `JournalDB` into `Journal`, where it can often validate almost for free
- Some targeted in-lining
- Don't re-initialize `Journal`, just reset it, which enables...
- Pass through a couple method calls direct from `JournalDB` to `Journal`
(Unfortunately, the neat `@cached_property` trick doesn't work with slots, so this goes back to the `self.method = self.journal.method` approach)
So far, total time spent in journal dropped to 1.4% of the run.
This 6.9% …
> Faster JournalDB committing

- eth/rlp/logs.py
- eth/tools/_utils/hashing.py
- eth/tools/fixtures/fillers/vm.py
- eth/validation.py
- eth/vm/computation.py
- eth/vm/forks/constantinople/storage.py
- eth/vm/logic/arithmetic.py
- eth/vm/logic/block.py
- eth/vm/logic/call.py
- eth/vm/logic/comparison.py
- eth/vm/logic/context.py
- eth/vm/logic/flow.py
- eth/vm/logic/logging.py
- eth/vm/logic/memory.py
- eth/vm/logic/sha3.py
- eth/vm/logic/stack.py
- eth/vm/logic/storage.py
- eth/vm/logic/system.py
- eth/vm/stack.py
- tests/core/opcodes/test_opcodes.py
- tests/core/stack/test_stack.py
- tests/core/validation/test_eth1_validation.py
```
EVM stack push, pop, and dup ~8.9% speedup
Percent of total import_block() time
====================================
In eth/vm/stack.py:
old      new     saved
push  5.99% -> 3.69% = 2.30%
pop   8.63% -> 4.90% = 3.73%
dup   1.76% -> 0.69% = 1.07%
----------------------------------
Total lift             7.1%
In eth/vm/computation.py:
old      new    saved
stack_push  0.98% -> ~0% =  0.98%
stack_pop   0.87% -> ~0% =  0.87%
----------------------------------
Total lift                  1.85%
Tested import_block() against mainnet blocks:
(7620447, 7620450, 7620453, 7620454)
```
(Note: performance measured on top of #1777)
There are a few important changes here:
- switch push and pop to use explicit type signatures, which avoids a lot of dynamic checks
- split out a single pop from …
> EVM stack operation speedup, ~9% speedup

- eth/chains/base.py
- eth/db/account.py
- eth/db/diff.py
- eth/db/hash_trie.py
- eth/db/storage.py
- eth/exceptions.py
- eth/rlp/headers.py
- eth/vm/base.py
- eth/vm/forks/frontier/validation.py
- eth/vm/interrupt.py
- setup.py
- tests/core/opcodes/test_opcodes.py
- tests/core/vm/test_interrupt.py
- tests/database/test_journal_db.py
Beam Sync involves intentionally executing transactions without the full state, including some state that might be necessary to execute. There are currently issues when we fail out of execution in the middle with `MissingTrieNode` (like leaving behind partial state). Also, Beam Sync is if we only learn about the one particular missing trie node. Including data about which account and storage slot are requested speeds things up considerably.
- Add new exceptions in `eth.vm.interrupt`. They are intentionally not in `eth.exceptions` because they are aware of (and import from) other `eth` modules. These are full-blown classes with references back to data, rather than simple exceptions.
- `MissingAccountTrieNode`
- `MissingStorageTrieNode`
- `MissingBytecode`
- Add `HashTrie.squash_changes()`, …
> Exception with more context when trie data missing

- setup.py
This library specifies a dependency on `cryptography` but it doesn't actually appear to be used.
Removed it.
> Remove the cryptography library from dependencies

- .circleci/config.yml
- docs/conf.py
- mypy.ini
- setup.py
- tests/conftest.py
- tox.ini
python3.5 prevents us from using f-strings, native `pathlib.Path()` objects in some places, type annotations, etc. python3.6+ should be available on enough targets, and the most important dependency (trinity) already requires 3.6+.
- Dropped support from pypi classifiers
- Dropped 3.5 tests
- Some test reordering to aim to run the longest tests up-front (to minimize joint test time)
- Update docs links to point to python3.6
- Added py3.7 tests (not really related, just maintenance while touching CI)
> Drop python3.5 support

- eth/tools/builder/chain/__init__.py
- eth/tools/builder/chain/builders.py
- tests/core/builder-tools/test_chain_construction.py
- tests/core/vm/test_rewards.py
`petersburg_at` wasn't exposed in `eth.tools.builder.chain`.
No easy way to use the chain builder to always test the latest VM. (Every network upgrade would require updating the tests explicitly)
Exposed `petersburg_at()` and `latest_mainnet_at()`.
> Expose and test petersburg_at and latest_mainnet_at

- setup.py
It's causing dependency conflicts with other libraries that are
requiring eth-keys <0.3 -- since semver allows breaking changes in minor
releases in a v0 major release, it makes more sense to constrain at the
minor version here.
> eth-keys shouldn't be allowed to minor bump

- eth/chains/base.py
- eth/vm/base.py
- eth/vm/forks/byzantium/headers.py
- eth/vm/forks/frontier/headers.py
- eth/vm/forks/homestead/headers.py
- scripts/benchmark/checks/import_empty_blocks.py
- tests/core/chain-object/test_build_block_incrementally.py
- tests/core/chain-object/test_gas_estimation.py
- tests/core/helpers.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/test_virtual_machine.py
class vm using properties to access and retreive values of block and header
changing from properties to getter and setter methods in files where were requiered.
[//]: # (For important changes, please add a new entry to the running release notes PR)
[//]: # (You can find the current one using: https://github.com/ethereum/py-evm/pulls?q=is%3Aopen+is%3Apr+label%3A%22Release+Notes%22 )
> removed properties from vm.header and block, all tests passed

- eth/abc.py
- eth/estimators/gas.py
- eth/vm/forks/frontier/state.py
- eth/vm/state.py
- newsfragments/1809.removal.rst
- tests/core/vm/test_vm_state.py
When handling missing node exceptions `StateRootNotFound` is an easy one to miss and only comes up very rarely. It's an unnecessary specialization of other exceptions now, IMO.
The exception is an overly-custom version of the MissingTrieNode
exceptions. Just let those bubble up now.
Now `execute_transaction()` is exactly the same as `apply_transaction()`, so
drop the method (and save the method overhead).
> Delete StateRootNotFound, execute_transaction()

- eth/db/chain.py
- newsfragments/1810.bugfix.rst
When a chain reorg's, it tries to remove the canonical transactions from the lookup db. If that chain is header-only, it crashes, because the canonical transactions were never inserted.
Catch and drop the exception if canonical transactions were missing. The point was to delete them, so if they are missing: mission accomplished.
> Bugfix: don't crash on re-org of header-only chain

- eth/abc.py
- eth/chains/base.py
- newsfragments/1821.bugfix.rst
- tests/core/chain-object/test_chain_retrieval_of_vm_class.py
In the refactor to add `eth.abc` the `Chain.get_vm_class` method got lost.
Added it back and added a test for it too.
> Fix missing Chain.get_vm_class method

- setup.py
See #1815 .
Updated `plyvel` dev requirement to `1.1.0`.
> Update dev plyvel requirement

- eth/abc.py
- newsfragments/1822.bugfix.rst
The `ConfigurableAPI.configure` was missing the `@abstractmethod` decorator.
Added the decorator to the function.
> Fix missing abstractmethod decorator on ConfigurableAPI.configure

- README.md
- newsfragments/1827.doc.rst
The Readme still features Trinity which is confusing.
Remove the section about Trinity.
> Remove Trinity from Readme

- eth/precompiles/ecadd.py
- eth/precompiles/ecmul.py
- eth/precompiles/ecpairing.py
- eth/vm/forks/istanbul/computation.py
- eth/vm/forks/istanbul/constants.py
- newsfragments/1819.feature.rst
Fixes #1819
- made the precompiles curry-able
- moved gas price into a keyword argument that defaults to the original byzantium cost
- added modified precompiles to instanbul
> EIP-1108: Reduce EC precompile costs

- eth/db/header.py
- newsfragments/1830.bugfix.rst
- tests/database/test_header_db.py
We recently added support to persist checkpoint headers, in other words, headers, not connected to genesis, persisted with a score that we trust.
However, previously, when we set `persist_checkpoint_header` it did not make that checkpoint header the canonical head.
The feature is used for checkpointed beam sync (https://github.com/ethereum/trinity/pull/921) 
and in a previous version of that PR it didn't mattered if that API call would make the checkpoint header the new canonical head or not.
The reason for that is because eventually a header on top would be persisted with `persist_header_chain(headers, genesis_parent_hash)` and then that would move the canonical head to the latest header.
But with a refactored https://github.com/ethereum/trinity/pull/921 this turned out to be a problem …
> Make checkpoint header the canonical head

- eth/vm/forks/constantinople/storage.py
- eth/vm/logic/storage.py
There is a lot of shared logic between the original 1283 net gas metering, and the new 2200 net gas metering, but not an easy way to reuse it with a few variables updated.
Related to #1825 
Generalized net gas metering logic to accept a gas schedule as an argument.
You can see where this is headed with something like an Istanbul version of:
```py
from eth.exceptions import OutOfGas
from eth.vm.computation import BaseComputation
from eth.vm.forks.constantinople.storage import (
GAS_SCHEDULE_EIP1283,
)
from eth.vm.forks.istanbul import (
constants
)
from eth.vm.logic.storage import (
net_sstore,
)
GAS_SCHEDULE_EIP2200 = GAS_SCHEDULE_EIP1283._replace(base=constants.GAS_SLOAD_EIP1884)
def sstore_eip2200(computation: BaseComputation) -> None:
gas_remaining = computation.get_gas_remaining()
if …
```
> Refactor net gas metering as prep for EIP-2200

- eth/db/chain.py
- newsfragments/1841.doc.rst
- newsfragments/1841.performance.rst
- newsfragments/README.md
- newsfragments/validate_files.py
- pyproject.toml
I was trying out Intel's vtune, and used the "simple value transfer" benchmarks as a target.
Turns out that both the existence check and retrieving the receipt & transfer were expensive, essentially double the work for no benefit.
Look in the receipt and transaction tries once instead of twice.
Checking if a value is present is nearly as much work as getting the
value.
So now, get the value once, and check if it's empty (same as missing).
(Also added a 'performance' type to towncrier)
[//]: # (See: …
> ~20% speedup on "simple value transfer" benchmarks

- eth/vm/forks/istanbul/blocks.py
- eth/vm/forks/istanbul/computation.py
- eth/vm/forks/istanbul/headers.py
- eth/vm/forks/istanbul/opcodes.py
- eth/vm/forks/istanbul/state.py
- eth/vm/forks/istanbul/transactions.py
`Istanbul` was inheriting everything from `Constantinople` instead of `Petersburg`.
This is incorrect as `Istanbul` is a descendant of `Petersburg` and not `Constantinople`.
Made Istanbul inherit from Petersburg instead of Constantinople
> Make Istanbul inherit from Petersburg instead of Constantinople

- newsfragments/1845.feature.rst
- setup.py
From a 3rd party library perspective, all of the values from py-evm are `Any` types.
Expose type information via PEP561
> Expose type data to other packages via PEP561

- eth/abc.py
- eth/chains/base.py
- eth/chains/mainnet/__init__.py
- eth/chains/ropsten/__init__.py
- eth/chains/tester/__init__.py
- eth/constants.py
- eth/rlp/headers.py
- eth/tools/builder/chain/builders.py
- eth/typing.py
- eth/vm/execution_context.py
- eth/vm/forks/frontier/blocks.py
- eth/vm/state.py
- newsfragments/1850.bugfix.rst
fixes #1847
The `eth.constants.GENESIS_BLOCK_NUMBER` was not typed as `eth_typing.BlockNumber`.  Nor were many other variables that should have been `BlockNumber` types.
Updated all the places I could find where block numbers are used and made them into proper `BlockNumber` types.
> More consistent use of BlockNumber type

- eth/vm/chain_context.py
- tests/core/opcodes/test_opcodes.py
There was a suggestion to limit the size of Chain ID to 64 bits, however this was a premature proposal and has since been punted to [EIP-2294](https://GitHub.com/Ethereum/EIPs/issues/2294).
Reverted back to `uint256` validation
> Revert premature optimization for EIP-2294

- newsfragments/1860.bugfix.rst
- setup.py
There's a version conflict on installation because our fixed pluggy version doesn't match the expectations of pytest.
Since, we don't use pluggy directly (it is only a secondary dependency) we can just remove the dependency for now to have it automatically resolve to the required version.
> Remove explicit pluggy dependency

- eth/chains/base.py
- newsfragments/1862.bugfix.rst
This is a fallout from #1855 paving the way to *Clique Consensus*
Py-EVM crashes with an DivideByZero error when `0` is used as a value for `seal_check_random_sample_rate`.
Interpret `0` as not performing any checks. This is symmetric to the current *opposite* behavior of passing `1` to check every single header instead of taking samples.
> Fix crash when using seal_check_random_sample_rate of 0

- eth/abc.py
- eth/rlp/headers.py
- eth/vm/base.py
- eth/vm/execution_context.py
This is a first fall out from #1855 which adds support for *Clique Consensus*.
Currently the `create_execution_context` method is sitting on the `BlockHeader`. The purpose if this method is to create an `ExecutionContext` for the VM to operate on. This defines things such as who is the coinbase. Since Clique repurposes some of the header fields, we need to be able to replace `create_execution_context` with an implementation that fits the scheme.
With the method being implemented on `BlockHeader`, replacing it isn't straight forward. 
1. Move the method from `BlockHeader` to `VM`
2. Change it to be a `staticmethod` and take in the `header`
3. Fix some typing issues that were exposed by this task
> Move create_execution_context from BlockHeader to VM

- eth/abc.py
- eth/vm/base.py
- newsfragments/1864.feature.rst
The validation check for the maximum bytes of the `extra_data` field is currently hardcoded. It needs to be configurable to allow different consensus schemes such as Clique which have a different opinion on the max bytes of this field.
Introduce a `extra_data_max_bytes` class var which defaults to `32` but can be overwritten.
> Make the max bytes of extra_data configurable

- eth/db/account.py
- eth/db/journal.py
- newsfragments/1865.bugfix.rst
- tests/core/vm/test_vm_state.py
Fix #1865 
Two fixes for two different scenarios:
- If creating the storage DB for the first time just to wipe it, then make sure it has the original storage root hash.
- If completely resetting the journal, make sure that any current `clear` (like a storage wipe) gets fully reset (which means it should read through to the underlying if the key is missing from the journal) See more commentary in the PR
> Revert storage after selfdestruct

- eth/vm/forks/istanbul/headers.py
- newsfragments/1877.bugfix.rst
Fixes #1877 
Remove the delay, use the exact same difficulty definition as Constantinople (er, Petersburg).
> Remove ice age delay from Istanbul

- docs/_static/css/custom.css
- docs/conf.py
- newsfragments/1797.doc.rst
- newsfragments/794.doc.rst
This builds on top of #1796 to get the changes into the release notes, too.
Now
Then:
[//]: # (For important changes, please add a new entry to the running release notes PR)
[//]: # (You can find the current one using: https://github.com/ethereum/py-evm/pulls?q=is%3Aopen+is%3Apr+label%3A%22Release+Notes%22 )
> Improve layout of API docs

- docs/api/api.chain.rst
- docs/api/api.db.rst
- docs/api/db/api.db.atomic.rst
- docs/api/db/api.db.batch.rst
- docs/api/db/api.db.cache.rst
- docs/api/db/api.db.diff.rst
- docs/api/db/api.db.header.rst
- docs/api/db/api.db.schema.rst
- docs/api/db/api.db.storage.rst
- docs/api/vm/api.vm.forks.rst
- eth/abc.py
- eth/chains/base.py
- eth/chains/header.py
- eth/db/atomic.py
- eth/db/chain.py
- eth/db/header.py
- eth/db/schema.py
- eth/db/storage.py
- eth/rlp/transactions.py
- eth/vm/base.py
- eth/vm/chain_context.py
- eth/vm/computation.py
- eth/vm/forks/frontier/state.py
- eth/vm/memory.py
- eth/vm/message.py
- eth/vm/opcode.py
- eth/vm/stack.py
- eth/vm/state.py
- eth/vm/transaction_context.py
- newsfragments/1880.doc.rst
Overall doc coverage should be improved before beta
1. Add missing API docs for ``MiningChain``.
2. Add missing API docs for ``eth.db.*``
3. Add missing API docs for ``Constantinople``, ``Petersburg`` and ``Istanbul`` forks
4. Move all docstrings that aren't overly specific to a particular implementation from
the implementation to the interface. This has the effect that the docstring will
appear both on the interface as well as on the implementation except for when the
implementation overwrites the docstring with a more specific descriptions.
[//]: …
> Add some missing API docs and move docstrings from implementation to interface

- eth/abc.py
- eth/db/journal.py
- eth/tools/_utils/slow_code_stream.py
- eth/validation.py
- eth/vm/code_stream.py
- eth/vm/computation.py
- eth/vm/forks/frontier/opcodes.py
- eth/vm/logic/flow.py
- eth/vm/logic/invalid.py
- newsfragments/1882.doc.rst
- tests/core/code-stream/test_code_stream.py
We have a bunch of types in our docs that are lacking docstrings. I believe having at least *some* docstring per public API is the lowest bar of requirement before we can cut a beta.
Added at least **some** docstring for every single public API.
Imperative present tense is being used for the docstrings.
For methods, it should rhyme with **IT WILL:**
Example:
```python
def get_block:
"""
Return the block at the tip of the chain
"""
```
For methods, it should rhyme with **IT IS:**
Example:
```python
class SchemaAPI(ABC):
"""
A class representing a database schema that maps values to lookup keys.
"""
```
[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: …
> Add missing docstrings

- eth/abc.py
- eth/chains/base.py
- newsfragments/1887.feature.rst
Our current APIs do not allow to implement `getTransactionReceipt` in Trinity (without reaching into Py-EVM internals).
That's because the expected response includes information that we can not retrieve if the APIs aren't changed or new APIs are added.
**Exampe response**
```
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"blockHash": "0xf64a12502afc36db3d29931a2148e5d6ddaa883a2a3c968ca2fb293fa9258c68",
"blockNumber": "0x70839",
"contractAddress": null,
"cumulativeGasUsed": "0x75d5",
"from": "0xc80fb22930b303b55df9b89901889126400add38",
"gasUsed": "0x75d5",
"logs": [
{
"address": "0x03fca6077d38dd99d0ce14ba32078bd2cda72d74",
"topics": [
"0x24bcf19562365f6510754002f8d7b818d275886315d29c7aa04785570b97a363"
],
"data": "0x0000000000000000000000000000000000000000000000000000000000000020000000 …
> Add new APIs to allow efficient retrieval of receipts

- docs/_static/js/matomo.js
- docs/conf.py
- newsfragments/1892.doc.rst
Currently we do not have a good insight into our target group. In order to improve both Py-EVM itself and the documentation, it makes sense to aggregate some data.
Add Matomo Tracking to Docs site.
Matomo is an Open Source web analytics platform that allows us
to get better insights and optimize for our audience without
the negative consequences of other compareable platforms.
Read more: https://matomo.org/why-matomo/
> Add matomo tracking to docs site

- eth/vm/base.py
- newsfragments/1889.bugfix.rst
Fix #1889 
If apply_all_transactions is missing data, reraise
> Bugfix: don't resume apply_all_transactions if EVM is missing data

- eth/abc.py
- eth/db/account.py
- eth/db/storage.py
- eth/vm/base.py
- eth/vm/state.py
- newsfragments/1893.bugfix.rst
- tests/core/vm/test_vm_state.py
Currently, because we don't do this, there is a bug in EIP-2200, net gas
metering. When looking up the "original value", the EVM must get the
storage value at the beginning of the transaction, not the beginning of
the block.
Fixes #1893 
So we lock in changes at the beginning of every transaction,
to make sure we don't read values from older transactions, when reading
the original value.
> Lock in storage changes before transaction starts

- eth/db/chain.py
- eth/db/header.py
- eth/tools/_utils/normalization.py
- newsfragments/1891.performance.rst
Breaking this out from #1888, improves performance if the parent of the header being imported is the canonical chain tip. `_find_new_ancestors` is relatively expensive; if I remember right a lot of time is spent fetching and de-serializing the header which was just imported, when all that's wanted is its hash.
> Improve header chain extension performance

- eth/db/storage.py
- newsfragments/1898.bugfix.rst
Fixes: https://github.com/ethereum/trinity/issues/1376
Was trying to delete a storage value that was missing. Other changes made this problem more apparent.
> Only delete (account) storage values if they are present

- setup.py
- tests/core/code-stream/test_code_stream.py
CI is currently broken due to some [hypothesis error](https://circleci.com/gh/ethereum/py-evm/140594?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
1.  Upgraded hypothesis to latest version which resulted in [another error](https://circleci.com/gh/ethereum/py-evm/140612?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
2. Bound some `max_value` in hypothesis tests to `sys.maxsize`
> Update hypothesis to unbreak CI

- eth/chains/goerli/__init__.py
- newsfragments/1904.feature.rst
The `GOERLI_VM_CONFIGURATION` was missing Istanbul support.
Added Istanbul support to `GOERLI_VM_CONFIGURATION`
> Add Istanbul fork to GOERLI_VM_CONFIGURATION

- eth/vm/base.py
- newsfragments/1907.bugfix.rst
There's a logging message printed when the seal check fails that mentions PoW even though that code path could also be running under a different consensus mechanism.
Changed the logging message to be more generic (failed seal check
> Improve logging message for failed seal check

- eth/abc.py
- eth/chains/base.py
- eth/chains/mainnet/__init__.py
- eth/vm/base.py
- newsfragments/1909.removal.rst
- tests/core/vm/test_mainnet_dao_fork.py
`VM.validate_header` recently became an instance method (was a `classmethod` before). The only reason why it became an instance method is because it has an optional seal check and seal checks can only be performed on VM instances.
@carver [suggested](https://github.com/ethereum/trinity/pull/1196#discussion_r364957121) to take the seal check out of this method. I initially was a bit skeptical about that as it comes with the risk of simply forgetting about the check. But in practice, there are few places where we explicitly need to call this and higher level code usually deals with APIs such as `validate_chain` that cover the seal check internally.
So yeah, this PR drops `check_seal` from `validate_header`, makes it a `classmethod` and changes all call sites accordingly.
[//]: # (Stay ahead …
> Drop check_seal support from validate_header

- eth/abc.py
- eth/chains/base.py
- newsfragments/1910.feature.rst
- scripts/benchmark/checks/import_empty_blocks.py
See #1881 
Created the named tuple and used it.
> import_block return refactor

- newsfragments/1911.internal.rst
- tests/core/vm/test_vm.py
We don't have tests that cover `validate_header` directly. ([Related discussion](https://github.com/ethereum/trinity/pull/1196#discussion_r366641218))
1. Added one test that demonstrates that `validate_header` will succeed given that the header is structurally correct even if `validate_seal` will fail on that header.
2. Added one test that demonstrates that `validate_header` will fail if the parent is invalid.
> Add tests for validate_header

- eth/chains/base.py
- eth/db/account.py
- eth/db/storage.py
- newsfragments/1912.bugfix.rst
- tests/core/vm/test_vm_state.py
- tests/database/test_account_db.py
- tests/json-fixtures/test_blockchain.py
Fix #1912 
The bug was: when a previous transaction creates/modifies an account,
and then is "locked", those pending changes are written at the end of the block, even if the
account is deleted is a subsequent transaction.
The fix was: clear out all "locked" storage changes (those made during previous transactions) when you lock in an account deletion.
That fix brought up a new interesting case, where the "dirty" flag wasn't noticing when an account started the block as empty, then some storage was added in one transaction, then in a later transaction it was deleted again. The further solution was to track a history of of storage tries that can be reverted to (a new one added on every account delete), and generously treat the storage as dirty if there were ever any writes in the block, …
> Fix consensus bug from deleting account in same block that creates it

- Makefile
- docs/guides/understanding_the_mining_process.rst
- eth/abc.py
- eth/db/accesslog.py
- eth/db/atomic.py
- eth/db/backends/level.py
- eth/rlp/blocks.py
- eth/tools/mining.py
- newsfragments/1918.internal.rst
- tests/database/test_accesslog.py
- tests/database/test_database_api.py
Wanted an easy way to track all key accesses, for #1917 .
Added new `KeyAccessLoggerDB` (and an atomic database version -- the type checking seems to require both).
Some other bonus tweaks to:
- clean up types
- add some of the block hash to `str(block)`
- speed up the Makefile, etc.
> Add Database for tracking key accesses

- docs/guides/understanding_the_mining_process.rst
- eth/abc.py
- eth/chains/base.py
- eth/db/account.py
- eth/db/storage.py
- eth/db/witness.py
- eth/tools/fixtures/helpers.py
- eth/tools/mining.py
- eth/vm/base.py
- eth/vm/state.py
- newsfragments/1917.feature.rst
- newsfragments/1917.internal.rst
- newsfragments/1918.internal.rst
- setup.py
- tests/core/chain-object/test_chain.py
- tests/core/chain-object/test_chain_get_ancestors.py
- tests/core/chain-object/test_chain_reorganization.py
- tests/core/vm/test_vm.py
- tests/core/vm/test_vm_state.py
- tests/database/test_account_db.py
https://github.com/ethereum/trinity/issues/1225 requires a way to generate information about a witness.
(Note that this is based on #1918 -- I will rebase on master when that gets merged)
Modified `Chain.import_block()` to include another result in `BlockImportResult`, called a `WitnessIndex`.
The `WitnessIndex` includes important information like:
- the hashes of the trie nodes which are accessed while executing a block
- the list of accounts that were accessed while executing a block
- the list of storage slots, for each account, that were accessed while executing a block
- the list of accounts for which we loaded contract bytecode
Note that a `WitnessIndex` is not **the** witness. It doesn't include required information like:
- the bodies of the trie nodes which are accessed while …
> Generate Witness Index while executing a block

- eth/abc.py
- eth/vm/base.py
- eth/vm/computation.py
- eth/vm/forks/frontier/computation.py
- eth/vm/forks/frontier/state.py
- eth/vm/forks/homestead/computation.py
- eth/vm/forks/spurious_dragon/computation.py
- newsfragments/1921.internal.rst
- pytest.ini
- tests/core/opcodes/test_opcodes.py
- tests/core/vm/test_base_computation.py
- tests/json-fixtures/test_virtual_machine.py
Computations are unnecessarily getting created and then thrown away. See:
```
Peteris Erins @Pet3ris Apr 07 08:58
Hi There! I'm noticing that when a contract CALL is issued by py-evm (internal CALL), two new computations are created immediately. Anyone know why is that the case?
49
Op: GAS
[384, 2, 672, 33, 33, 768, 33, 672, 0, 4]
49
Op: CALL
[384, 2, 672, 33, 33, 768, 33, 672, 0, 4, 113796]
New computation started
<eth.vm.forks.constantinople.computation.ConstantinopleComputation object at 0x10d237bd0>
New computation started
<eth.vm.forks.constantinople.computation.ConstantinopleComputation object at 0x10d32c2d0>
50
Op: PUSH2
[]
Peteris Erins @Pet3ris Apr 07 09:07
moreover they both seem to be using the same message computation.msg
Peteris Erins @Pet3ris Apr 07 09:22
one of the …
```
> Convert apply_message to a classmethod

- tests/conftest.py
The `chain_with_block_validation` fixture was set to `NoProofConsensus`. I believe the idea of the fixture is to operate under `PowConsensus`.
Change consensus engine to `PowConsensus`.
> Enable PoW consensus for fully validating chain in test

- eth/abc.py
- eth/db/chain.py
- newsfragments/1925.feature.rst
- tests/conftest.py
- tests/database/test_eth1_chaindb.py
As noted in #1925, currently `persist_block` does not actually persist the transactions and receipts. It relies on the side effect of block *execution*  to save these.
- Added a new API `persist_unexecuted_block` which takes in an additional `receipts` parameter
- Improved docs to better distinguish when to use which API  
- Added tests that prove `persist_block` does not properly persist transactions and receipts whereas `persist_unexecuted_block` does.
> Ensure persist_block persists tx and receipts

- eth/db/storage.py
- eth/vm/interrupt.py
- newsfragments/1935.internal.rst
- setup.py
Need to support new py-trie API to eventually use trie tools to help with state backfill in trinity.
Upgrade and see what's what.
Looks like only exceptions are affected. So upgrading should be pretty smooth.
> Upgrade py-trie to v2 alpha 1

- eth/db/chain.py
- eth/db/chain_gaps.py
- eth/db/header.py
- eth/db/schema.py
- eth/exceptions.py
- newsfragments/1929.bugfix.rst
- tests/database/test_header_db.py
Fix #1928
Fix #1929 
Use hypothesis data draws to make aggressive assertions about headers becoming canonical, no matter what order they are inserted. I think Piper is interested in the state machine approach, which may be superior. _(maybe so, but this one is done, and worked pretty well!)_
There was a lot more hiding under the hood here than I expected. Looks like it's all working now. I'm not 100% confident because I had to manually deal with changing header difficulty, but it's certainly an improvement!
I had to explicitly mark which headers are canonical (we could no longer assume that the end of a gap is the beginning of a checkpoint, because of the way we de-canonicalize headers, and insert a gap, if a header doesn't match an adjacent checkpoint).
[//]: # (Stay ahead of things, add …
> Handle a lot more scenarios of filling header gaps, created by checkpoints

- eth/abc.py
- eth/db/chain.py
- eth/exceptions.py
- eth/vm/forks/frontier/blocks.py
- newsfragments/1943.feature.rst
- tests/database/test_eth1_chaindb.py
Having py-trie make `MissingTrieNode` stop subclassing `KeyError` exposed an awkwardness mentioned here in trinity:
https://github.com/ethereum/trinity/blob/e40aac0ab2a9a2e7a703af0b94fafd1047ce6e55/trinity/sync/beam/chain.py#L330-L331
The exception story for loading a block body was pretty messy.
To be clear, Trinity breaks if you upgrade to py-trie v2a1 without this change (although it still requires a change to catch the `BlockNotFound`, but that's an improvement).
Raise a `BlockNotFound` if the transactions or uncles are missing.
Bonus change: bring back a performance boost when persisting a trie (using a batch write).
[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained …
> Raise BlockNotFound on missing txns or uncles

- setup.py
`TraversedPartialPath` was incorrectly raised on leaf nodes that didn't match. Also, the "recovery" mechanism for traversing from sub_segments of the partially traversed node was broken.
Upgrade to new py-trie:
https://github.com/ethereum/py-trie/blob/e3889c54013125d0f664fbfa6a4dea4bc85e67a6/CHANGELOG#L6-L45
Plan to use the new `TraversedPartialPath.simulated_node` feature. (Although I think it doesn't really come into play directly in py-evm, just trinity).
I hope this upgrade is entirely uneventful... :crossed_fingers: 
[//]: # (See: …
> Upgrade py-trie, which has a fixed TraversedPartialPath

- eth/db/chain.py
- eth/db/schema.py
- eth/tools/builder/chain/builders.py
- newsfragments/1947.feature.rst
- newsfragments/1947.internal.rst
- tests/core/builder-tools/test_chain_builder.py
- tests/database/test_eth1_chaindb.py
Similar to how we track gaps in the chain of headers, we also need to track gaps in the chain of blocks.
1. Taught `mine_blocks` of chain builer tools to accept a `transactions` argument to make it easier to write tests where blocks are mined with transactions
2. Track gaps in `persist_block` (similar but simpler to header gap tracking)
3. Overwrite `_update_header_chain_gaps` in `ChainDB` to hook into the `HeaderDB` gap tracking to react to cases where an uncle header gets replaced and should trigger an update to the block gap tracking.
[//]: # …
> Track gaps in the chain of blocks

- eth/_utils/datatypes.py
- eth/_utils/headers.py
- eth/_utils/transactions.py
- eth/abc.py
- eth/chains/base.py
- eth/chains/tester/__init__.py
- eth/consensus/clique/_utils.py
- eth/db/chain.py
- eth/rlp/accounts.py
- eth/rlp/blocks.py
- eth/rlp/headers.py
- eth/rlp/logs.py
- eth/rlp/receipts.py
- eth/rlp/transactions.py
- eth/tools/fixtures/helpers.py
- eth/vm/base.py
- eth/vm/forks/byzantium/__init__.py
- eth/vm/forks/frontier/__init__.py
- eth/vm/forks/frontier/blocks.py
- eth/vm/forks/frontier/headers.py
- eth/vm/forks/homestead/headers.py
- newsfragments/1948.internal.rst
- setup.py
Currently, any method that expects any of `BaseHeaderAPI`, `BaseBlockAPI`, `UnsignedTransactionAPI`, `ReceiptAPI` does not properly enforce type safe. In practice that means that a method such as:
```python
def do_something_with_block(block: BlockAPI):`
...
```
Can be called as `do_something_with_block(accidential_is_transaction)` or `do_something_with_block(accidential_is_header)` and mypy does not complain about it.
This has allowed serious bugs to fly under the radar: https://github.com/ethereum/trinity/pull/1830 
The root cause for this is that anything derived from `rlp.Serializable` will be seen as `Any` by mypy. We currently do not enforce this to be invalid but if so, mypy would rightfully reject a series of types:
```
$ mypy -p eth --config-file mypy.ini 
eth/vm/interrupt.py:28: …
```
> Tighten type support and fix typing issues

- eth/vm/forks/frontier/blocks.py
- newsfragments/1949.removal.rst
Looks like the `add_uncle` API on blocks is not used anywhere.
Removed dead API.
> Remove unused add_uncle API

- eth/abc.py
- eth/chains/base.py
- eth/vm/base.py
- newsfragments/1950.feature.rst
No convenient way to report progress in the middle of `apply_all_transactions` (the longest step of `import_block`).
See https://github.com/ethereum/trinity/pull/1916/files#r458190667
- Added a new `VirtualMachineAPI.transaction_applied_hook()`
- In the hook, supply a header that includes the expected amount of gas to be used by the full block. This allows for things like monitoring the progress of the block in between transactions if they are slow. Executing transactions can be very slow in Beam Sync, for example.
We have to explicitly annotate the header used to generate the VM with the gas used by the final header in order to do that last step.
[//]: # (For important changes that should go into the release notes please add a …
> Call a new hook when a transaction is applied

- newsfragments/1951.performance.rst
- setup.py
Nothing wrong but Py-RLP shipped a new version that uses a rust based backend to speed up decoding/encoding. 
We can clearly observe the performance gains for Py-EVM.
Current:
```
Starting benchmark: Simple value transfer
Sending to existing address
------------------------------------------------------------------------------------------------------------------------------------------------
|        VM         | total seconds  |    total tx    |  tx / second   |  total blocks  |  blocks / second   |   total gas    |  gas / second  |
------------------------------------------------------------------------------------------------------------------------------------------------
|     frontier      |     5.738      |      142       |     24.749     |       1        |       0.174        | …
```
> Upgrade Py-RLP to see if anything breaks.

- setup.py
The current py-trie doesn't support the latest py-rlp that py-evm was upgraded to. Not sure why #1951 looked fine pre-merge. :/
Released a py-trie that supports the latest py-rlp.
> Upgrade py-trie for v2 rlp support

- eth/abc.py
- eth/chains/base.py
- eth/tools/builder/chain/builders.py
- eth/tools/factories/transaction.py
- eth/vm/base.py
- newsfragments/1967.performance.rst
- scripts/benchmark/checks/erc20_interact.py
- scripts/benchmark/checks/simple_value_transfers.py
- tests/core/chain-object/test_chain.py
- tests/core/vm/test_rewards.py
- tests/core/vm/test_vm_state.py
Benchmarks were showing up as really slow (300 kgas/sec for simple value transfer, 3.3 Mgas/sec for ERC20 transfer).
The mining chain was significantly slowed down, by doing a bunch of state work in between each transaction (storing all the state to disk, etc). By batching all the transactions together before sealing the block, we see significant speedups. (7 Mgas/sec for simple value transfer, 5.5 Mgas/sec for ERC20 transfer)
Overall, the benchmark run dropped from 3m1s to 1m43s, and that's with doubling the number of simple value transfers and running 5x as many ERC20 transactions.
[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: …
> Benchmarks: Mine transactions in a batch to show real import speed

- eth/vm/forks/berlin/__init__.py
- eth/vm/forks/berlin/blocks.py
- eth/vm/forks/berlin/computation.py
- eth/vm/forks/berlin/headers.py
- eth/vm/forks/berlin/opcodes.py
- eth/vm/forks/berlin/state.py
- eth/vm/forks/berlin/transactions.py
Isolating the Berlin fork boilerplate from the BLS precompile code in #1933 
Dropped the commits
> Implement Berlin fork stub

- .circleci/config.yml
- eth/tools/fixtures/helpers.py
- eth/vm/forks/__init__.py
- newsfragments/1971.internal.rst
- pytest.ini
- setup.py
- tests/json-fixtures/test_blockchain.py
- tox.ini
Need the new tests for Berlin
Update the ethereum/tests repo
> Upgrade ethereum/tests to v7.0.1

- eth/vm/base.py
- newsfragments/1979.bugfix.rst
- tests/json-fixtures/test_blockchain.py
The uncle header may not have the same timestamp as its parent. I ignored the test at first due to https://github.com/ethereum/tests/issues/787 - but it turns out the test is correct.
Update the inequality, and stop ignoring the valid test.
> Fix uncle timestamp check against its parent

- eth/abc.py
- eth/chains/base.py
- eth/db/chain.py
- eth/exceptions.py
- eth/rlp/blocks.py
- eth/rlp/transactions.py
- eth/vm/base.py
- eth/vm/forks/berlin/blocks.py
- eth/vm/forks/berlin/transactions.py
- eth/vm/forks/byzantium/blocks.py
- eth/vm/forks/constantinople/blocks.py
- eth/vm/forks/frontier/blocks.py
- eth/vm/forks/frontier/transactions.py
- eth/vm/forks/homestead/blocks.py
- eth/vm/forks/istanbul/blocks.py
- eth/vm/forks/muir_glacier/blocks.py
- eth/vm/forks/petersburg/blocks.py
- eth/vm/forks/spurious_dragon/blocks.py
- newsfragments/1973.feature.rst
- tests/core/transaction-utils/test_transaction_encoding.py
- tests/database/test_eth1_chaindb.py
- tests/json-fixtures/test_transactions.py
Fixes #1973 
Uses the basic structure from https://github.com/ethereum/pyrlp/pull/131 to enable dynamic encodings. It kicks the can down the road a bit to #1975 for actually supported any specific typed transactions, since they aren't defined until then.
Had to split the transaction responsibility up a bit: isolated a transaction builder/serializer from the actual transaction API. It causes some code churn, but not quite as much as I feared.
> Add typed transactions - EIP 2718 - Berlin

- docs/guides/building_an_app_that_uses_pyevm.rst
* OS: macOS 11.2.2
* Python Version (python --version): Python 3.6.13
1. Guide Doc [building_an_app_that_uses_pyevm](https://py-evm.readthedocs.io/en/latest/guides/building_an_app_that_uses_pyevm.html#add-the-py-evm-library-as-a-dependency) is outdated, py-evm old version `0.2.0a40` causes script below to fail.
> chain.get_vm().state.get_balance(MOCK_ADDRESS)
2. "Edit on GitHub" link redirects to 404 page.
> https://py-evm.readthedocs.io/en/latest/guides/building_an_app_that_uses_pyevm.html
Update py-evm in doc to the latest version "py-evm==0.3.0a20"
https://github.com/ethereum/py-evm/blob/master/docs/guides/building_an_app_that_uses_pyevm.rst
> Fixed: Outdated py-evm version in Guide Doc - #1983

- newsfragments/1987.internal.rst
Tests were running against ethereum/tests v7. 
Updated the commit hash in the fixtures directory!
> Update ethereum/tests to v8.0.1

- .circleci/config.yml
- eth/_utils/rlp.py
- eth/tools/rlp.py
- newsfragments/1991.internal.rst
- pytest.ini
- tests/json-fixtures/blockchain/test_blockchain.py
- tox.ini
Need to run Berlin tests #1991
(Can't close the issue until #1988 and maybe other modexp issues are solved)
When #1988 is resolved, remove the `-k "not modexp"`. (Presumably in a different PR, depending on merge order)
> Run Berlin ethethereum/tests, except for modexp-related ones

- eth/precompiles/modexp.py
- eth/vm/forks/berlin/computation.py
- tox.ini
Modexp wasn't being calculated quite correctly. 
Removed reuse of `compute_adjusted_exponent_length`, and made a new method called `calculate_iteration_count` that's pulled pretty much verbatim from [EIP-2565](https://eips.ethereum.org/EIPS/eip-2565).
> Calculate modexp gas fee correctly EIP-2565

- eth/abc.py
- eth/chains/base.py
- eth/db/chain.py
- newsfragments/1994.bugfix.rst
- tests/core/chain-object/test_chain.py
There was a bug when loading a the receipt from the chain object. (and apparently no test for it!)
Added a test, fixed the bug.
Note that the `ChainDB` uses the keyword `receipt_decoder` instead of `receipt_builder` (and the same for `transaction_decoder`), because it *only* uses the "decode from bytestring" API. It doesn't use the full RLP serialize/deserialize functionality.
> Fix get receipt from chain

- eth/abc.py
- eth/rlp/transactions.py
- eth/vm/forks/berlin/transactions.py
- newsfragments/1996.feature.rst
The most obvious way to determine if transactions are typed is an `isinstance` call. 
Just expose a `type_id` on all transactions instead.
> Make type_id accessible on all transactions

- eth/abc.py
- eth/rlp/transactions.py
- newsfragments/1997.feature.rst
Type-checking complains about accessing `v` on legacy transactions.
Add an API that a transaction can be cast to, if `type_id` is `None`.
> Add v to special legacy transaction API

- .circleci/config.yml
- newsfragments/1999.feature.rst
- newsfragments/1999.misc.rst
- setup.py
- tox.ini
Web3py needs blake2b-py>=0.1.4 to support python 3.9. It looks like the only libraries that require py-evm are Trinity and eth-tester, so I'm hopeful that the impacts of updating this will be minimal.
Updated blake2b-py dep to >=0.1.4.
> Update blake2b-py version requirement

- eth/abc.py
- eth/vm/forks/london/computation.py
- eth/vm/forks/london/opcodes.py
- eth/vm/forks/london/state.py
- eth/vm/logic/block.py
- eth/vm/mnemonics.py
- eth/vm/opcode_values.py
- eth/vm/state.py
- newsfragments/2015.feature.rst
- tests/core/opcodes/test_opcodes.py
The BASEFEE opcode for London hadn't been implemented yet. 
Added it! 
> London basefee opcode 0x48

- eth/precompiles/blake2.py
- setup.py
fixes: #1959
may fix: #1941
Used the native implementation of blake2b compression function if `blake2b-py` is not installed.
Made `blake2b-py` an optional dependency via `eth-extra`.
> fix: make blake2b optional

- eth/tools/_utils/normalization.py
- eth/tools/fixtures/helpers.py
- eth/vm/forks/london/headers.py
- newsfragments/2022.internal.rst
- tests/json-fixtures/blockchain/test_blockchain.py
When enabling London tests, some basic missing/broken functionality showed up.
> Preliminary london fixups

- docs/guides/building_an_app_that_uses_pyevm.rst
- docs/guides/quickstart.rst
Hi!
When trying to install `py-evm` following the quick start guide I noticed that pip 9 (the default version installed by `apt install python3-pip` on Ubuntu 18.04) fails to install `blake2b-py` version 0.1.4. This is probably because the wheel for that version of `blake2b-py` is tagged as `manylinux2010`, whose support was introduced in PEP 571/pip 19.0.
```
ftruzzi@thinkpad:~/projects/ethereum/py-evm$ python3.8 -m venv .venv
ftruzzi@thinkpad:~/projects/ethereum/py-evm$ source .venv/bin/activate
ftruzzi@thinkpad:~/projects/ethereum/py-evm$ pip install .
Processing /home/ftruzzi/projects/ethereum/py-evm
Collecting blake2b-py<0.2,>=0.1.4 (from py-evm==0.4.0a4)
Could not find a version that satisfies the requirement blake2b-py<0.2,>=0.1.4 (from py-evm==0.4.0a4) (from versions: 0.1.2, …
```
> Add step to quick start guide to update pip

- eth/vm/computation.py
- eth/vm/logic/system.py
- newsfragments/2023.bugfix.rst
- tests/core/vm/test_base_computation.py
- tests/core/vm/test_computation.py
- tests/core/vm/test_london.py
1. We did not reset return data on CREATE or CREATE2 calls for an insufficient funds case.
2. We also never reset return data on exceptions that have `erases_return_data` flag set to `True`. Some tests that were in place to test this did not test it appropriately.
1. Erase return data and error log when insufficient funds or stack depth limit reached during CREATE or CREATE2.
2. Check the `erases_return_data` flag on the raised exception and erase the return data in the same way that we burn gas when the `burns_gas` flag is set to `True`.
[//]: # …
> Erase return data on appropriate exceptions

- eth/vm/forks/london/computation.py
- eth/vm/forks/spurious_dragon/computation.py
- tests/core/vm/test_london.py
- LondonComputation was raising an error where it should set the error and return the computation. This fixes broken ethereum tests related to this new logic from EIP-3541.
- Ethereum tests released a new version (v10.0)
- Set the `computation.error` and return the computation rather than raise the VMError
- Updated ethereum tests submodule to new version v10.0
> EIP-3541 london test fixes

- .circleci/config.yml
- docs/guides/quickstart.rst
- docs/guides/understanding_the_mining_process.rst
- eth/_utils/headers.py
- eth/_utils/rlp.py
- eth/tools/_utils/normalization.py
- eth/validation.py
- eth/vm/base.py
- eth/vm/logic/system.py
- newsfragments/2017.feature.rst
- newsfragments/2021.bugfix.rst
- newsfragments/2021.doc.rst
- tests/core/vm/test_london.py
- tests/core/vm/test_vm.py
- tests/json-fixtures/blockchain/test_blockchain.py
- tox.ini
> Run London fork tests

- docs/guides/building_an_app_that_uses_pyevm.rst
- newsfragments/2032.doc.rst
Project templates URL in https://github.com/ethereum/py-evm/blob/master/docs/guides/building_an_app_that_uses_pyevm.rst was redirecting to https://github.com/carver/ethereum-python-project-template.
Fixes #2032 
I changed the URL to https://github.com/ethereum/ethereum-python-project-template and also changed the location in the git clone command accordingly.
> Reference to the project template in the docs updated

- .circleci/config.yml
- eth/tools/_utils/normalization.py
- newsfragments/2040.misc.rst
- setup.py
- tests/json-fixtures/test_transactions.py
- tox.ini
ethereum/tests submodule needed an update.
Changed the commit to point at the right version. Fixes: #2039 
> Update test fixtures to v10.1

- setup.py
With the updated dependencies, we couldn't update the tester dependency of web3py to the latest py-evm without breaking it. We need to wait until web3py has a v6 beta release to do that. 
Reverted most of the dependency updates for now. I will pull them back in once we're ready to cut our web3py v6 branch soon. 
Released a new v2.3.0 `eth-typing` that had the enum for the `London` and `ArrowGlacier` fork names, which are needed for the update of `ethereum/tests` to v10.1. Also released a v0.3.4 of `eth-keys` which has the bugfix for the ecrecover point at infinity.
[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: …
> Downgrade dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- eth/vm/forks/arrow_glacier/blocks.py
- newsfragments/2047.bugfix.rst
- tests/core/vm/test_vm.py
- Arrow Glacier block serialization was not properly set up to inherit from London block header.
- Arrow Glacier block header should now be set up properly by actually using the `ArrowGlacierBlockHeader` 😅 .
- Test added to try to catch copy / paste issues like these in the future.
> Arrow glacier block header serialization fix

- newsfragments/2068.removal.rst
- setup.py
I should have released 0.5.0-b.2 as 0.6.0-b.1. So this ports the dependency upgrades from 0.5.0-b.2 to master so that we can cut a new 0.6.0-b.1 release.
Upgraded dependencies, added python 3.10 support. 
> Upgrade dependencies

- .circleci/config.yml
- .readthedocs.yml
- docs/conf.py
- eth/_utils/version.py
- eth/abc.py
- eth/vm/base.py
- eth/vm/forks/frontier/__init__.py
- eth/vm/forks/homestead/__init__.py
- eth/vm/forks/spurious_dragon/__init__.py
- newsfragments/2070.removal.rst
- setup.py
- tests/core/helpers.py
- tox.ini
Python 3.6 is no longer supported, so dropping here. 
Removed CI runs, and updated any runs using 3.6 to use Python 3.9 now.
> Drop Python 3.6

- newsfragments/2078.misc.rst
- tests/json-fixtures/blockchain/test_blockchain.py
Update `ethereum/tests` submodule to ``v11.1`` [commit hash](https://github.com/ethereum/tests/releases/tag/v11.1)
> Update ethereum/tests to v11.1 commit hash

- .circleci/config.yml
- newsfragments/2082.misc.rst
The updated circleci images can't find tox under `~/.local/bin/tox`
Changed invocation to: `python -m tox -r`
> Invoke tox differently in CI

- newsfragments/2085.misc.rst
- setup.py
- Breaking ``importlib-metadata`` dependency issues with python version below ``3.8``
- Pin version to ``<5`` for python versions below ``3.8``
> Pin ``importlib-metadata`` dependency to ``<5`` to allow py37 builds to run

- docs/guides/understanding_the_mining_process.rst
- eth/vm/forks/byzantium/headers.py
- eth/vm/forks/homestead/headers.py
- newsfragments/2084.bugfix.rst
- tests/core/consensus/test_pow_mining.py
- tests/json-fixtures/blockchain/test_blockchain.py
Related to #2075 
- Difficulty calculation was taking into account the parent ``difficulty`` which would slip below the ``DIFFICULTY_MINIMUM`` value if the parent ``difficulty`` was less than the allowed minimum. 
- Take the max only between the difficulty calculation and the _actual_ minimum allowed value.
> Address failing tests from ethereum/tests ``v11.1``

- .circleci/config.yml
- newsfragments/2087.internal.rst
- OpenSSL 3 removed ripemd160 functions from the default behavior. Instead they now have to be locally configured. This broke a lot of blockchain related logic and they decided to add it back in in version 3.0.7, see blog post [here](https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider/).
- CircleCI is using openssl3 but not (yet?) the latest version. Since this breaks tests even on `master`, which were previously passing, we need to update the config for now until the newer open ssl version is used in the circleci images.
- For now, updating the openssl config just works™ and we can ideally remove it when the images are updated.
- Config changes suggested, among other places, [here](https://github.com/openssl/openssl/issues/16994#issuecomment-963669325)
> Update OpenSSL Config for ripemd160

- newsfragments/2090.misc.rst
- setup.py
- tox.ini
To get dependencies to resolve, we need to remove the upper pin on eth-bloom.
Removed pin per our current philosophy. I will remove other pins in a separate PR. 
> Remove upper pin on eth-bloom

- .circleci/config.yml
- newsfragments/2102.internal.rst
- `virtualenv` versions seem to be clashing across sys and user libraries. CircleCI images come with `virtualenv` installed at the sys level and when we did `pip install --user tox` we installed `tox` and a different `virtualenv` version there at the user package level. I believe the `--user` flag was causing issues with the different `virtualenv` installs. By installing `tox` at the sys level, it allows us to work with the existing `virtualenv` version already in the image. Whether the `tox` version chooses to update it or not is left to its dependency setup.
- Also, ``--upgrade`` the ``pip`` version sitting in the image python install before any of the above steps.
> Update pip and virtualenv for CI builds

- Makefile
- setup.py
- tox.ini
Imports are not sorted.
Related to Issue https://github.com/ethereum/py-evm/issues/2094
Added `isort`, a tool to sort imports, in the linting process.
Adding lint setup + linting files would be a large PR to review. I've decided to split it up into two parts. 
```mermaid
flowchart LR
pr1[Added isort to setup, makefile and tox - This PR] --> pr2[Linted file with isort in eth and tests directory]
pr2 --> pr3[Add isort check to tox]
```
In this PR, I've added `isort` and related commands to `setup.py`, `Makefile` and `tox`. 
In the follow up PR, I will be running `make lint-roll`. It will be easier for repo maintainers to checksum the changes and review the lint changes. 
Let me know if I missed anything in the contribution process.
> [1/3] Added isort to setup, makefile and tox

- eth/vm/forks/shanghai/blocks.py
- newsfragments/2105.bugfix.rst
- tests/core/vm/test_vm_class_configurations.py
- `ShanghaiBlock` class was missing a receipt builder. This is not directly used in PyEVM but is used by `eth-tester`. Since `ShanghaiBlock` is the first time we've had to re-build from `BaseBlock` since the `__init__()` adds a new field, this was the first time in a while we were vulnerable to missing a configuration on the class. Since it wasn't directly tested here, we missed it.
- Add the `LondonReceiptBuilder` to the `ShanghaiBlock` class since that's the latest version of the receipt builder (the last time a typed transaction was introduced was the type=2 transaction via EIP-1559, London).
- Add basic testing around Block class configuration to make sure each is wired up with the expected configuration classes.
> Bugfix: Add receipt builder to ShanghaiBlock

- newsfragments/2108.internal.rst
- tests/json-fixtures/blockchain/test_blockchain.py
- tox.ini
- The latest release of ``ethereum/tests`` moves EOF to Cancun, which will be moved again to Prague since 4844 took precedence in Cacun. Either way, Shanghai tests no longer have EOF so we can remove the ``-k "not EOF"`` flag from the Shanghai tests
> Update ``ethereum/tests`` and turn on all Shanghai tests

- newsfragments/2111.internal.rst
- tests/json-fixtures/test_transactions.py
Since Berlin, the way we handle decoding isn't as straightforward as passing the encoded bytes object to rlp.decode using the class as the sedes. Properly handling decoding by directly calling the ``decode()`` method of the transaction builder classes (Berlin and above) is the best way to decode from bytes in a way that accounts for similar behavior across all fork Transaction / TransactionBuilder classes.
Closes #2075
> Properly decode all transaction test cases

- .circleci/config.yml
- .readthedocs.yml
- eth/abc.py
- eth/db/__init__.py
- eth/db/chain.py
- eth/tools/_utils/deprecation.py
- eth/tools/db/atomic.py
- eth/tools/fixtures/fillers/common.py
- newsfragments/2113.internal.rst
- newsfragments/README.md
- newsfragments/validate_files.py
- pyproject.toml
- scripts/benchmark/checks/deploy_dos.py
- scripts/benchmark/checks/erc20_interact.py
- scripts/benchmark/checks/import_empty_blocks.py
- scripts/benchmark/checks/mine_empty_blocks.py
- scripts/benchmark/checks/simple_value_transfers.py
- setup.py
- tests/core/consensus/test_clique_utils.py
- tests/database/test_leveldb_db_backend.py
- tox.ini
Lint dependencies were not bumped in the template update
`tox.ini` and `setup.py`could use some cleanup
bumped version for flake8, flake8-bugbear, mypy
bumped tox version and cleaned up `tox.ini` and 'setup.py`
set docs build to template standard
> bump versions for lint, cleanup setup.py and tox.ini, docs ci

- eth/vm/code_stream.py
- newsfragments/2109.bugfix.rst
`pc` was used in the `__slots__` list, but `program_counter` was used throughout the rest of the `CodeStream` class.
Closes #2109 
Changed slot `pc` to `program_counter`.
Quick `timeit` tests showed ~25% faster access to `program_counter` :tada:
> update CodeStream slot name pc to program_counter

- eth/abc.py
> fix doc typo for `validate_block` function

- eth/_utils/headers.py
- newsfragments/2119.bugfix.rst
utcnow() returns a local time, which for computers in any time zone besides utc will result in an eth_now() value being shifted forwards or backwards by the distance from utc.
Related to Issue #
Closes Issue #
> fix eth_now()

- eth/_utils/numeric.py
- eth/abc.py
- eth/vm/code_stream.py
- eth/vm/forks/berlin/opcodes.py
- eth/vm/forks/london/opcodes.py
- eth/vm/logic/duplication.py
- eth/vm/logic/stack.py
- eth/vm/logic/swap.py
- eth/vm/memory.py
- eth/vm/opcode.py
- eth/vm/stack.py
- newsfragments/2076.performance.rst
grab bag of optimizations. profiling (using pypy as the runtime) showed that hotspots included
- `functools.__call__` (presumably from `functools.partial` and `functools.wraps`)
- `apply_computation`
- `expand_memory`
- stack operations
to that end, I applied the following optimizations
- write more inlineable wrappers for DUP/SWAP/PUSH instructions
- write more inlineable ceil_XX implementations, replace with branchless implementation
- optimize the Stack data structure. instead of using List[type, value], simply use List[value] (as the type is tagged in the python runtime anyways)
- optimize apply_computation event loop
- remove usage of CodeStream iterator, inline pc logic
- remove `__enter__` and `__exit__`, replace with inlined try/finally
- a minor peephole optimization in …
> feat: improve py-evm performance

- .circleci/config.yml
- tests/json-fixtures/blockchain/test_blockchain.py
- tox.ini
- Update `ethereum/tests` (fixtures submodule) to latest release, `v13`
- Add cancun test run to `tox.ini` but silence it in circleci config for now since everything will be failing
This PR is meant to be tested as a test run but we should be able to merge into the base branch before starting implementation on separate EIP PRs
> Add cancun tests; silence for now

- eth/vm/forks/cancun/blocks.py
- eth/vm/header.py
- This gets us to the 20 expected fields in the cancun block headers without actually implementing any of the logic involved in those EIPs. What this does is it allows for the tests to run past where the header field check fails for each and every test. Now, when we implement the EIP logic, we will get more specific errors like expected hashes or values not matching, etc, until the tests pass / the logic is correctly implemented.
> Update Cancun header to include new fields

- eth/vm/forks/paris/blocks.py
- eth/vm/forks/shanghai/blocks.py
- `Paris` network and above still defined a `MiningHeader` class which isn't necessary.
- Remove the concept of a pre-mining header post-merge by removing the `MiningHeader` class beginning with the `Paris` network upgrade.
- Raise when trying to call `block.mining_hash`, post `Paris` network upgrade.
> Drop the concept of pre-mining header post merge

- eth/tools/_utils/normalization.py
- newsfragments/2136.bugfix.rst
- newsfragments/2136.internal.rst
- tests/json-fixtures/blockchain/test_blockchain.py
- There are some new tests under the PySpecs directory that we should turn on.
- Update test fixture to use the latest, `v13`
- Turn on the pyspec tests and address failing tests:
- We can accept `type==0` as legacy transactions
- Handle expected failures based on transaction type
These changes are better addressed separately but they are necessary for passing the cancun branch
> Turn on pyspec generated tests

- .circleci/config.yml
- 2137.internal.rst
- Makefile
- docs/Makefile
- docs/guides/index.rst
- docs/guides/installation.rst
- docs/index.rst
- docs/introduction.rst
- tox.ini
Build on RTD has been failing, but only when a PR is merged into `main`. In our own docs testing, we only test building the html version of the docs, but for several months now we've had RTD building html, pdf, and epub versions for almost all our libs. It seems like there hasn't been an issue, but in this case the html docs build fine but the epub build fails.
Created a new `validate-docs-ci` make command, which will build pdf and epub only as part of CI. Tried changing it so all docs building builds all 3 formats, but the local reqs for building `latexpdf` are hefty. 
Fix issues with epub build by restructuring the introduction and guides so that the `quickstart.rst` (now `installation.rst` is only included once.
Updated `docs/Makefile` to template version(not sure why that didn't …
> Create CI-only docs builds for additional formats, update docs Makefile, add deletion of unused autogen docs

- eth/abc.py
- eth/vm/computation.py
- eth/vm/logic/call.py
- newsfragments/2140.breaking.rst
this commit modifies `msg.data` so that it is an immutable `bytes` copy of the input. the issue is that right now it is a view of memory, which means the caller can trample the msg.data buffer after the call returns (and `msg.data` gets mutated). this is not necessarily a problem for the VM correctness, but it is an issue for integrators that inspect `msg.data` after a call, because `msg.data` will not retain its original value.
as a refactor, since `Computation.memory_read()` is completely dead (and more importantly, probably a footgun), this commit also removes `memory_read()` from the `ComputationAPI` interface as well as the `Computation` implementation.
Related to Issue #
Closes #
> fix: msg.data mutability

- .circleci/config.yml
- eth/tools/fixtures/helpers.py
- newsfragments/2149.internal.rst
- tests/json-fixtures/blockchain/test_blockchain.py
- tests/json-fixtures/test_transactions.py
- tox.ini
- Update *ethereum/tests* to `v13.1`
- "Merge" was correctly updated to "Paris" in this version -> relevant changes included.
- Some new tests are failing. Issue created to address them #2150.
Note: This PR will be important to catch all the updated cancun tests for testing the `cancun-network-upgrade` branch.
> Update ethereum tests to v13.1

- eth/tools/builder/chain/builders.py
- eth/tools/fixtures/helpers.py
- eth/vm/forks/cancun/headers.py
- newsfragments/2156.bugfix.rst
- tox.ini
New transition tests no longer live under `/BlockchainTests/TransitionTests/...` and so we didn't catch any Shanghai to Cancun tests. This PR turns those on and more properly addresses transition test setup dealing with a timestamp by introducing helper functions to set them up properly.
- Address issues at Shanghai -> Cancun transition.
- Add helpers for testing transition tests at timestamp.
- Fix the keywords for CI transition tests since they no longer live in ``/TransitionTests``.
prompt: `snakes transitioning from the Shanghai city life to a life in Cancun with a sign that says "Cancun"`
> Turn on Cancun transition tests and address issues

- eth/_utils/spoof.py
- eth/tools/_utils/normalization.py
- eth/tools/fixtures/generation.py
- eth/tools/fixtures/loading.py
- eth/vm/forks/__init__.py
- eth/vm/forks/cancun/state.py
- newsfragments/2157.bugfix.rst
- newsfragments/2157.internal.rst
- tests/core/transaction-utils/test_spoof_transaction.py
- tests/json-fixtures/test_transactions.py
- A `SpoofTransaction` is usually used to turn an unsigned transaction into a "signed" transaction for estimating gas for example. *eth-tester* uses `SpoofTransaction` for these purposes and we need to make sure that it also accounts for a `type_id` which is a part of the `SignedTransactionAPI`.
- Quite a few transaction tests can be pulled in from general state tests.
- Add proper `type_id` values to `SpoofTransaction` since it should use all attributes from the `SignedTransactionAPI`.
- Pull in transaction tests from some general state tests
prompt: `iterate on 'snakes transitioning from the Shanghai city life to a life in Cancun with a sign that says "Cancun"' but make 'transactions' a theme`
> Use some general state tests as transaction tests; Ensure txn `type_id`

- eth/abc.py
- eth/vm/forks/cancun/state.py
- eth/vm/state.py
- eth/vm/transient_storage.py
- newsfragments/2159.bugfix.rst
in chain.estimate_gas(), the chain creates a snapshot, applies a transaction, then reverts the snapshot. the issue with this is applying a transaction creates a new JournalDB inside of the transient storage, so the checkpoint from the snapshot is no longer valid as soon as apply_transaction() is called. this commit cleans the transient storage db by calling JournalDB.clear() so that the checkpoint from the snapshot is still valid.
Related to Issue #
Closes #
> fix: cancun transaction executor

- eth/vm/base.py
- eth/vm/forks/cancun/__init__.py
- newsfragments/2165.bugfix.rst
- This is a minor change that is nice to have but also necessary for full *web3.py* <-> *eth-tester* <-> *py-evm* support in order to update fields that are meant to be coming from the consensus layer.
*Bonus: Instead of just copying the messages from the EIP, provider values in the error message when the calculated `blob_gas_used` doesn't match the block header blob gas used. This kind of helped track this down but also is just a nicety :)*
- Use the current vm's header to check fields got `vm.pack_block()`
> Update block fields check to use current vm's block header

- eth/vm/forks/cancun/blocks.py
- newsfragments/2166.bugfix.rst
Having plugged *web3.py* (via PR ethereum/web3.py#3332) through *eth-tester* (via ethereum/eth-tester#285), these seem to be that last few changes to fully support Cancun across the stack.
- We are incorrectly not using the `CancunReceiptBuilder` for `CancunBlock`
> bugfix: use CancunReceiptBuilder in CancunBlock

- eth/vm/forks/cancun/state.py
- newsfragments/2168.bugfix.rst
- ``integer.to_bytes()`` requires size and byteorder below py311 and our fixture tests only use py311.
- Compare the first byte of versioned hashes by indexing instead.
> Compare the first versioned hash byte by indexing

- eth/db/keymap.py
- newsfragments/2116.bugfix.rst
- tests/core/db/test_keymap_db.py
KeyMapDB would segfault on deepcopy, due to recursion in `__getattr__`
`0_o`
> fix: make KeyMapDB deep-copiable

- MANIFEST.in
- newsfragments/2170.internal.rst
- setup.py
Error importing when using pytest due to `scripts` being included as a package.
Exclude `scripts` when building the wheel (setup.py)
Include `scripts` for the distribution (MANIFEST.in)
> Exclude `scripts` from wheels

- .circleci/config.yml
- eth/validation.py
- newsfragments/2171.feature.rst
- setup.py
- tests/database/test_eth1_chaindb.py
- tests/database/test_header_db.py
- tests/database/test_journal_db.py
- tox.ini
closes #2169 
- Add relevant Python 3.12 CI runs, copy the new windows CI setup from the template.
- Bump `hypothesis` to `>6,<7` (this is only for `tests` install extra, should be OK / non-breaking)
- Silence some minor warnings related to new hypothesis version. When `@given()` is used with a function-scoped fixture, it doesn't re-generate the values at the function level. I think this is OK for the tests that had this issue but double check to make sure I didn't miss anything.
- Use an `int` (`10**18`) instead of a `float` (`10e18`) for `random.randint()` as it now raises an exception.
> Add python 3.12 support

- Makefile
- newsfragments/2172.bugfix.rst
- setup.py
scripts was getting installed as a package because we added a `scripts/__init__.py`, but it really shouldn't be a package. 
Removed `scripts/__init__.py`, and made sure it wasn't getting included in the wheel. It is still getting included in the source dist.
> Remove scripts/__init__.py, don't include scripts dir in sdist

- docs/Makefile
- newsfragments/2174.internal.rst
`make build-docs` (which calls `make docs clean`) was failing because we took out the `scripts/__init__.py` and it couldn't find the scripts files to rm. 
Now we remove the scripts directory before the doc build on `make docs clean`
> Remove scripts dir instead of scripts module

- .circleci/config.yml
- docs/guides/understanding_the_mining_process.rst
- newsfragments/2175.internal.rst
`docs` CI was only installing dependencies and exiting.
Added the missing steps to the CI run.
> Fix Docs CI

- eth/vm/forks/prague/transactions.py
- newsfragments/2211.bugfix.rst
- tests/core/transactions/test_transaction_builder.py
- `PragueTransactionBuilder.new_set_code_transaction()` should return a `PragueTypedTransaction` filled in appropriately with the transaction type and inner transaction.
- As we did with `new_unsigned_set_code_transaction`, open up the types to accept dictionary auths in the auth list and fill in `Authorization` classes via the method.
- Return `PragueTypedTransaction`
- Accept dict auths in the auth list for `new_set_code_transaction`
> `PragueTransactionBuilder` is not building a `PragueTypedTransaction` as expected
