ethereum/py-evm

evm/__init__.py, evm/logic/block.py, evm/logic/call.py, evm/logic/system.py, evm/rlp/blocks.py, evm/utils/blocks.py, evm/validation.py, evm/vm/__init__.py, evm/vm/base.py, evm/vm/computation.py, evm/vm/evm.py, evm/vm/flavors/__init__.py, evm/vm/flavors/frontier/__init__.py, evm/vm/flavors/frontier/blocks.py, evm/vm/flavors/frontier/headers.py, evm/vm/flavors/homestead/__init__.py, evm/vm/flavors/mainnet/__init__.py, pytest.ini, tests/core/validation/test_validate_evm_block_ranges.py, tests/json-fixtures/test_blockchain.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_vm.py
Some naming conventions have been adjusting as development progresses and some of the APIs are starting to become clearer.  Time for a big cleanup.
Work in progress.
=> Naming convention and API cleanup

.travis.yml, evm/exceptions.py, evm/rlp/headers.py, evm/utils/blocks.py, evm/utils/fixture_tests.py, evm/utils/rlp.py, evm/utils/state.py, evm/utils/transactions.py, evm/vm/base.py, evm/vm/flavors/frontier/__init__.py, evm/vm/flavors/frontier/blocks.py, evm/vm/flavors/frontier/headers.py, evm/vm/flavors/frontier/validation.py, evm/vm/flavors/homestead/validation.py, evm/vm/flavors/mainnet/__init__.py, tests/json-fixtures/test_blockchain.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_transactions.py
During work on the blockchain fixtures, there was a bit of API cleanup that happened.  This was cluttering up the branch that the blockchain fixtures are being worked on soo....
Extracted the pieces that are just cleanup.
=> API cleanup prior to starting JSON Blockchain tests

evm/consensus/pow.py
Before this change we'd re-generate it every time check_pow() was
called, but now we keep a cache of caches and only generated a new one
when needed.
Run time for the fast blockchain tests:
Before: ====================== 246 passed, 2 deselected in 400.65 seconds
After: ====================== 246 passed, 2 deselected in 50.84 seconds
=> Avoid unnecessarily regenerating the ethash cache in check_pow()

evm/vm/evm.py
=> Reduce number of places where we overwrite EVM.header

MANIFEST.in
Package did not have a manifest file, caused installation issues.
Added a `MANIFEST.in` file.
=> add MANIFEST.in file

evm/chain.py, evm/db/__init__.py, evm/ecc/__init__.py, evm/exceptions.py, evm/vm/base.py, evm/vm/flavors/__init__.py, evm/vm/flavors/mainnet/__init__.py, evm/vm/memory.py, evm/vm/message.py, evm/vm/stack.py, tests/coincurve-ecc/test_coincurve_ecc_backend.py, tests/core/evm/test_evm.py, tests/json-fixtures/test_blockchain.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_transactions.py, tests/json-fixtures/test_vm.py
I broke  `master` and there were still some EVM/Chain renamings necessary.
Did them.
=> Rename all EVM occurances to Chain

evm/vm/flavors/eip150/opcodes.py, evm/vm/flavors/frontier/__init__.py, evm/vm/flavors/homestead/opcodes.py, tests/core/utils/test_blocks.py
This PR unit tests `evm/utils/blocks.py` and is created in response to issue #40
=> Add unit tests to evm/utils/blocks

evm/chain.py, evm/ecc/backends/coincurve.py, evm/validation.py, setup.py, tests/coincurve-ecc/test_coincurve_ecc_backend.py, tests/core/chain-object/test_chain_retrieval_of_vm_class.py, tests/json-fixtures/test_blockchain.py, tox.ini
There were a few extra cleanups remaining after the EVM to Chain rename
Cleaned them up
=> cleanup after rename of EVM to Chain

tests/core/stack/test_stack.py
No unit tests for stack object.
Wrote unit tests for stack object.
=> Write tests for stack object

.travis.yml, evm/db/__init__.py, evm/db/backends/level.py, setup.py, tests/level-db/test_leveldb_db_backend.py, tox.ini
Creates and tests leveldb backend in response to issues #33 
@pipermerriam I'm not to happy with how I'm implementing the snapshot and revert functionality but after reading the docs of multiple dbs it seems like the best way (leveldb and rockdb both takes snapshots that are read-only which is why I have to manually enter the information when reverting).
=> Create and test leveldb backend

tests/core/memory/test_memory.py
No unit tests for memory object.
Wrote unit tests for memory object.
=> Write unit tests for memory object

tests/core/code-stream/test_code_stream.py
No unit tests for CodeStream object.
Wrote unit tests for CodeStream object.
=> Write code-stream object unit tests

tests/core/vm/test_computation.py
Creates unit tests for `Computation` class in response to #54
=> Create unit tests for Computation 

tests/core/padding-utils/test_padding.py
padding.py needed unit tests
Added tests to padding.py
=> Padding unit test

evm/p2p/kademlia.py, evm/p2p/test_kademlia.py
Replaces: https://github.com/gsalgado/py-evm/pull/4
=> Binary search

evm/p2p/auth.py, evm/p2p/constants.py, evm/p2p/exceptions.py, evm/p2p/les.py, evm/p2p/p2p_proto.py, evm/p2p/peer.py, evm/p2p/protocol.py, evm/p2p/test_auth.py, evm/p2p/utils.py
Those together will perform the auth dance and exchange a hello packet with the remote, for a full handshake.
=> Implement auth.handshake() and Peer

evm/p2p/les.py, evm/p2p/p2p_proto.py, evm/p2p/peer.py, evm/p2p/protocol.py, evm/p2p/test_auth.py, evm/p2p/test_peer.py
=> Perform P2P protocol matching when the hello msg is received

evm/p2p/kademlia.py, evm/p2p/test_kademlia.py
It was broken by https://github.com/pipermerriam/py-evm/pull/102/files#diff-a3c95f408ab1e088005660c33f5de2f2R222
=> Fix RoutingTable.remove_node

.travis.yml, tox.ini
I mucked up the CI runs in my rebasing of the spurious dragon fork rules PR
Fixed it.
=> Fix CI muckup

evm/p2p/exceptions.py, evm/p2p/p2p_proto.py, evm/p2p/peer.py, evm/p2p/protocol.py, evm/p2p/test_peer.py, evm/p2p/utils.py
I've been running a script that uses multiple Peers connected to different mainnet
remotes, all fetching headers and sharing a single chaindb, and that uncovered a
few issues which I'm fixing here.
=> Some fixes to the Peer code

tests/core/vm/test_computation.py
The tests for the upcoming `REVERT` opcode were not compatible with the current way that the `Computation` object was being tested.
Removed the `create_error` helper function in favor of explicitly triggering the error in each test.
=> Refactor computation tests

tests/json-fixtures/test_blockchain.py, tests/json-fixtures/test_state.py
The way that some of the fixture tests were written needed some minor tweaks to be ready for byzantium.
Changed how the test configuration is done.
=> Fixture tests refactor

.github/PULL_REQUEST_TEMPLATE.md
To reduce cute animal image friction
* People unfamiliar with github markdown might not know how to add an image.
* Doing much more than copying in a URL is probably too much work for people. Even when cute animals are at stake.
Added template and instructions for how to create animal pic
Low friction animal:
=> Improve animal pic template

evm/chains/chain.py, evm/logic/call.py, evm/vm/base.py, evm/vm/computation.py, evm/vm/forks/frontier/__init__.py, evm/vm/gas_meter.py
A long time ago I tried to add some optimizations by nesting all logging statements in an `if` statement.  This has not been done consistently and currently, we never use these objects without a logger.
Removed the nested if statements.
=> Refactor if statements out of logging

evm/vm/forks/frontier/blocks.py
Byzantium needs to create block receipts in a different manner than previous fork rules.  To do this it needs a hook for modifying receipt creation.
Added a new `make_receipt` API to the block object.
=> Refactor block receipt creation into dedicated method

evm/exceptions.py, evm/logic/call.py, evm/logic/system.py, evm/vm/computation.py, evm/vm/forks/byzantium/blocks.py, evm/vm/forks/frontier/__init__.py, evm/vm/forks/homestead/__init__.py, evm/vm/forks/spurious_dragon/__init__.py, evm/vm/forks/spurious_dragon/utils.py, tests/core/chain-object/test_chain.py, tests/core/vm/test_computation.py, tests/core/vm/test_vm.py, tests/json-fixtures/test_virtual_machine.py
Issue #164 
- added `should_burn_gas` to Computation and used throughout where applicable
- added `should_erase_return_data` to Computation and used throughout where applicable
- change `VMError` and `Revert` attribute `zeros_return_data`  to `erases_return_data`
=> [Issue #164] gas and return data helpers for Computation

evm/p2p/test_lightchain.py, evm/p2p/test_peer.py
Also refactor some helper methods and add docstrings to make the tests
easier to follow.
=> Move LightChain-related tests out of test_peer.py

README.md
#180 
Added note about `--recursive` flag to README
=> Note required --recursive flag when cloning

requirements-docs.txt
Documentation wasn't building
Fixed RTD configuration and dependency that wasn't parsing.
=> update sphinxcontrib-asyncio dependency declaration

evm/p2p/conftest.py, evm/p2p/les.py, evm/p2p/lightchain.py, evm/p2p/test_lightchain.py, evm/p2p/test_lightchain_integration.py, evm/rlp/transactions.py
Also includes an integration test (skipped by default) that runs a LightChain connected to a local geth instance to test header syncing and block/contract/receipts/proof retrieval.
=> p2p: Implement most of the remaining LES commands

evm/chains/chain.py, evm/rpc/format.py, evm/rpc/modules/eth.py, tests/rpc/test_rpc_fixtures.py
#178 
Get individual transactions and uncles, and their respective counts.
=> RPC: get individual transactions, uncles, and their counts

evm/lightchain_shell.py
It was crashing because `Chain.__init__()` expects the DB to always have the genesis block.
=> Fix lightchain_shell to work with an empty DB

evm/vm/vm_state.py, setup.py, tests/core/vm/test_state_access_restrictions.py, tests/database/test_account_state_db.py
The recent rebase of the `sharding` branch onto master had a lot of merge conflicts.  There were breakages because these that needed to be fixed.
Run tests, fix things, repeat
=> Check to see sharding branch is working.

setup.py
Fixes #253 
Something broke with the older version of cytoolz
Upgraded to `>=0.9.0,<1.0.0`
=> bump cytoolz version

evm/p2p/eth.py, evm/p2p/les.py, evm/p2p/lightchain.py, evm/p2p/peer.py, evm/p2p/protocol.py, evm/p2p/sedes.py, evm/p2p/test_lightchain_integration.py
It doesn't belong in lightchain.py
=> Move PeerPool to peer.py

evm/chains/chain.py, evm/db/chain.py, evm/rlp/headers.py, evm/vm/base.py, evm/vm/forks/byzantium/vm_state.py, evm/vm/forks/frontier/__init__.py, evm/vm/forks/frontier/vm_state.py, evm/vm/forks/homestead/vm_state.py, evm/vm/forks/spurious_dragon/vm_state.py, evm/vm_state.py, tests/core/chain-object/test_chain.py, tests/core/vm/test_vm_state.py
=> Remove `is_stateless` flag

docs/building_chains.rst
Docs updated to reflect moving of constants
=> this seems to have changed

.travis.yml, tox.ini
Tests in `tests/auxiliary` are not run on Travis.
=> Run auxiliary tests on Travis

evm/p2p/lightchain.py, evm/p2p/peer.py
That way LightChain doesn't have any knowledge of implementation details of LESPeer
=> p2p: Move all code that deals with waiting for LES replies to LESPeer

setup.py
=> Use latest eth-utils

evm/vm/base.py, evm/vm_state.py, tests/json-fixtures/test_virtual_machine.py
=> Add VM function to execute raw bytecode

evm/computation.py, evm/logic/call.py, evm/logic/context.py, evm/logic/system.py, evm/transaction_context.py, evm/vm/forks/frontier/computation.py, evm/vm/forks/frontier/transaction_context.py, evm/vm/forks/frontier/vm_state.py, evm/vm/forks/sharding/computation.py, evm/vm/forks/sharding/transaction_context.py, evm/vm/forks/sharding/vm_state.py, evm/vm/forks/spurious_dragon/utils.py, evm/vm/message.py, evm/vm_state.py, tests/auxiliary/user-account/test_contract.py, tests/core/message-object/test_message_object.py, tests/core/vm/test_base_computation.py, tests/core/vm/test_frontier_computation.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_virtual_machine.py
Cf. #262, and #327 where this was added to master.
Creating a PR to track this work in progress.
=> Add transaction-context object

evm/db/chain.py, evm/p2p/peer.py, requirements-dev.txt, tests/rpc/conftest.py
There were some small cleanup changes that have accumulated in the trinity branch.
Moved them to this PR in their own branch.
=> Backport changes from trinity branch to master

evm/logic/context.py, evm/logic/memory.py, evm/logic/stack.py, evm/utils/address.py, evm/utils/padding.py, tests/core/padding-utils/test_padding.py
I tried to adress #388 but I'm still very much a Python noob (in fact, this is my first contribution to a Python project ever)
@pipermerriam I hope I refactored it the way you had it in mind. I first wasn't sure about the curried functions but think it turned out well (again, bloody Python noob here!).
=> Refactor pad utilities to use Python internals (#388)

docs/building_chains.rst
the documentation available at http://py-evm.readthedocs.io/en/latest/building_chains.html is out of sync with the source code on how to setup a LightChain
Documentation was updated providing instructions that work with the actual codebase
=> DOC: building-chains: syncing documentation with source code

README.md
I came across [someone asking](https://gitter.im/ethereum/py-evm?at=5a90f5e9c3c5f8b90dfadd03) about the bigger picture / roadmap of the project.
While I'm not in the position to provide a detailed answer to that, I recently had @pipermerriam answer some related questions on [gitter for me](https://gitter.im/ethereum/py-evm?at=5a78a1fea3447aac75455bf1) and thought I try to compile it into a Readme update.
=> Fine tune Readme to provide more info

evm/logic/call.py, evm/logic/context.py, evm/logic/storage.py, evm/logic/system.py, evm/vm/forks/frontier/computation.py, evm/vm/forks/frontier/validation.py, evm/vm/forks/frontier/vm_state.py, evm/vm/forks/homestead/computation.py, evm/vm/forks/homestead/headers.py, evm/vm/forks/spurious_dragon/computation.py, evm/vm/forks/spurious_dragon/vm_state.py, evm/vm_state.py, tests/core/chain-object/test_chain.py, tests/core/helpers.py, tests/core/vm/test_frontier_computation.py, tests/core/vm/test_vm.py, tests/core/vm/test_vm_state.py, tests/json-fixtures/test_blockchain.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_virtual_machine.py, trinity/rpc/modules/eth.py
Turn `state_db(read_only=True)` and `state_db(read_only=False)` into `read_only_state_db` and `mutable_state_db` property respectively.
=> Add read only state db property

p2p/cancel_token.py, p2p/chain.py, p2p/lightchain.py, p2p/peer.py, p2p/protocol.py, tests/p2p/test_cancel_token.py, tox.ini, trinity/chains/__init__.py
For now it only fetches headers, but has hooks in place for triggering the download of block bodies and receipts as well.
Plenty of TODOs and FIXMEs as well, so not sure if we want to merge this into master or in a separate branch
=> p2p: Implement first cut of ChainSyncer

trinity/utils/chains.py, trinity/utils/db.py, trinity/utils/filesystem.py, trinity/utils/ipc.py, trinity/utils/logging.py, trinity/utils/xdg.py
Related to #386 this PR brings type annotations for trinity/utils to kick things off.
=>  Type Annotations for Trinity/utils

evm/chains/__init__.py, evm/chains/chain.py, evm/chains/mainnet/__init__.py, evm/chains/ropsten/__init__.py, evm/chains/shard.py, evm/chains/tester/__init__.py, evm/utils/db.py, evm/vm/forks/sharding/computation.py
Need to fix `sharding`  branch after rebasing.
1. Relocated `evm.chains.chain.Chain` -> `evm.chain.chains.base.Chain`.
2. Some minor fixes for #397 .
=> Fix sharding branch after rebasing

evm/db/trie.py, evm/utils/state.py, evm/vm/forks/sharding/vm_state.py, evm/vm_state.py, p2p/chain.py
=> p2p: ChainSyncer now fetches block bodies

trinity/chains/__init__.py, trinity/chains/ropsten.py, trinity/db/chain.py
This adds more type hints to trinity
=> More type annotations for Trinity

evm/tools/test_builder/test_builder.py, tests/fillers/build_json.py, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasAfterCall.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasFailBefore.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasFailThereafter.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasInCall.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasInsufficientBalance.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasNormal.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasOmitted.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasRepeated.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasRepeatedSameGasprice.json, tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasZeroGasprice.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasAfterCall.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasFailBefore.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasFailThereafter.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasInCall.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasInsufficientBalance.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasNormal.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasOmitted.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasRepeated.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasRepeatedSameGasprice.json, tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasZeroGasprice.json, tests/fillers/vm_fillers/paygas_fillers.py
=> Extend paygas JSON tests

p2p/chain.py
See: https://github.com/ethereum/py-evm/pull/441#discussion_r173282554
Minor security issue allowing for db bloat by malicious parties during fast sync.
Validate that the `receipt_root` is in the list of pending receipt roots we expect to receive.
> DISCLAIMER: At first glance it just looked like a cute picture of a flying kitten.
=> Add validation to receipt root prior to persisting to db

p2p/chain.py
Doing that uses a lot of CPU cycles and was slowing down the fast sync
significantly.
=> p2p: ChainSyncer now uses a ProcessPoolExecutor to generate trie data

evm/utils/blobs.py
This adds type hints for the blob utils.
=> Add type hints for blob utils

evm/rlp/accounts.py, evm/rlp/blocks.py, evm/rlp/collations.py, evm/rlp/headers.py, evm/rlp/logs.py, evm/rlp/receipts.py, evm/rlp/sedes.py, evm/rlp/transactions.py, evm/utils/env.py, tox.ini
evm/rlp lacked type hints
Added type hints
=> Add type hints for evm/rlp

evm/computation.py, evm/logic/call.py, evm/logic/storage.py, evm/logic/system.py
after this pr, I will change gas_meter to _gas_meter
=> added return_gas and refund gas to computation class

evm/vm/forks/sharding/vm_state.py, evm/vm/forks/spurious_dragon/vm_state.py
See #368.
Implemented the `BaseTransactionExecutor` for `ShardingVMState`.
=> Sharding transaction executor

tests/p2p/peer_helpers.py
That way we can use crypto backends (e.g. pycryptodome) that don't
provide a copy() API like pysha3
=> p2p: Refactor test helper to no longer depend on keccak.copy()

p2p/chain.py
Post-Byzantium blocks may have identical receipts, and we don't need to
fetch them multiple times.
=> p2p: ChainSyncer avoids requesting receipts that are already pending

evm/db/chain.py, tests/p2p/integration_test_helpers.py
Also use it in p2p's FakeAsyncChainDB
Closes #495
=> evm/db: New non-journaled version of ChainDB

tests/sharding/fixtures.py
Latest web3 beta requires explicit opt-in of account features.
Added conditional opt-in.
=> Handle latest web3 beta, enabling accounts features

eth_typing/enums.py, evm/tools/fixture_tests.py, tests/json-fixtures/test_state.py, tests/json-fixtures/test_transactions.py, tox.ini
The fixtures where outdated. (See #208 
I tried to address #208 and updated the fixtures and tried to refactor the transaction tests to match the new structure. However, I feel like I might be missing something and could use some guidance. The main thing I'm wondering about goes as follows.
The old transaction fixtures looked like this.
[TransactionTests/ttFrontier/TransactionWithGasLimitOverflow63_1.json](https://github.com/ethereum/tests/blob/6df9b4ad039ff0043ca75579979f945598898eb3/TransactionTests/ttFrontier/TransactionWithGasLimitOverflow63_1.json)
```json
{
"TransactionWithGasLimitOverflow63_1" : {
"_info" : {
"comment" : "",
"filledwith" : "cpp-1.3.0+commit.6e0ce939.Linux.g++",
"lllcversion" : "Version: 0.4.18-develop.2017.10.6+commit.6c09e32c.Linux.g++",
"source" : …
```
=> Update fixtures / transaction tests

p2p/chain.py, p2p/lightchain.py, p2p/peer.py, p2p/state.py, p2p/sync.py
For now it just runs ChainSyncer to fast-sync chain data, followed by
the StateDownloader
=> p2p: Implement FullNodeSyncer

p2p/peer.py
Also changes its get_nodes_to_connect() to not return nodes always in
the same order.
=> p2p: Add more ropsten nodes to HardCodedNodesPeerPool

evm/db/shard.py, evm/exceptions.py, evm/utils/db.py, tests/database/test_shard_db.py
Add a basic shard db that should be sufficient for the minimal sharding protocol.
Referencing #530
=> Add ShardDB

evm/db/state.py, evm/exceptions.py, evm/vm/state.py, setup.py, tests/core/vm/test_vm_state.py, tests/p2p/test_state_sync.py
=> Use a lru cache for MainAccountStateDB._get_account()

evm/db/batch.py, tests/database/test_batch_db.py
[issue 160](https://github.com/ethereum/py-evm/issues/160)
warps a cache with underlying db and use context manager to apply batch updates
=> add BatchDB to allow commit DB update all fail or all success

setup.py
Just some very minor formatting cleanup to `setup.py`.
=> minor formatting cleanup to setup.py

evm/db/batch.py, tests/database/test_base_db_api.py, tests/database/test_batch_db.py, tests/database/test_journal_db.py
- The `BatchDB` implementation had some bugs surrounding key removal.
- Duplication between tests dealing with base db API
- Common test suite for base database API
- Improved `BatchDB` tests to cover edge cases.
=> Improvements to db tests

evm/constants.py, evm/db/batch.py, evm/utils/blobs.py, tests/core/test_blob_utils.py
Implement blob serialization as described here: https://ethresear.ch/t/blob-serialisation/1705
Flags are not yet implemented (they are set to 0 when writing and ignored when reading) because I can't see right now what the interface would look like ideally. We should revisit this when state execution is implemented.
=> Blob serialization

evm/db/chain.py
This is a very easy/safe thing to cache and provides a big performance
improvement for fast sync as that involves frequently looking up recent
block headers.
Part of #542 as well
=> ChainDB: cache block header RLP decoding

evm/exceptions.py, p2p/exceptions.py, p2p/peer.py
As described in #591 the exceptions in p2p did not have a common project base exception yet.
Added base exceptions and also added docstrings.
=> Add common base exception to all p2p exceptions

evm/db/chain.py
That method, which is rather expensive since it may read a fair amount of data
from the DB and then decode it, is called several times for every block
imported
Added a small LRU cache, which provides a significant improvement
=> Use an LRU cache for ChainDB.get_block_transactions()

.circleci/config.yml, .circleci/merge_pr.sh
The CI job that fetches the PRs base branch via the GitHub API sometimes fails but works after retry.
Extracted the command into a standalone script and configured two more commands that only run if the previous command failed.
This may not be the most elegant way to solve this but my Google fu didn't yield anything else and it seems to get the job done.
=> Retry flaky CI job up to three times

evm/chains/__init__.py, evm/chains/base.py, evm/vm/forks/frontier/state.py, p2p/chain.py, p2p/protocol.py, tests/p2p/integration_test_helpers.py
See #330 for more info
The next step is to change https://github.com/ethereum/py-evm/blob/master/p2p/sync.py#L11 to run the new RegularChainSyncer once it completes the fast sync.
=> Implement regular (i.e. block-processing) chain sync

p2p/chain.py, p2p/sync.py
=> FullNodeSyncer now calls RegularChainSyncer after state download

p2p/auth.py, p2p/server.py
- It now creates the endpoint for DiscoveryProtocol and bootstraps it
- Also runs the PeerPool in its run() method
- Handle DecryptionErrors (which are expected) in receive_handshake()
- Handle TimeoutErrors in receive_handshake()
- Fix the _test() function
=> p2p: A few misc fixes to Server

p2p/server.py, setup.py
=> p2p: Add NAT port-mapping support to p2p.Server

p2p/chain.py, p2p/sync.py
Also add some docstrings and renames ChainSyncer to FastChainSyncer to
hopefully make a few things clearer.
Closes #654
=> p2p: Run fast-sync only when local head is older than 24h

evm/exceptions.py, evm/vm/state.py, p2p/sync.py, tests/core/vm/test_vm_state.py
=> p2p: Ensure we have the head's state_root before starting regular sync

p2p/discovery.py, p2p/peer.py, p2p/server.py, p2p/sharding.py, tests/p2p/integration_test_helpers.py, tests/p2p/test_server.py, tests/p2p/test_sharding.py, trinity/cli_parser.py, trinity/main.py
=> p2p: Server now listens on all network interfaces

tests/p2p/peer_helpers.py, tests/p2p/test_sharding.py
- No longer use/run a p2p.Server
- No longer run a PeerPool nor access its private bits
- Use peer with directly connected reader/writers, avoiding going
through the network
=> p2p: Improve sharding tests

evm/chains/base.py
It would be *weird* if a Chain subclass configured the VMs differently than the `vm_configuration` standard. So weird that it would feel broken. So implementing `get_vm_class_by_block_number()` in every subclass is redundant.
Moved `vm_configuration` and `get_vm_class_by_block_number()` to `BaseChain`.
Inspired by #717
=> Make vm_configuration a standard across all Chains

p2p/chain.py, p2p/exceptions.py
=> p2p: Cleanly abort sync if there are no connected peers

evm/chains/base.py, evm/vm/base.py
Follow up work from #707 
The uncle validation was embeded within the `VM.validate_block` which is problematic since uncles are for *other* block numbers, meaning that in situations where we are immediately after the boundary of two fork rules, we'll be running the validation for the new fork on blocks which were mined in the old fork.
Move the orchestration and execution of this up to the `Chain` class.
=> Fixes for uncle validation

evm/vm/memory.py, evm/vm/message.py, evm/vm/stack.py, evm/vm/state.py, evm/vm/transaction_context.py
- Closes #520 
- Added `__slots__` into objects under the Computation class.
=> Add __slots__ into objects under the Computation class

p2p/chain.py
Currently trinity full sync output looks roughly like this:
```bash
INFO  05-22 14:55:50       chain  Got headers segment starting at #784215
INFO  05-22 14:55:52       chain  Imported chain segment, new head: #784406
INFO  05-22 14:55:52       chain  Fetching chain segment starting at #784407
INFO  05-22 14:55:52       chain  Got headers segment starting at #784407
INFO  05-22 14:55:53       chain  Imported chain segment, new head: #784598
INFO  05-22 14:55:53       chain  Fetching chain segment starting at #784599
INFO  05-22 14:55:54       chain  Got headers segment starting at #784599
INFO  05-22 14:55:56       chain  Imported chain segment, new head: #784790
INFO  05-22 14:55:56       chain  Fetching chain segment starting at #784791
INFO  05-22 14:55:56       chain  Got headers …
```
=> Reduce noise in fast sync terminal output

docs/guides/evm/index.rst, docs/guides/evm/understanding_the_mining_process.rst, evm/consensus/pow.py, evm/vm/forks/frontier/__init__.py
The docs don't cover the basics of the mining process yet.
Started writing on a guide.
=> Add understanding mining guide

p2p/chain.py
#773 
- Use the full `headers` set to ensure unexpected parts are **really** unexpected.
- Separately log duplicate parts at a lower warning level.
=> quiet terminal output on unexpected parts

p2p/chain.py, p2p/exceptions.py
=> p2p: When requesting block parts use only peers that are supposed to have them

p2p/chain.py, tests/p2p/test_sync.py
=> p2p: Fix a bug when calculating the TD of the current header batch

evm/vm/base.py, trinity/db/base.py
Fixes #811 
`DBProxy` was proxying `__getitem__` to `get`. Proxy to `__getitem__` instead.
=> Raise KeyError when requesting a key through DBProxy

docs/guides/trinity/quickstart.rst
Quickstart needed some extra info
- added thing about `--preferred-node`
- added thing about `--light`
- added thing about `--ropsten`
=> Update trinity quickstart

tests/conftest.py, tests/core/conftest.py, tests/trinity/conftest.py, tests/trinity/core/json-rpc/test_ipc.py, trinity/rpc/main.py, trinity/rpc/modules/__init__.py, trinity/rpc/modules/net.py
Missing endpoint for `net.version` call.
Added it.
=> Add net.version rpc endpoint

docs/guides/evm/understanding_the_mining_process.rst
Mining guide in docs didn't demonstrate how to include transactions.
Added another paragraph that demonstrates how to include a simple transaction.
This PR also includes two another change that is *driven* by the docs and hence included in this PR.
I added a `get_transaction_nonce` API to the `VM` class. Reasoning is that it feels not very ergonomic to drill into `vm.state.account_db` in order to get a nonce. I also considered setting the `nonce` *implicitly* as part of the `create_unsigned_transaction` API if no `nonce` is passed. However, I believe there are still scenarios where one needs to retrieve the `nonce` directly which brings me back to the point that drilling into `vm.state.account_db` feels not very ergonomic (and may even straight violate the general principle of …
=> Elaborate on tx handling in "Understanding mining" guide

p2p/chain.py
during fast sync the `GetBlockHeaders` message was being silently ignored.  This resulted in the requesting node dropping us as a "useless peer"
Return an empty list of headers.  https://github.com/ethereum/py-evm/issues/846 tracks an issue to try and optimistically return the requested headers.
=> Respond to GetBlockHeaders command during fast sync

p2p/chain.py, p2p/constants.py, p2p/peer.py, p2p/server.py, p2p/state.py, p2p/sync.py, tests/p2p/integration_test_helpers.py, tests/p2p/test_server.py
`PeerPool.min_peers` was no longer used
Removed it
=> remove min_peers

p2p/peer.py
And yet another stab at fixing max peer enforcement.
=> Yet another fix for enforcing max peers

docs/guides/trinity/quickstart.rst
Missing Keyword Install
Added Keyword Install
=> apt-get install

evm/chains/base.py
`MainnetTesterChain` was overriding `validate_seal` to do nothing, but this had no effect as it was not being used by `validate_block`.
Add `validate_seal` in the `Chain` again.
=> Reintroduce validate_seal method of Chain class

p2p/peer.py, tests/p2p/peer_helpers.py, tests/p2p/test_sharding.py
=> p2p: Peer now supports multiple subscribers

.circleci/config.yml, evm/utils/version.py, scripts/benchmark/checks/__init__.py, scripts/benchmark/checks/base_benchmark.py, scripts/benchmark/checks/import_empty_blocks.py, scripts/benchmark/checks/mine_empty_blocks.py, scripts/benchmark/checks/simple_value_transfers.py, scripts/benchmark/run.py, scripts/benchmark/utils/address.py, scripts/benchmark/utils/chain_plumbing.py, scripts/benchmark/utils/format.py, scripts/benchmark/utils/meters.py, scripts/benchmark/utils/reporting.py, scripts/benchmark/utils/shellart.py, scripts/benchmark/utils/tx.py, setup.py, tox.ini
Missing benchmark suite (See #592 )
This PR adds a first rudimentary version of a benchmarking suite under `evm.tools.benchmark`. It defines some utilities as well as `BaseBenchmark` class that benchmarks are expected to derive from and tries to generalize as much as possible from the heavy lifting so that benchmark implementations should be rather slim.
Here's a gif of it in action.
We should still keep #592 open and I intend to continue to work on this but I feel this is good enough to be given another review and potentially getting merged as groundwork.
=> Add benchmarking suite

p2p/peer.py, p2p/protocol.py, tests/p2p/integration_test_helpers.py
=> p2p: Include (hard-coded) frame data in msg headers

p2p/auth.py
=> p2p: Correctly handle peers that disconnect before sending the auth ack

p2p/chain.py, p2p/exceptions.py, p2p/lightchain.py, p2p/peer.py, p2p/service.py, p2p/state.py, tests/p2p/test_lightchain_integration.py
=> p2p: Consolidate PeerPool APIs to get peers from which to fetch data

docs/api/evm/api.db.rst, docs/api/evm/db/api.db.account.rst, docs/api/evm/db/api.db.backends.rst, docs/api/evm/db/api.db.chain.rst, docs/api/evm/db/api.db.journal.rst, docs/api/evm/index.rst
Database APIs aren't covered in docs yet
Adds docs for database APIs
=> Docs: Cover database APIs

p2p/peer.py, p2p/server.py
This is yet another attempt to catch the MalformedMessage exception at the right place. Seems to be the cockroach of issues :)
Fixes #882
Moved exception handling to the proper place
=> Hunting the cockroach

setup.py
#958
Removed the useless dependencies.
=> Remove all aiohttp, and async_lru from evm

trinity/chains/light.py
Exception due to missing methods on the `LightDispatchChain`
```
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/salgado/src/py-evm/trinity/utils/profiling.py", line 31, in inner
return fn(*args, **kwargs)
File "/home/salgado/src/py-evm/trinity/utils/logging.py", line 118, in inner
return fn(*args, **inner_kwargs)
File "/home/salgado/src/py-evm/trinity/main.py", line 235, in launch_node
node = NodeClass(chain_config)
File "/home/salgado/src/py-evm/trinity/nodes/light.py", line 54, in __init__
self.create_and_add_tx_pool()
File "/home/salgado/src/py-evm/trinity/nodes/base.py", line 106, in …
```
=> Implement missing abstract methods in LightDispatchChain

evm/vm/forks/tangerine_whistle/__init__.py, p2p/cancel_token.py, p2p/constants.py, p2p/exceptions.py, p2p/lightchain.py, p2p/peer.py, p2p/service.py, tests/p2p/test_lightchain_integration.py
Fixes #849 
- Modify API to take the address of the contract to check
- Request the account info to get the code_hash to validate against
- Drop a peer with subprotocol error if they give us a bad code hash
=> Light client: validate contract code with account

p2p/les.py
Our light client was recently extended to serve headers and relay
transactions, so we should advertise that during the handshake
=> p2p: Announce serveHeaders/txRelay during LES handshake

setup.py
There was [a new mypy 0.620 release](http://mypy-lang.blogspot.com/2018/07/mypy-0620-released.html).
Set newer version n `setup.py`
=> Upgrade mypy to version 0.620

p2p/peer.py, trinity/plugins/builtin/tx_pool/pool.py
To help investigate what's going on in #1032
=> Logging changes to improve debugging on TxPool issues

docs/api/eth/db/api.db.chain.rst, docs/guides/eth/building_an_app_that_uses_pyevm.rst, docs/guides/eth/index.rst
So, far, we don't have a guide that shows how to use `Py-EVM` as an actual library to build things. Frankly, most of this isn't really `Py-EVM` specific and falls more into a "How to get started with Python" category but I feel it doesn't hurt to be as helpful as possible especially when it comes to onboarding new peoplel to the ecosystem.
Added simple guide that shows how to clone a boilerplate repo, add `Py-EVM` as a dependency, install it, and code a very very simple script that uses Py-EVM
**The code is written based on the latest release. Might be worth cutting a new release soon and then rebasing this PR (as opposed to merging and breaking silently soon** :sweat_smile:
=> Add simple guide to show how to use Py-EVM as a library

trinity/main.py
Fixes #1040 
- at end of fix-unclean-shutdown, remove `db.ipc` file, and log out what happened
=> fix-unclean-shutdown: remove db.ipc, if present

p2p/chain.py, p2p/utils.py, tests/p2p/test_utils.py
Fixes #1036 
- Extract to a utility for easier testing
- Added the example from the issue, plus a few corner cases
Could probably do a few more cases, but ran out of time today. If any obviously missing cases jump out, please comment!
=> Fix header number sequence generation

p2p/chain.py
=> p2p: Add some more logging statements to ChainSyncer

eth/db/chain.py
When adding canonical tx hash indices for the block being persisted,
lookup the transactions directly from the block and not from the DB.
This gives us a big performance boost during a fast sync
Part of #1065
=> Optimize ChainDB.persist_block() for the common case

setup.py
https://github.com/ethereum/py-evm/pull/1112#issuecomment-409251348
https://github.com/pytest-dev/pytest-asyncio/issues/89
WIP
=> Fix CI failure due to upstream fixture breakage

tests/trinity/core/p2p-proto/test_state_sync.py, trinity/sync/full/hexary_trie.py, trinity/sync/full/state.py
=> Use a LevelDB instance as the node cache in StateDownloader

eth/chains/base.py, eth/vm/base.py, tests/trinity/conftest.py, tests/trinity/core/json-rpc/test_ipc.py, tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py, trinity/chains/light.py, trinity/rpc/format.py, trinity/rpc/ipc.py, trinity/rpc/modules/eth.py, trinity/utils/validation.py
Part of #1061, implementing `eth_estimateGas` (and the trivial `eth_accounts`)
Linked into existing gas estimation. Add a bunch of tests, and a smattering of refactors/touchups in somewhat-related code.
=> Add RPC methods: eth_estimateGas & eth_accounts

p2p/peer.py, p2p/protocol.py, trinity/protocol/common/handlers.py, trinity/protocol/common/managers.py, trinity/protocol/eth/handlers.py, trinity/protocol/eth/managers.py, trinity/protocol/eth/peer.py, trinity/protocol/les/managers.py, trinity/protocol/les/peer.py
=> Track and report peer response size/time

p2p/discovery.py, p2p/service.py, tests/p2p/test_service.py, trinity/server.py
If a daemon finishes while its parent is still running, the parent terminates itself.
Closes: #679
=> BaseService now terminates itself if a daemon dies unexpectedly

trinity/extensibility/plugin_manager.py
Just cleaning up a typo I introduced.
Magic
=> Fix typo in constant

p2p/peer.py, p2p/service.py
fixes #1234 
Added a new *boot* sequence to the `Peer` class which performs the DAO fork check.
=> Move DAO fork check into Peer class

p2p/discovery.py, tests/p2p/test_discovery.py, trinity/cli_parser.py, trinity/config.py, trinity/nodes/light.py, trinity/server.py, trinity/utils/chains.py
With this we should be able to find LES nodes much faster. Still experimental, but eventually we
should turn it on by default when running in light mode, like geth does.
=> New cmdline flag to enable v5 topic discovery

p2p/peer.py
Peer._boot() would wrongly log an exception in case we got an
OperationCancelled (e.g. because the remote disconnected) during the DAO
fork check.
=> Do not log an error when remote disconnects during DAO fork check

trinity/protocol/les/peer.py
=> Fail handshake when LES peer doesn't serve headers

scripts/chainsync.py, scripts/db-shell.py, scripts/peer.py
Also move a couple test scripts into the scripts/ dir
=> New script to access the chain DB via an interactive python shell

trinity/p2p/handlers.py, trinity/sync/full/chain.py, trinity/sync/light/chain.py
=> PeerRequestHandler: ignore requests dispatched after peer disconnected

trinity/sync/common/chain.py
When a new peer is selected to sync headers, it may start from far
behind where the old peer left off (if there is a large backlog of bodies being downloaded,
during fast sync).
We were re-requesting the same headers from them
in an infinite loop (only resolved when we disconnect from the peer
and try again, after taming the backlog).
Update the starting header to the next batch or the canonical head (minus reorg distance), whichever is larger.
=> Enable header peer catchup

p2p/ecies.py
An invalid public key was causing an uncaught `ValueError` during handshake
Catch the `ValueError` raised by the encryption library on a bad public key, and re-raise a `DecryptionError`.
=> Fix unhandled ValueError raised during handshake

setup.py
Closes #1318 
https://github.com/ethereum/pyrlp/pull/99
and then upgrade pyrlp.
=> Upgrade pyrlp to 1.0.3

eth/tools/builder/chain/builders.py, eth/utils/bitfield.py, eth/utils/blake.py, eth/utils/bls.py, setup.py, tests/core/bitfield-utils/test_bitfields.py, tests/core/blake-utils/test_blake.py, tests/core/bls-utils/test_bls.py, tests/core/builder-tools/test_chain_initializer.py, tests/core/helpers.py
Fixes #1322
I was thinking of putting these APIs to `eth.beacon_chain.utils` at the beginining, but those functions will also be used for shard chains, so I put to `eth.utils` in the end.
(yay I miss cute animal pictures!)
=> Added beacon chain utils

tests/core/chain-object/test_create_transaction.py
Not test coverage for creating transactions via the `Chain` object.
Added some tests to exercise the code paths.
=> Add create_transaction tests

eth/beacon/config.py, eth/beacon/constants.py, eth/beacon/genesis_helpers.py, eth/beacon/helpers.py, eth/beacon/utils/random.py, tests/beacon/conftest.py, tests/beacon/helpers.py, tests/beacon/test_genesis_helpers.py, tests/beacon/test_helpers.py, tests/beacon/utils/test_random.py
#1339 - 1. Move all pure functions
1. Move all `helpers.py` functions to `eth/beacon/helpers.py`
2. Move all `genesis_helpers.py` functions to `eth/beacon/genesis_helpers.py`
=> Port beacon chain helper functions

tox.ini
=> Remove unneeded dependency in tox.ini

tests/trinity/core/json-rpc/test_ipc.py, trinity/protocol/common/peer.py, trinity/protocol/les/peer.py, trinity/rpc/modules/eth.py, trinity/sync/common/chain.py, trinity/sync/common/events.py, trinity/sync/common/types.py
Implemented eth_syncing endpoint as per https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing specs.
=> Implement eth_syncing endpoint

trinity/__init__.py, trinity/cli_parser.py, trinity/config.py, trinity/extensibility/plugin.py, trinity/initialization.py, trinity/main.py, trinity/plugins/builtin/tx_pool/pool.py, trinity/protocol/common/handlers.py, trinity/protocol/common/managers.py, trinity/protocol/common/validators.py, trinity/protocol/eth/peer.py, trinity/protocol/eth/validators.py, trinity/protocol/les/peer.py, trinity/protocol/les/proto.py, trinity/sync/light/service.py, trinity/tools/async_process_runner.py, trinity/utils/chains.py, trinity/utils/headers.py, trinity/utils/log_messages.py, trinity/utils/logging.py, trinity/utils/version.py
Inconsistent use of `.format(..)` and f-string style string formatting in our python 3.6 code.
Updated all code in `p2p` and `trinity` module to use f-strings.
=> Update to use f-strings

trinity/plugins/builtin/ethstats/ethstats_service.py
Previously, the Ethstats Plugin waited on the PeerCount
forever. But since the PeerPool is not ready by the time
that the Ethstats plugin sends the request, it just hangs
there waiting and at some point the websocket connection
times out.
This change introduces a timeout of 500ms for the PeerPool
to answer. If the PeerPool does not answer within 500ms,
we assume 0 peers and move on.
Fixes #1379
I tested this against ethstats and it seems the plugin stays alive and reports the peer count correctly as seen in the following screenshot.
=> Ensure ethstats plugin uses a timeout to wait on PeerCount

setup.py
New mypy version is out http://mypy-lang.blogspot.com/2018/10/mypy-0640-released.html
Upgraded in `setup.py`
=> Upgrade to mypy 0.641

eth/vm/computation.py
The organization of the methods for our `Computation` object wasn't consistent and had room for improvement.
Moved things around to better group them by functionality.
=> re-organize Computation methods

trinity/protocol/bcc/commands.py, trinity/protocol/bcc/proto.py
=> Define beacon chain network commands

trinity/nodes/base.py
Code used a hack that isn't needed anymore.
Removed hack.
=> Remove obsolete lahja hack

p2p/cancellable.py, tests/p2p/test_service.py
I wanted a clean way to iterate through an asynchronous generator, cancelling early if the service exits. Didn't find any good built-in options.
Added `wait_iter` used like:
```py
async for val in service.wait_iter(my_async_iterator()):
do_stuff(val)
```
(The intent is to roughly match the `await self.wait(async_method())` API)
=> New cancellable asynchronous iterators

tests/trinity/core/p2p-proto/test_bcc.py, trinity/protocol/bcc/commands.py, trinity/protocol/bcc/context.py, trinity/protocol/bcc/peer.py, trinity/protocol/bcc/proto.py
This implements the protocol class and the basis for the peer class for the beacon chain network. It's mostly boilerplate, tests, and a little handshake logic.
=> Implement bcc protocol class and handshake

p2p/discovery.py, p2p/kademlia.py
Wasn't connecting to nodes on bad wifi
Add some more logging info to discovery, and increase the general timeout (which ping/pong uses).
=> Peer discovery on high-latency connection

tests/trinity/core/p2p-proto/bcc/helpers.py, tests/trinity/core/p2p-proto/bcc/test_commands.py, tests/trinity/core/p2p-proto/bcc/test_handshake.py, tests/trinity/core/p2p-proto/bcc/test_requests.py, trinity/protocol/bcc/commands.py, trinity/protocol/bcc/peer.py, trinity/protocol/bcc/servers.py, trinity/protocol/common/servers.py
Implements handling of and responding to beacon chain `GetBeaconBlocks` messages.
=> Beacon block request handler

eth/beacon/constants.py, eth/beacon/db/chain.py, eth/beacon/db/schema.py, eth/beacon/helpers.py, eth/beacon/state_machines/configs.py, eth/beacon/state_machines/forks/serenity/configs.py, eth/beacon/types/attestation_data.py, eth/beacon/types/blocks.py, eth/beacon/types/crosslink_records.py, eth/beacon/types/proposal_signed_data.py, eth/beacon/types/states.py, tests/beacon/conftest.py, tests/beacon/db/test_chaindb.py, tests/beacon/helpers.py, tests/beacon/test_helpers.py, tests/beacon/types/test_crosslink_record.py, tests/beacon/types/test_proposal_signed_data.py, tests/beacon/types/test_states.py, tests/trinity/core/p2p-proto/bcc/helpers.py, tests/trinity/core/p2p-proto/bcc/test_commands.py, tests/trinity/core/p2p-proto/bcc/test_requests.py, trinity/protocol/bcc/commands.py, trinity/protocol/bcc/proto.py, trinity/protocol/bcc/servers.py
Fixes #1575 
Fixes #1595
1. Sync the latest constants
2. Add `slot` to `BeaconState`
2. Replace `*_hash` with `*_root`
=> State slot and *_hash to *_root and constants updates

docs/guides/trinity/architecture.rst, docs/guides/trinity/writing_plugins.rst, eth/chains/base.py, eth/db/chain.py, eth/vm/computation.py
Found some typos and minor grammatical bugs in docs.
I edited the appropriate places.
=> Medley of typo fixes

eth/beacon/state_machines/validation.py, eth/beacon/types/blocks.py, eth/beacon/types/proposal_signed_data.py, tests/beacon/state_machines/test_validation.py
Fixes #1639 
Followed the `specs` and most of the `helper` functions were used. Further added a `TODO` for replacing `flat hash` with `Tree Hash` in the future.
=> Implements validate_proposer_signature function

eth/tools/fixtures/helpers.py, eth/vm/logic/context.py, tests/core/opcodes/test_opcodes.py, tests/json-fixtures/test_blockchain.py
[A new release of the tests](https://github.com/ethereum/tests/releases/tag/v6.0.0-beta.3) has just been published! This branch updates the tests but does not yet resolve the 7 errors that causes.
=> Update fixtures to the v6.0.0-beta.3 release

tests/core/vm/test_rewards.py
=> Add some more tests for Rewards

eth/db/account.py
account_cache was declared but not used causing ~30% of performance degradation when accessing accounts.
Starting to use account_cache in get\set_account functions
=> enable account_cache

docs/fragments/doctest_explainer.rst, docs/guides/building_an_app_that_uses_pyevm.rst
A code example in the docs was broken
Updated example, migrated to doctest and added explainer about doctest syntax.
=> Fix example and migrate it to doctest

eth/vm/base.py
Occasionally, we want to build custom state from a VM class. It's possible but a little annoying, by doing something like:
```py
execution_context = header.create_execution_context(previous_hashes)                                           
VM.get_state_class()(db, execution_context, header.state_root)
```
This comes up during genesis generation in #1735 
Now, all that is hidden behind `VM.build_state(db, header, previous_hashes)`. Since `VM.state` uses `build_state()` it doesn't seem critical to add a separate test for it at this point.
=> Add VM.build_state()

eth/chains/base.py, eth/vm/base.py, eth/vm/forks/byzantium/__init__.py, eth/vm/forks/constantinople/state.py, eth/vm/forks/frontier/__init__.py, eth/vm/forks/frontier/state.py, eth/vm/state.py, tests/core/vm/test_vm.py
State was persisting after every apply_transaction call in all forks (https://github.com/ethereum/py-evm/issues/705)
State is not persisting after every apply_transaction call after Byzantium fork
=> Stop persisting state after Byzantium fork

eth/db/diff.py, tests/database/test_db_diff.py
Wanted to get information about a `DBDiff` in #1735 -- specifically a list of keys that have been updated.
Added `DBDiff.new_keys()` to return all keys that have been updated. While there, it made sense to add the companion methods:
- `DBDiff.new_items()` (the (key, value) pairs of all updated values)
- `DBDiff.deleted_keys()`
Also, added some basic tests that touch on all these.
=> DBDiff inspection

eth/tools/builder/chain/__init__.py, eth/tools/builder/chain/builders.py, eth/vm/forks/__init__.py, eth/vm/forks/istanbul/__init__.py, eth/vm/forks/istanbul/blocks.py, eth/vm/forks/istanbul/computation.py, eth/vm/forks/istanbul/headers.py, eth/vm/forks/istanbul/opcodes.py, eth/vm/forks/istanbul/state.py, eth/vm/forks/istanbul/transactions.py, tests/conftest.py, tests/core/builder-tools/test_chain_construction.py, tests/json-fixtures/test_transactions.py
Istanbul is coming! Multiple EIPs incoming!
This PR just adds the necessary boilerplate to start Istanbul updates. It does not integrate with anything at all yet. Basically dead code.
=> Prepare for Istanbul

docs/release_notes/index.rst
This is the long-running PR for release notes to be included in the next release.
Community contributors are welcome to comment below with your notes, or open a PR to merge into this branch.
Coders with write access are welcome to add commits on top. Please don't force push, though: it would be sad to accidentally blow away someone else's notes, due to concurrent force pushes.
=> Release notes for v0.2.0-alpha.43

docs/release_notes/index.rst
This is the long-running PR for release notes to be included in the next release.
Community contributors are welcome to comment below with your notes, or open a PR to merge into this branch.
Coders with write access are welcome to add commits on top. Please don't force push, though: it would be sad to accidentally blow away someone else's notes, due to concurrent force pushes.
=> Release notes for v0.3.0-alpha.1

eth/chains/mainnet/__init__.py, eth/chains/mainnet/constants.py, eth/chains/ropsten/__init__.py, eth/chains/ropsten/constants.py, eth/tools/builder/chain/__init__.py, eth/tools/builder/chain/builders.py, eth/vm/forks/__init__.py, eth/vm/forks/muir_glacier/__init__.py, eth/vm/forks/muir_glacier/blocks.py, eth/vm/forks/muir_glacier/computation.py, eth/vm/forks/muir_glacier/headers.py, eth/vm/forks/muir_glacier/opcodes.py, eth/vm/forks/muir_glacier/state.py, eth/vm/forks/muir_glacier/transactions.py, newsfragments/1901.feature.rst, tests/core/builder-tools/test_chain_construction.py, tests/core/tester/test_generate_vm_configuration.py
Implement Muir Glacier fork
- copy + rename from Istanbul
- calculate difficulty based on block number `9_000_000`
=> Implement Muir Glacier fork

eth/chains/mainnet/__init__.py
Now that `validate_header` has become an instance method it turned problematic to have the DAO check coupled with it. That is because in Trinity we need this check very early in the p2p process.
https://github.com/ethereum/trinity/blob/1a112b681a19f1321ac74588e4225aaf595d5dd5/trinity/protocol/common/boot.py#L84-L87
But obtaining an instance of the VM is also problematic since we can not provide all required dependencies.
Extracted the DAO check into a static method which `validate_header` just delegates to. During the boot we can just invoke the static method. This does also mean that we are not running the actual seal check at that point anymore but I think that is ok since it will run at a later stage anyway.
[//]: # (For important …
=> Extract DAO check into static function

setup.py
Need to Upgrade Py-RLP and Py-Trie
Changed `setup.py`
=> Upgrade RLP dependency

newsfragments/1998.internal.rst, tests/json-fixtures/blockchain/test_blockchain.py
=> Upgrade ethereum tests to v8.0.2

.deepsource.toml, eth/_utils/blake2/coders.py, eth/_utils/transactions.py, eth/consensus/clique/encoding.py, eth/db/account.py, eth/db/header.py, eth/tools/builder/chain/builders.py, eth/tools/fixtures/generation.py, eth/vm/computation.py, tests/core/chain-object/test_chain_get_ancestors.py, tests/core/chain-object/test_header_chain.py, tests/core/consensus/test_clique_encoding.py, tests/core/tester/test_generate_vm_configuration.py, tests/core/validation/test_eth1_validation.py, tests/core/vm/test_base_computation.py, tests/database/test_db_diff.py, tests/database/test_header_db.py
Hey :wave:, I'm a Developer Outreach at [DeepSource](https://deepsource.io/) and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality and performance improvements](https://deepsource.io/gh/akshgpt7/py-evm/) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Use literals instead of function calls to create data structures.
- Simplify the `if` statements.
- Remove calling `len()` for comparison.
- Refactor unnecessary use of comprehension.
- Remove unnecessary generators.
Here's a cute sloth :)
=> chore: Refactor code quality issues

newsfragments/2025.misc.rst
There was one more patch release in the tests repo, so I figured I'd update to the latest. 
=> Update test fixtures to v9.0.5

.gitignore, README.md, docs/contributing.rst, docs/guides/building_an_app_that_uses_pyevm.rst, docs/guides/quickstart.rst, eth/abc.py, eth/chains/base.py, eth/tools/builder/chain/builders.py, newsfragments/2036.doc.rst, newsfragments/2036.misc.rst
- Grammar updates by @joshklop in docs and code comments + some minor refactoring
- Updated the py-evm version used in docs examples
- Updated python versions in docs examples
- .[dev] -> ".[dev]" in docs code blocks for better compatibility across shells
- Remove gitter link in favor of promoting Discord as the primary support chat
#2009 & #2034
=> Documentation updates

docs/api/vm/api.vm.forks.rst
- Arrow Glacier fork sphinx api docs needed to be added
- Added Arrow Glacier fork sphinx api docs
=> Add Arrow Glacier sphinx api docs

docs/guides/understanding_the_mining_process.rst
=> typo in docs

eth/db/account.py, eth/vm/forks/berlin/transactions.py, eth/vm/forks/frontier/transactions.py, eth/vm/forks/london/transactions.py, eth/vm/logic/system.py, newsfragments/2110.bugfix.rst, tests/json-fixtures/blockchain/test_blockchain.py
Related to Issue #2075 
- Fix test failures related to updates to EIP-2681
=> Address changes to EIP-2681 (HighNonce)

eth/abc.py, eth/db/backends/base.py, eth/tools/factories/transaction.py, eth/vm/forks/frontier/transactions.py, eth/vm/forks/homestead/transactions.py, newsfragments/2117.internal.rst, setup.py
`mypy` and `mypy_extensions` versions were holding back typing updates elsewhere.
Bumped! Fixed new errors where I could, was unable to resolve typing in 2 spots.
=> bump mypy and fix related new errors

eth/consensus/clique/snapshot_manager.py, eth/db/account.py, eth/db/cache.py, eth/tools/builder/chain/__init__.py, eth/tools/builder/chain/builders.py, eth/vm/forks/__init__.py, eth/vm/forks/cancun/__init__.py, eth/vm/forks/cancun/blocks.py, eth/vm/forks/cancun/computation.py, eth/vm/forks/cancun/headers.py, eth/vm/forks/cancun/opcodes.py, eth/vm/forks/cancun/state.py, eth/vm/forks/cancun/transactions.py, tests/core/builder-tools/test_chain_construction.py
Merge Cancun classes into `cancun-network-upgrade` feature branch
=> Cancun network upgrade base branch

.circleci/config.yml, eth/abc.py, eth/vm/computation.py, eth/vm/forks/cancun/opcodes.py, eth/vm/logic/memory.py, eth/vm/memory.py, eth/vm/mnemonics.py, eth/vm/opcode_values.py, tox.ini
- Re: EIP-5656, use memoryview slice/assign. note that this has the correct performance characteristics; see that cpython uses memmove here: https://github.com/python/cpython/blob/d2f1b0eb4956b4923f111c7c740ba7ab25f3312d/Objects/memoryobject.c#L357
=> feat: add mcopy implementation

eth/db/storage.py, scripts/benchmark/contract_data/erc20.sol, tests/core/env-utils/test_env_list.py
=> chore: remove repetitive words

.circleci/config.yml, eth/abc.py, eth/chains/mainnet/__init__.py, eth/vm/computation.py, eth/vm/forks/cancun/__init__.py, eth/vm/forks/cancun/logic.py, eth/vm/forks/cancun/opcodes.py, eth/vm/forks/cancun/state.py, eth/vm/forks/frontier/computation.py, eth/vm/forks/frontier/state.py, eth/vm/forks/homestead/computation.py, eth/vm/forks/spurious_dragon/_utils.py, eth/vm/forks/spurious_dragon/computation.py, eth/vm/logic/system.py, newsfragments/2148.feature.rst, tests/core/opcodes/test_opcodes.py, tests/core/vm/test_base_computation.py, tests/json-fixtures/blockchain/test_blockchain.py, tox.ini
Implement https://eips.ethereum.org/EIPS/eip-6780
=> Implement selfdestruct eip6780

docs/cookbook/index.rst, eth/abc.py, eth/chains/tester/__init__.py, eth/db/atomic.py, eth/db/journal.py, eth/db/slow_journal.py
=> chore: fix some typos

eth/exceptions.py
=> chore: fix typo in comment

README.md, newsfragments/2173.internal.rst
=> Fix link to the getting started guide
